### ISSUE TITLE
Harbor portal-svc.yaml has no name on the port

### ISSUE THREAD

**Issue by ajchiarello** [bitnami/charts#1356]
**Which chart**: 

**Harbor  v2.2.0**

**Description**

When deploying with the Voyager ingress controller, the harbor login page in inaccessible. This is resolved by the following change to the harbor-portal service:

```diff
  ports:
-   - port: 80
+   - name: http
+     port: 80
      targetPort: http
```

**Steps to reproduce the issue:**

1. Install the helm chart to a kubernetes cluster using the voyager ingress controller, with `service.Type=Ingress`

**Describe the results you received:**

The portal page is not accessible until the harbor-portal service port is named.

**Describe the results you expected:**

The page to load automatically

**Additional information you deem important (e.g. issue happens only occasionally):**

This did not happen when using the nginx ingress controller (we are transitioning ingress controllers for an unrelated reason).

**Version of Helm and Kubernetes**:

- Output of `helm version`: 

```
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @ajchiarello 

I think this issue has already been addressed on a recent PR (see https://github.com/bitnami/charts/pull/1360).

Check https://github.com/bitnami/charts/blob/master/bitnami/harbor/templates/portal/portal-svc.yaml#L10

Could you please confirm the issue solved in the latest version of the chart (**2.3.2**)?

**Comment by ajchiarello** [comment]
I'm not seeing that version available in the repo - it looks like 2.2.0 is the published version. I ran 'helm repo update' with no change.

**Comment by juan131** [comment]
Hi @ajchiarello 

It takes some time (usually a few hours) since we merged the changes in the repo until they're available at the Helm repo (charts.bitnami.com). It's just a matter of time.

As you can check in the link below, the changes are already merged: 

- https://github.com/bitnami/charts/blob/master/bitnami/harbor/Chart.yaml

**Comment by ajchiarello** [comment]
Hi @juan131 - yes, I see the changes, and they all look good. I'm still not seeing the new version, but I can be patient and check it tomorrow.

**Comment by juan131** [comment]
Hi @ajchiarello 

There must be sth wrong in our sync process since it's taking too much time to update the Chart repository. I'll ping the team maintaining this so they can take a look.

Thanks for your consideration and patience.

**Comment by juan131** [comment]
Hi @ajchiarello 

Just a quick note to let you know that we fixed the issue and the repo has been updated:

```
$ helm repo update && helm search bitnami/harbor
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
NAME          	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/harbor	2.4.0        	1.8.1      	Harbor is an an open source trusted cloud native registry...
```

**Comment by ajchiarello** [comment]
hi @juan131  - thanks! I have the new version and it is working now.

**Comment by juan131** [comment]
Great @ajchiarello !!! Please do not hesitate to open a new issue if you struggle with this or any other chart.
