### ISSUE TITLE
[bitnami/harbor] - DevCenter API Page is broken

### ISSUE THREAD

**Issue by rajan123456** [bitnami/charts#14137]
### Name and Version

bitnami/harbor 16.1.2

### What steps will reproduce the bug?

1. Install the bitnami/harbor chart
2. Login to admin console -> Harbor API V2.0

Page fails to load.

### Are you using any custom parameters or values?

NA

### What is the expected behavior?

The DevCenter API Page (Swagger) should open successfully.

### What do you see instead?

The page opens to a custom 404 page and redirects to the homepage in a few seconds.

**Comment by Mauraza** [comment]
Hi @rajan123456,

I just installed harbor and everything is fine. Could you add more information? Did you use other values?

**Comment by rajan123456** [comment]
Hi @Mauraza - not using any overrides. This is happening with a fresh install of 16.1.2

'''
helm install darc-harbor bitnami/harbor 
'''

Opening the Harbor API V2.0 page (last option in the left side menu) gives a 404. It should show a swagger spec instead.

**Comment by Mauraza** [comment]
Hi @rajan123456,

You are right. I going to open an internal task to investigate it.

**Comment by mustdiechik** [comment]
the same problem.
Version v2.7.0-6113469

**Comment by Mauraza** [comment]
Hi @rajan123456,

With the PR should fix the issue,

**Comment by ChBerrich** [comment]
Hi @Mauraza,

Is this fix will work when we deploy with parameter exposureType: ingress ?
I deployed version 16.4.1 and still get the problem
Thanks

**Comment by hur** [comment]
Still having this issue on chart version 16.4.5, using exposureType: ingress. the devcenter page gives 404.
