### ISSUE TITLE
[bitnami/nginx-ingress-controller] Upgrading to 9.3.23 or above breaks some regex based path rules

### ISSUE THREAD

**Issue by justinmchase** [bitnami/charts#14324]
### Name and Version

bitnami/nginx-ingress-controller 9.3.25

### What steps will reproduce the bug?

1. Update chart to `9.3.23` (or greater)
2. Create an ingress with the following annotation
```yaml
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
```
and a rule with a regular expression path such as
```yaml
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /example(/|$)(.*)
        backend:
          service:
            name: api
            port:
              number: 8080
```
4. helm install
3. Observe an error in the nginx logs such as 
> W0113 05:28:08.270992       1 store.go:866] ingress default/example contains invalid path /example(/|$)(.*)

### Are you using any custom parameters or values?

N/A

### What is the expected behavior?

I expect my routing to just continue to work as is, or for breaking changes to be denoted by a major version increment.

### What do you see instead?

I see my ingress route failing to load, with the below error message:

> W0112 23:52:23.598515       1 store.go:866] ingress recovery-auth/recovery-auth contains invalid path /auth(/|$)(.*)

My ingress has this annotation:
```yaml
nginx.ingress.kubernetes.io/use-regex: "true"
```

and my rule has this path:
```yaml
path: /auth(/|$)(.*)
```

#### Full logs 

```
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:       1.6.0
  Build:         3474c33
  Repository:    https://github.com/kubernetes/ingress-nginx
  nginx version: nginx/1.21.6

-------------------------------------------------------------------------------

W0112 23:52:22.105073       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0112 23:52:22.105385       1 main.go:209] "Creating API client" host="https://10.0.0.1:443"
I0112 23:52:22.129459       1 main.go:253] "Running in Kubernetes cluster" major="1" minor="23" git="v1.23.8" state="clean" commit="83d00b7cbf10e530d1d4b2403f22413220c37621" platform="linux/amd64"
I0112 23:52:22.145254       1 main.go:86] "Valid default backend" service="recovery/recovery-nginx-default-backend"
I0112 23:52:22.313569       1 main.go:104] "SSL fake certificate created" file="/etc/ingress-controller/ssl/default-fake-certificate.pem"
I0112 23:52:22.409735       1 nginx.go:260] "Starting NGINX Ingress controller"
I0112 23:52:22.493108       1 event.go:285] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"recovery", Name:"recovery-nginx", UID:"1c79666d-f915-47b5-bf73-f966449008ae", APIVersion:"v1", ResourceVersion:"26795", FieldPath:""}): type: 'Normal' reason: 'CREATE' ConfigMap recovery/recovery-nginx
I0112 23:52:22.587166       1 backend_ssl.go:67] "Adding secret to local store" name="recovery/reco-certs"
I0112 23:52:23.597615       1 store.go:431] "Found valid IngressClass" ingress="recovery-provider/recovery-provider" ingressclass="nginx"
W0112 23:52:23.597781       1 store.go:866] ingress recovery-provider/recovery-provider contains invalid path /provider(/|$)(.*)
I0112 23:52:23.598117       1 event.go:285] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"recovery-provider", Name:"recovery-provider", UID:"a7e59484-0eaf-414b-b85a-7cf876c2d551", APIVersion:"networking.k8s.io/v1", ResourceVersion:"39321", FieldPath:""}): type: 'Normal' reason: 'Sync' Scheduled for sync
I0112 23:52:23.598406       1 backend_ssl.go:67] "Adding secret to local store" name="recovery-provider/reco-certs"
I0112 23:52:23.598460       1 store.go:431] "Found valid IngressClass" ingress="recovery-auth/recovery-auth" ingressclass="nginx"
W0112 23:52:23.598515       1 store.go:866] ingress recovery-auth/recovery-auth contains invalid path /auth(/|$)(.*)
I0112 23:52:23.598626       1 event.go:285] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"recovery-auth", Name:"recovery-auth", UID:"9810d46f-ab7c-40f6-9b57-4c9841d8fc97", APIVersion:"networking.k8s.io/v1", ResourceVersion:"26849", FieldPath:""}): type: 'Normal' reason: 'Sync' Scheduled for sync
I0112 23:52:23.598968       1 backend_ssl.go:67] "Adding secret to local store" name="recovery-auth/reco-certs"
I0112 23:52:23.688613       1 nginx.go:303] "Starting NGINX process"
I0112 23:52:23.688719       1 leaderelection.go:248] attempting to acquire leader lease recovery/ingress-controller-leader...
I0112 23:52:23.690066       1 controller.go:168] "Configuration changes detected, backend reload required"
I0112 23:52:23.694785       1 status.go:84] "New leader elected" identity="recovery-nginx-db64fb467-bl9pb"
I0112 23:52:23.887118       1 controller.go:185] "Backend successfully reloaded"
I0112 23:52:23.887293       1 controller.go:196] "Initial sync, sleeping for 1 second"
I0112 23:52:23.887431       1 event.go:285] Event(v1.ObjectReference{Kind:"Pod", Namespace:"recovery", Name:"recovery-nginx-db64fb467-7nzb9", UID:"2270185e-473a-4c97-8200-75144f33997d", APIVersion:"v1", ResourceVersion:"42667", FieldPath:""}): type: 'Normal' reason: 'RELOAD' NGINX reload triggered due to a change in configuration
E0112 23:52:28.580417       1 queue.go:78] "queue has been shutdown, failed to enqueue" key="&ObjectMeta{Name:sync status,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[]OwnerReference{},Finalizers:[],ManagedFields:[]ManagedFieldsEntry{},}"
I0112 23:52:28.894283       1 sigterm.go:47] "Exiting" code=0
I0112 23:53:10.616401       1 leaderelection.go:258] successfully acquired lease recovery/ingress-controller-leader
I0112 23:53:10.616477       1 status.go:84] "New leader elected" identity="recovery-nginx-db64fb467-7nzb9"
```

### Additional information

After rolling back to `9.3.18`, nginx works as expected again.

**Comment by justinmchase** [comment]
I tested each patch fix version from `9.3.18..9.3.22` which are all ok but I can confirm the break happens at `9.3.23`.

**Comment by justinmchase** [comment]
There's not much here in this version increment other than an update of the base image it seems:
https://github.com/bitnami/charts/commit/344d9da61c92bc426a3a4e08a26f4a4722d170fa

**Comment by justinmchase** [comment]
It looks like this change may have caused the issue:
https://github.com/kubernetes/ingress-nginx/pull/9309/files#diff-5f4da05f4716a8d567db533819486a784e3f4993c11021da3b569564c78a5935R866

Related to https://github.com/kubernetes/ingress-nginx/issues/9464

**Comment by javsalgar** [comment]
Hi

Looking at the issue, it seems that the problem lies un upstream nginx-ingress-controller. As soon as they release a new version, we will update the chart with the new image.

**Comment by netdip** [comment]
Yes faced similar kind of issue when we deployed chart version 9.3.25.

`W0117 06:37:55.746465       1 store.go:866] ingress kube-system/kubernetes-dashboard contains invalid path /k8s(/|$)(.*)`

**Comment by justinmchase** [comment]
This format of path replacement `/k8s(/|$)(.*)` is basically the canonical example for all regex paths in their documentation. So the number of users being affected by this seems potentially _very high_.

Given that this is a breaking "patch" fix version, I may recommend making a new patch fix of this repo, which reverts the version of the upstream `nginx-ingress-controller` dependency until its resolved. Otherwise probably a lot of people are going to be having a real bad time as they do an update and deploy one day and their routing completely breaks.

**Comment by ZitRos** [comment]
Confirming that the issue with regex still happens in chart version `9.3.26`.

```
W0122 20:32:13.830435       1 store.go:866] ingress du-dev/api contains invalid path /(/?)(.*)
```

**Comment by justinmchase** [comment]
Is this actually solved yet?

**Comment by javsalgar** [comment]
I'm not sure if the upstream devs released a new version of the application that solves the issue.

**Comment by parak** [comment]
Seems like this was possibly fixed upstream in 1.6.4: https://github.com/kubernetes/ingress-nginx/pull/9626

**Comment by javsalgar** [comment]
Then you should expect an automated update of the chart very soon.

**Comment by JustDoItSascha** [comment]
Still happening in version 9.3.32 and app version 1.6.4
