### ISSUE TITLE
[bitnami/mariadb-galera] Cluster fails upon statefulset rolling-update

### ISSUE THREAD

**Issue by iomarcovalente** [bitnami/charts#1602]
**Which chart:**

mariadb-galera v0.5.1

**Description**

After creating a 3 nodes cluster ( will refer to them as `node0`,`node1`,`node2` from here onwards) with default configuration using the chart, the galera cluster started fine and all nodes joined the cluster. I then attempted to delete nodes one by one, simulating an instance loss scenario. 

I deleted `node1`, `node2`, and `node0` in this order, and in this situation all the nodes after restarting joined the cluster fine.

I then tried to simulate a rolling update of the cluster but this made one of the nodes, `node0` in this case, fails restarting and went in a Crashloop state.

Also all the other nodes are now reporting that the cluster size is 1.

This is logs for node0 - the failing one:
```
 18:55:37.65 
 18:55:37.65 Welcome to the Bitnami mariadb-galera container
 18:55:37.65 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
 18:55:37.66 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
 18:55:37.66 Send us your feedback at containers@bitnami.com
 18:55:37.66 
 18:55:37.66 INFO  ==> ** Starting MariaDB setup **
 18:55:37.70 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
 18:55:37.73 INFO  ==> Initializing mariadb database...
 18:55:37.74 INFO  ==> Persisted data detected. Restoring...
 18:55:37.75 INFO  ==> ** MariaDB setup finished! **

 18:55:37.79 INFO  ==> ** Starting MariaDB **
2019-11-14 18:55:37 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.3.18-MariaDB-log) starting as process 1 ...
/opt/bitnami/mariadb/sbin/mysqld: Can't create file '/opt/bitnami/mariadb/logs/mysqld.log' (errno: 13 "Permission denied")
2019-11-14 18:55:37 0 [Note] WSREP: Read nil XID from storage engines, skipping position init
2019-11-14 18:55:37 0 [Note] WSREP: wsrep_load(): loading provider library '/opt/bitnami/mariadb/lib/libgalera_smm.so'
2019-11-14 18:55:37 0 [Note] WSREP: wsrep_load(): Galera 3.28(r0) by Codership Oy <info@codership.com> loaded successfully.
2019-11-14 18:55:37 0 [Note] WSREP: CRC-32C: using hardware acceleration.
2019-11-14 18:55:37 0 [Note] WSREP: Found saved state: 1e3ee577-06f0-11ea-a569-bbcb49e0fab2:-1, safe_to_bootstrap: 0
2019-11-14 18:55:37 0 [Note] WSREP: Passing config to GCS: base_dir = /bitnami/mariadb/data/; base_host = 100.70.129.124; base_port = 4567; cert.log_conflicts = no; cert.optimistic_pa = yes; debug = no; evs.auto_evict = 0; evs.delay_margin = PT1S; evs.delayed_keep_period = PT30S; evs.inactive_check_period = PT0.5S; evs.inactive_timeout = PT15S; evs.join_retrans_period = PT1S; evs.max_install_timeouts = 3; evs.send_window = 4; evs.stats_report_period = PT1M; evs.suspect_timeout = PT5S; evs.user_send_window = 2; evs.view_forget_timeout = PT24H; gcache.dir = /bitnami/mariadb/data/; gcache.keep_pages_size = 0; gcache.mem_size = 0; gcache.name = /bitnami/mariadb/data//galera.cache; gcache.page_size = 128M; gcache.recover = no; gcache.size = 128M; gcomm.thread_prio = ; gcs.fc_debug = 0; gcs.fc_factor = 1.0; gcs.fc_limit = 16; gcs.fc_master_slave = no; gcs.max_packet_size = 64500; gcs.max_throttle = 0.25; gcs.recv_q_hard_limit = 9223372036854775807; gcs.recv_q_soft_limit = 0.25; gcs.sync_donor = no; gmcast.segment = 0; gmcast.version = 0; pc.a
2019-11-14 18:55:37 0 [Note] WSREP: GCache history reset: 1e3ee577-06f0-11ea-a569-bbcb49e0fab2:0 -> 1e3ee577-06f0-11ea-a569-bbcb49e0fab2:-1
2019-11-14 18:55:37 0 [Note] WSREP: Assign initial position for certification: -1, protocol version: -1
2019-11-14 18:55:37 0 [Note] WSREP: wsrep_sst_grab()
2019-11-14 18:55:37 0 [Note] WSREP: Start replication
2019-11-14 18:55:37 0 [Note] WSREP: Setting initial position to 00000000-0000-0000-0000-000000000000:-1
2019-11-14 18:55:37 0 [Note] WSREP: protonet asio version 0
2019-11-14 18:55:37 0 [Note] WSREP: Using CRC-32C for message checksums.
2019-11-14 18:55:37 0 [Note] WSREP: backend: asio
2019-11-14 18:55:37 0 [Note] WSREP: gcomm thread scheduling priority set to other:0 
2019-11-14 18:55:37 0 [Warning] WSREP: access file(/bitnami/mariadb/data//gvwstate.dat) failed(No such file or directory)
2019-11-14 18:55:37 0 [Note] WSREP: restore pc from disk failed
2019-11-14 18:55:37 0 [Note] WSREP: GMCast version 0
2019-11-14 18:55:37 0 [Note] WSREP: (58d3b148, 'tcp://0.0.0.0:4567') listening at tcp://0.0.0.0:4567
2019-11-14 18:55:37 0 [Note] WSREP: (58d3b148, 'tcp://0.0.0.0:4567') multicast: , ttl: 1
2019-11-14 18:55:37 0 [Note] WSREP: EVS version 0
2019-11-14 18:55:37 0 [Note] WSREP: gcomm: connecting to group 'galera', peer 'test-mariadb-galera-headless.data.svc.cluster.local:'
2019-11-14 18:55:37 0 [Note] WSREP: (58d3b148, 'tcp://0.0.0.0:4567') connection established to 83a74926 tcp://100.70.32.148:4567
2019-11-14 18:55:37 0 [Note] WSREP: (58d3b148, 'tcp://0.0.0.0:4567') turning message relay requesting on, nonlive peers: 
2019-11-14 18:55:38 0 [Note] WSREP: declaring 83a74926 at tcp://100.70.32.148:4567 stable
2019-11-14 18:55:38 0 [Note] WSREP: view(view_id(NON_PRIM,58d3b148,20) memb {
	58d3b148,0
	83a74926,0
} joined {
} left {
} partitioned {
	b3c8ca5a,0
	d5b01fa6,0
	e8fdf81e,0
})
2019-11-14 18:55:41 0 [Note] WSREP: (58d3b148, 'tcp://0.0.0.0:4567') turning message relay requesting off
2019-11-14 18:56:08 0 [ERROR] WSREP: failed to open gcomm backend connection: 110: failed to reach primary view: 110 (Connection timed out)
	 at gcomm/src/pc.cpp:connect():158
2019-11-14 18:56:08 0 [ERROR] WSREP: gcs/src/gcs_core.cpp:gcs_core_open():209: Failed to open backend connection: -110 (Connection timed out)
2019-11-14 18:56:08 0 [ERROR] WSREP: gcs/src/gcs.cpp:gcs_open():1458: Failed to open channel 'galera' at 'gcomm://test-mariadb-galera-headless.data.svc.cluster.local': -110 (Connection timed out)
2019-11-14 18:56:08 0 [ERROR] WSREP: gcs connect failed: Connection timed out
2019-11-14 18:56:08 0 [ERROR] WSREP: wsrep::connect(gcomm://test-mariadb-galera-headless.data.svc.cluster.local) failed: 7
2019-11-14 18:56:08 0 [ERROR] Aborting
```

**Steps to reproduce the issue:**

Deploy helm chart with default settings

**Describe the results you received:**

Galera cluster failed restarting upon statefulset rollling update

**Describe the results you expected:**

I expected that the cluster would restart without issues

**Version of Helm and Kubernetes:**

**Output of helm version:**

Client: SemVer:"v2.15.2"

**Output of kubectl version:**

Client Version: Major:"1", Minor:"16"
Server Version: Major:"1", Minor:"12+"

**Comment by andresbono** [comment]
Hi @iomarcovalente, you mention that you simulated a rolling update. How did you do that exactly? We would like to reproduce the issue in order to help you.

**Comment by iomarcovalente** [comment]
I simply added an annotation and patched the statefulset to make it to roll update.
This was a consequence of #1601 , closing

**Comment by andresbono** [comment]
Thanks for letting us know, @iomarcovalente.

**Comment by MohammadrezaMasoumi** [comment]
I have same issue

**Comment by alemorcuq** [comment]
Hi, @MohammadrezaMasoumi.

This issue is very old and was already fixed. Do you mind opening a new issue detailing your case?

**Comment by dravenk** [comment]
Same issue. Not fixed.
Start nodes using below command.
```
helm install  my-release bitnami/mariadb-galera -f mariadb-galera/values.yaml
```
after DBS running successfully and then deleted all and reinstall.
```
helm delete my-release;helm install  my-release bitnami/mariadb-galera -f mariadb-galera/values.yaml
```
```
cat /bitnami/mariadb/mariadb/data/grastate.dat 
# GALERA saved state
version: 2.1
uuid:    7f974775-69fe-11ec-a64e-1b7a47ed85e0
seqno:   -1
safe_to_bootstrap: 1
```

**Comment by marcosbc** [comment]
Hi @dravenk, do you mind opening a new issue describing the issue, how to reproduce it and any additional info that may help reproduce it?
