### ISSUE TITLE
[bitnami/supabase] Cannot create a new user through studio /project/default/auth/users

### ISSUE THREAD

**Issue by jsmueller7** [bitnami/charts#16988]
### Name and Version

bitnami/supabase 0.3.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install the helm chart
2. Switch to studio
3. Open the default project
4. Swith to the "Authentication" tab (url: `<my-supabase-studio>/project/default/auth/users`)
5. Try to "Add user" by "Create new user" with auto-confirm enabled

### Are you using any custom parameters or values?

No

### What is the expected behavior?

A new user should be created.

### What do you see instead?

I am getting an error: `Failed to create user: invalid admin user`

### Additional information

The error goes away when I switch the container image for Supabase Auth. I am now using the container `supabase/gotrue` from docker hub. Probably you shouldn't be using the netlify code, that hasn't been updated since february 2022.

**Comment by migruiz4** [comment]
Hi @jsmueller7,

Thank you for reporting this issue. After further investigation, we have found an issue with the version of `gotrue` used in the Supabase chart, which is causing this issue.

We are currently working to fix this, I'm sorry for the inconvenience.

**Comment by migruiz4** [comment]
Thank you for sharing your workaround @stevefan1999-personal.

I'm sorry this task is still in our backlog, we will share any updates here.

**Comment by bdqfork** [comment]
Any update here? I missed same problem.

**Comment by stevefan1999-personal** [comment]
@bdqfork well...they have decided this isn't worth the effort and time to fix yet

**Comment by migruiz4** [comment]
Hi there, we have not forgotten about this issue.

In case it helps, this is planned to be developed after the holiday season.

**Comment by bartcode** [comment]
> Meanwhile, this would work:
> 
> ```yaml
> auth:
>   image:
>     repository: supabase/gotrue
>     tag: v2.91.0
> ```

I can confirm this works. And if you want to use a newer version: I noticed I also had to provide an extra environment variable (see below).

```yaml
auth:
  image:
    repository: supabase/gotrue
    tag: v2.143.0
  extraEnvVars:
    - name: API_EXTERNAL_URL
      value: "{your-external-api-url}"
```

**Comment by jotamartos** [comment]
Hi, 

Just a quick note to let you know that we just merged the changes to update the gotrue image to 2.x. You can learn more about the changes here:

https://github.com/bitnami/charts/pull/25070

This new version of the chart should be available soon

**Comment by evanrich** [comment]
adding 
```
auth:
  extraEnvVars:
    - name: API_EXTERNAL_URL
      value: "{your-external-api-url}"
```
still throws a localhost error when trying to add a new user for me
