### ISSUE TITLE
Multi-Replica Kafka Installation java.net.UnknownHostException

### ISSUE THREAD

**Issue by junsaw** [bitnami/charts#17715]
### Name and Version

bitnamicharts/kafka 1.23

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. helm install k8s-kafka oci://registry-1.docker.io/bitnamicharts/kafka -f kafka-4.yaml -n k8s-kafka
2. 

4.  

### Are you using any custom parameters or values?

Yes - kafka-4.yaml 

replicaCount: 4
containerPorts:
  client: 9092
  controller: 9093
  internal: 9094
  external: 9095

service:
  type:  "LoadBalancer"
  ports: 
    client: 9092
    controller: 9093
    internal: 9094
    external: 9094
  loadBalancerIP: 10.15.0.11
  annotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"

rbac:
 create: true

externalAccess:
  enabled: true 
  autoDiscovery:
    enabled: true   
  service:
    useHostIPs: true
    usePodIPs: true
    type: "LoadBalancer"
    ports: 
      external: 9094
    loadBalancerIPs: 
    - 10.15.0.15
    - 10.15.0.16
    - 10.15.0.17
    - 10.15.0.18
    annotations: 
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"

### What is the expected behavior?

Expectation is all pods in a running state:

AME          READY   STATUS    RESTARTS      AGE    IP            NODE                                NOMINATED NODE   READINESS GATES
k8s-kafka-0   1/1     Running   5 (19s ago)   4m3s   10.244.5.36   aks-nodepool2-41494409-vmss000001   <none>           <none>
k8s-kafka-1   1/1     Running   5 (19s ago)   4m3s   10.244.1.20   aks-nodepool1-40158233-vmss000001   <none>           <none>
k8s-kafka-2   1/1     Running   5 (18s ago)   4m3s   10.244.3.10   aks-nodepool1-40158233-vmss000003   <none>           <none>
k8s-kafka-3   1/1     Running   5 (19s ago)   4m3s   10.244.5.37   aks-nodepool2-41494409-vmss000001   <none>           <none>
root@jroc-redhat:~/files/AKS/kafka # 

### What do you see instead?

NAME          READY   STATUS    RESTARTS      AGE    IP            NODE                                NOMINATED NODE   READINESS GATES
k8s-kafka-0   0/1     Running   5 (19s ago)   4m3s   10.244.5.36   aks-nodepool2-41494409-vmss000001   <none>           <none>
k8s-kafka-1   0/1     Running   5 (19s ago)   4m3s   10.244.1.20   aks-nodepool1-40158233-vmss000001   <none>           <none>
k8s-kafka-2   0/1     Running   5 (18s ago)   4m3s   10.244.3.10   aks-nodepool1-40158233-vmss000003   <none>           <none>
k8s-kafka-3   0/1     Running   5 (19s ago)   4m3s   10.244.5.37   aks-nodepool2-41494409-vmss000001   <none>           <none>

### Additional information

Based on the logs seems like the DNS is not getting created on.  Please note: If I do a single deployment DNS is entry is created. 

kubectl logs -f k8s-kafka-0 -n k8s-kafka

[2023-07-14 15:39:37,375] INFO [RaftManager id=0] Election has timed out, backing off for 1000ms before becoming a candidate again (org.apache.kafka.raft.KafkaRaftClient)
[2023-07-14 15:39:37,414] INFO [MetadataLoader id=0] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader)
[2023-07-14 15:39:37,514] INFO [MetadataLoader id=0] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader)
[2023-07-14 15:39:37,614] INFO [MetadataLoader id=0] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader)
[2023-07-14 15:39:37,714] INFO [MetadataLoader id=0] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader)
[2023-07-14 15:39:37,814] INFO [MetadataLoader id=0] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader)
[2023-07-14 15:39:37,915] INFO [MetadataLoader id=0] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader)
[2023-07-14 15:39:38,015] INFO [MetadataLoader id=0] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader)
[2023-07-14 15:39:38,115] INFO [MetadataLoader id=0] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader)
[2023-07-14 15:39:38,215] INFO [MetadataLoader id=0] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader)
[2023-07-14 15:39:38,315] INFO [MetadataLoader id=0] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader)
[2023-07-14 15:39:38,375] INFO [RaftManager id=0] Re-elect as candidate after election backoff has completed (org.apache.kafka.raft.KafkaRaftClient)
[2023-07-14 15:39:38,392] INFO [RaftManager id=0] Completed transition to CandidateState(localId=0, epoch=45, retries=10, voteStates={0=GRANTED, 1=UNRECORDED, 2=UNRECORDED, 3=UNRECORDED}, highWatermark=Optional.empty, electionTimeoutMs=1259) from CandidateState(localId=0, epoch=44, retries=9, voteStates={0=GRANTED, 1=UNRECORDED, 2=UNRECORDED, 3=UNRECORDED}, highWatermark=Optional.empty, electionTimeoutMs=1769) (org.apache.kafka.raft.QuorumState)
[2023-07-14 15:39:38,392] WARN [RaftManager id=0] Error connecting to node k8s-kafka-3.k8s-kafka-headless.k8s-kafka.svc.cluster.local:9093 (id: 3 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.UnknownHostException: k8s-kafka-3.k8s-kafka-headless.k8s-kafka.svc.cluster.local
        at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:801)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
        at org.apache.kafka.clients.DefaultHostResolver.resolve(DefaultHostResolver.java:27)
        at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:110)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:510)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(ClusterConnectionStates.java:467)
        at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionStates.java:173)
        at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1030)
        at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
        at kafka.common.InterBrokerSendThread.$anonfun$sendRequests$1(InterBrokerSendThread.scala:107)
        at kafka.common.InterBrokerSendThread.$anonfun$sendRequests$1$adapted(InterBrokerSendThread.scala:103)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at kafka.common.InterBrokerSendThread.sendRequests(InterBrokerSendThread.scala:103)
        at kafka.common.InterBrokerSendThread.pollOnce(InterBrokerSendThread.scala:77)
        at kafka.common.InterBrokerSendThread.doWork(InterBrokerSendThread.scala:98)
        at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:127)
[2023-07-14 15:39:38,393] WARN [RaftManager id=0] Error connecting to node k8s-kafka-2.k8s-kafka-headless.k8s-kafka.svc.cluster.local:9093 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.UnknownHostException: k8s-kafka-2.k8s-kafka-headless.k8s-kafka.svc.cluster.local
        at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:801)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
        at org.apache.kafka.clients.DefaultHostResolver.resolve(DefaultHostResolver.java:27)
        at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:110)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:510)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(ClusterConnectionStates.java:467)
        at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionStates.java:173)
        at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1030)
        at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
        at kafka.common.InterBrokerSendThread.$anonfun$sendRequests$1(InterBrokerSendThread.scala:107)
        at kafka.common.InterBrokerSendThread.$anonfun$sendRequests$1$adapted(InterBrokerSendThread.scala:103)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at kafka.common.InterBrokerSendThread.sendRequests(InterBrokerSendThread.scala:103)
        at kafka.common.InterBrokerSendThread.pollOnce(InterBrokerSendThread.scala:77)
        at kafka.common.InterBrokerSendThread.doWork(InterBrokerSendThread.scala:98)
        at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:127)
[2023-07-14 15:39:38,393] INFO [QuorumController id=0] In the new epoch 45, the leader is (none). (org.apache.kafka.controller.QuorumController)
[2023-07-14 15:39:38,394] WARN [RaftManager id=0] Error connecting to node k8s-kafka-1.k8s-kafka-headless.k8s-kafka.svc.cluster.local:9093 (id: 1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.UnknownHostException: k8s-kafka-1.k8s-kafka-headless.k8s-kafka.svc.cluster.local
        at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:801)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
        at org.apache.kafka.clients.DefaultHostResolver.resolve(DefaultHostResolver.java:27)
        at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:110)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:510)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(ClusterConnectionStates.java:467)
        at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionStates.java:173)
        at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1030)
        at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
        at kafka.common.InterBrokerSendThread.$anonfun$sendRequests$1(InterBrokerSendThread.scala:107)
        at kafka.common.InterBrokerSendThread.$anonfun$sendRequests$1$adapted(InterBrokerSendThread.scala:103)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at kafka.common.InterBrokerSendThread.sendRequests(InterBrokerSendThread.scala:103)
        at kafka.common.InterBrokerSendThread.pollOnce(InterBrokerSendThread.scala:77)
        at kafka.common.InterBrokerSendThread.doWork(InterBrokerSendThread.scala:98)
        at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:127)
[2023-07-14 15:39:38,416] INFO [MetadataLoader id=0] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader)
[2023-07-14 15:39:38,516] INFO [MetadataLoader id=0] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader)

kubectl get pods -n k8s-kafka -o wide 
NAME          READY   STATUS    RESTARTS       AGE    IP            NODE                                NOMINATED NODE   READINESS GATES
k8s-kafka-0   0/1     Running   6 (100s ago)   6m4s   10.244.5.36   aks-nodepool2-41494409-vmss000001   <none>           <none>
k8s-kafka-1   0/1     Running   6 (100s ago)   6m4s   10.244.1.20   aks-nodepool1-40158233-vmss000001   <none>           <none>
k8s-kafka-2   0/1     Running   6 (100s ago)   6m4s   10.244.3.10   aks-nodepool1-40158233-vmss000003   <none>           <none>
k8s-kafka-3   0/1     Running   6 (100s ago)   6m4s   10.244.5.37   aks-nodepool2-41494409-vmss000001   <none>           <none>

kubectl get svc -n k8s-kafka -o wide 
NAME                   TYPE           CLUSTER-IP        EXTERNAL-IP   PORT(S)                         AGE    SELECTOR
k8s-kafka              LoadBalancer   192.168.126.74    10.15.0.11    9092:30955/TCP,9094:32259/TCP   6m8s   app.kubernetes.io/component=kafka,app.kubernetes.io/instance=k8s-kafka,app.kubernetes.io/name=kafka
k8s-kafka-0-external   LoadBalancer   192.168.126.60    10.15.0.15    9094:31476/TCP                  6m8s   app.kubernetes.io/component=kafka,app.kubernetes.io/instance=k8s-kafka,app.kubernetes.io/name=kafka,statefulset.kubernetes.io/pod-name=k8s-kafka-0
k8s-kafka-1-external   LoadBalancer   192.168.126.211   10.15.0.16    9094:32645/TCP                  6m8s   app.kubernetes.io/component=kafka,app.kubernetes.io/instance=k8s-kafka,app.kubernetes.io/name=kafka,statefulset.kubernetes.io/pod-name=k8s-kafka-1
k8s-kafka-2-external   LoadBalancer   192.168.126.4     10.15.0.17    9094:31800/TCP                  6m8s   app.kubernetes.io/component=kafka,app.kubernetes.io/instance=k8s-kafka,app.kubernetes.io/name=kafka,statefulset.kubernetes.io/pod-name=k8s-kafka-2
k8s-kafka-3-external   LoadBalancer   192.168.126.6     10.15.0.18    9094:32675/TCP                  6m8s   app.kubernetes.io/component=kafka,app.kubernetes.io/instance=k8s-kafka,app.kubernetes.io/name=kafka,statefulset.kubernetes.io/pod-name=k8s-kafka-3

kubectl exec -i --tty jrocutil /bin/bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
[root@jrocutil /]# **nslookup 10.244.5.36
** server can't find 36.5.244.10.in-addr.arpa: NXDOMAIN**

[root@jrocutil /]# nslookup 192.168.126.74
74.126.168.192.in-addr.arpa     name = k8s-kafka.k8s-kafka.svc.cluster.local.

[root@jrocutil /]# **nslookup 10.244.1.20
** server can't find 20.1.244.10.in-addr.arpa: NXDOMAIN**

[root@jrocutil /]# nslookup 192.168.126.60
60.126.168.192.in-addr.arpa     name = k8s-kafka-0-external.k8s-kafka.svc.cluster.local.

**Comment by migruiz4** [comment]
Hi @junsaw,

Your deployment is missing the `k8s-kafka-headless` service, but that service is not conditional: https://github.com/bitnami/charts/blob/main/bitnami/kafka/templates/svc-headless.yaml

I haven't been able to reproduce the issue using the values you provided. Is it possible the headless service has been manually deleted?

It would be helpful if you could share the output of the following command, so we can have a look at the manifests:
`helm install k8s-kafka oci://registry-1.docker.io/bitnamicharts/kafka -f kafka-4.yaml -n k8s-kafka --dry-run`

**Comment by migruiz4** [comment]
Hi @Nihilum and @junsaw.

I'm sorry for the inconvenience, could you please try deploying the Kafka chart using `--set service.headless.publishNotReadyAddresses=true`?

There is an issue in the current version of the `bitnami/kafka` chart when using multiple replicas.
This issue is fixed in the next major release which is currently in progress (https://github.com/bitnami/charts/pull/17507)

**Comment by hokiegeek2** [comment]
@migruiz4 thank you! I set that and now my multi-broker deployment is working

**Comment by migruiz4** [comment]
Hi there!

We have released a new major of the bitnami/kafka chart (24.x.x) which refactors the chart architecture and configuration.

In this new version of the chart, headless services are configured by default with `publishNotReadyAddresses: true`

You can find all the changes introduced in this version as well as some guidance on how to upgrade in the [Upgrading notes](https://github.com/bitnami/charts/tree/main/bitnami/kafka#to-2400)

**Comment by HectorB-2020** [comment]
> `publishNotReadyAddresses: true`

Unfortunately changing this parameter still does not help with Kafka 3.8.1 and charts 30.1.8. All Kafka pods begin restarting after a minute anyway.

**Comment by migruiz4** [comment]
@HectorB-2020 Could you please open a new issue describing your case? 
Creating a new issue instead of commenting on an old issue that is on resolved status would help us give you better support, and by filling the issue template you would help us reproduce your case more precisely.
