### ISSUE TITLE
bitnami/spark: Failed to connect to master

### ISSUE THREAD

**Issue by will-beta** [bitnami/charts#1775]
**Which chart**:

bitnami/spark

**Steps to reproduce the issue:**

1. install the spark chart
```sh
helm install r-spark bitnami/spark
```

2. port-forward the master port
```sh
kubectl port-forward --namespace default svc/r-spark-master-svc 7077:7077
```

3. submit the app
```sh
spark-submit   --class "SimpleApp" \
  --master "spark://127.0.0.1:7077" \ 
  target/scala-2.11/simple-project_2.11-1.0.jar
```
The `simple-project_2.11-1.0.jar` came from [spark Quick Start](https://spark.apache.org/docs/latest/quick-start.html#self-contained-applications)

**Describe the results you received:**

Got the following messages which indicate that `Failed to connect to master`.
```
19/12/26 15:50:24 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
19/12/26 15:50:25 INFO SparkContext: Running Spark version 2.4.4
19/12/26 15:50:25 INFO SparkContext: Submitted application: Simple Application
19/12/26 15:50:25 INFO SecurityManager: Changing view acls to: wangweiming
19/12/26 15:50:25 INFO SecurityManager: Changing modify acls to: wangweiming
19/12/26 15:50:25 INFO SecurityManager: Changing view acls groups to: 
19/12/26 15:50:25 INFO SecurityManager: Changing modify acls groups to: 
19/12/26 15:50:25 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(wangweiming); groups with view permissions: Set(); users  with modify permissions: Set(wangweiming); groups with modify permissions: Set()
19/12/26 15:50:25 INFO Utils: Successfully started service 'sparkDriver' on port 55421.
19/12/26 15:50:25 INFO SparkEnv: Registering MapOutputTracker
19/12/26 15:50:25 INFO SparkEnv: Registering BlockManagerMaster
19/12/26 15:50:25 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
19/12/26 15:50:25 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
19/12/26 15:50:25 INFO DiskBlockManager: Created local directory at /private/var/folders/16/g0s_dk6j66x_3qldj2656yq00000gn/T/blockmgr-f7f1e41d-6c93-43df-af67-ebf4e9a9658a
19/12/26 15:50:25 INFO MemoryStore: MemoryStore started with capacity 366.3 MB
19/12/26 15:50:26 INFO SparkEnv: Registering OutputCommitCoordinator
19/12/26 15:50:26 INFO Utils: Successfully started service 'SparkUI' on port 4040.
19/12/26 15:50:26 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://10.138.32.66:4040
19/12/26 15:50:26 INFO SparkContext: Added JAR file:/Users/wangweiming/tmp/scala-go/target/scala-2.11/simple-project_2.11-1.0.jar at spark://10.138.32.66:55421/jars/simple-project_2.11-1.0.jar with timestamp 1577346626523
19/12/26 15:50:26 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://127.0.0.1:7077...
19/12/26 15:50:26 INFO TransportClientFactory: Successfully created connection to /127.0.0.1:7077 after 57 ms (0 ms spent in bootstraps)
19/12/26 15:50:27 ERROR TransportResponseHandler: Still have 1 requests outstanding when connection from /127.0.0.1:7077 is closed
19/12/26 15:50:27 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master 127.0.0.1:7077
org.apache.spark.SparkException: Exception thrown in awaitResult: 
        at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:226)
        at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
        at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
        at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
        at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anonfun$tryRegisterAllMasters$1$$anon$1.run(StandaloneAppClient.scala:106)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Connection from /127.0.0.1:7077 closed
        at org.apache.spark.network.client.TransportResponseHandler.channelInactive(TransportResponseHandler.java:146)
        at org.apache.spark.network.server.TransportChannelHandler.channelInactive(TransportChannelHandler.java:108)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
        at org.apache.spark.network.util.TransportFrameDecoder.channelInactive(TransportFrameDecoder.java:182)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1354)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:917)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        ... 1 more
19/12/26 15:50:46 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://127.0.0.1:7077...
19/12/26 15:50:46 INFO TransportClientFactory: Found inactive connection to /127.0.0.1:7077, creating a new one.
19/12/26 15:50:46 INFO TransportClientFactory: Successfully created connection to /127.0.0.1:7077 after 1 ms (0 ms spent in bootstraps)
19/12/26 15:50:47 ERROR TransportResponseHandler: Still have 1 requests outstanding when connection from /127.0.0.1:7077 is closed
19/12/26 15:50:47 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master 127.0.0.1:7077
org.apache.spark.SparkException: Exception thrown in awaitResult: 
        at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:226)
        at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
        at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
        at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
        at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anonfun$tryRegisterAllMasters$1$$anon$1.run(StandaloneAppClient.scala:106)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Connection from /127.0.0.1:7077 closed
        at org.apache.spark.network.client.TransportResponseHandler.channelInactive(TransportResponseHandler.java:146)
        at org.apache.spark.network.server.TransportChannelHandler.channelInactive(TransportChannelHandler.java:108)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
        at org.apache.spark.network.util.TransportFrameDecoder.channelInactive(TransportFrameDecoder.java:182)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1354)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:917)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        ... 1 more
19/12/26 15:51:06 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://127.0.0.1:7077...
19/12/26 15:51:06 INFO TransportClientFactory: Found inactive connection to /127.0.0.1:7077, creating a new one.
19/12/26 15:51:06 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master 127.0.0.1:7077
org.apache.spark.SparkException: Exception thrown in awaitResult: 
        at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:226)
        at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
        at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
        at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
        at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anonfun$tryRegisterAllMasters$1$$anon$1.run(StandaloneAppClient.scala:106)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Failed to connect to /127.0.0.1:7077
        at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:245)
        at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:187)
        at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:198)
        at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:194)
        at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:190)
        ... 4 more
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:7077
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:323)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        ... 1 more
Caused by: java.net.ConnectException: Connection refused
        ... 11 more
19/12/26 15:51:26 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
19/12/26 15:51:26 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
19/12/26 15:51:26 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 55452.
19/12/26 15:51:26 INFO NettyBlockTransferService: Server created on 10.138.32.66:55452
19/12/26 15:51:26 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
19/12/26 15:51:26 INFO SparkUI: Stopped Spark web UI at http://10.138.32.66:4040
19/12/26 15:51:26 INFO StandaloneSchedulerBackend: Shutting down all executors
19/12/26 15:51:26 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
19/12/26 15:51:26 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
19/12/26 15:51:26 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
19/12/26 15:51:26 INFO MemoryStore: MemoryStore cleared
19/12/26 15:51:26 INFO BlockManager: BlockManager stopped
19/12/26 15:51:26 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.138.32.66, 55452, None)
19/12/26 15:51:26 INFO BlockManagerMaster: BlockManagerMaster stopped
19/12/26 15:51:26 WARN MetricsSystem: Stopping a MetricsSystem that is not running
19/12/26 15:51:26 INFO BlockManagerMasterEndpoint: Registering block manager 10.138.32.66:55452 with 366.3 MB RAM, BlockManagerId(driver, 10.138.32.66, 55452, None)
19/12/26 15:51:26 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
19/12/26 15:51:26 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.138.32.66, 55452, None)
19/12/26 15:51:26 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 10.138.32.66, 55452, None)
19/12/26 15:51:27 ERROR SparkContext: Error initializing SparkContext.
java.lang.NullPointerException
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:560)
        at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2520)
        at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:935)
        at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:926)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:926)
        at SimpleApp$.main(SimpleApp.scala:9)
        at SimpleApp.main(SimpleApp.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/12/26 15:51:27 INFO SparkContext: SparkContext already stopped.
Exception in thread "main" java.lang.NullPointerException
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:560)
        at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2520)
        at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:935)
        at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:926)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:926)
        at SimpleApp$.main(SimpleApp.scala:9)
        at SimpleApp.main(SimpleApp.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/12/26 15:51:27 INFO SparkContext: Successfully stopped SparkContext
19/12/26 15:51:27 INFO ShutdownHookManager: Shutdown hook called
19/12/26 15:51:27 INFO ShutdownHookManager: Deleting directory /private/var/folders/16/g0s_dk6j66x_3qldj2656yq00000gn/T/spark-d1ae534e-46d9-4672-91b6-2f31da2289d0
19/12/26 15:51:27 ERROR AsyncEventQueue: Listener AppStatusListener threw an exception
java.lang.NullPointerException
        at org.apache.spark.status.AppStatusListener.onApplicationEnd(AppStatusListener.scala:167)
        at org.apache.spark.scheduler.SparkListenerBus$class.doPostEvent(SparkListenerBus.scala:57)
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
        at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:91)
        at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$super$postToAll(AsyncEventQueue.scala:92)
        at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply$mcJ$sp(AsyncEventQueue.scala:92)
        at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply(AsyncEventQueue.scala:87)
        at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply(AsyncEventQueue.scala:87)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:87)
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$1$$anonfun$run$1.apply$mcV$sp(AsyncEventQueue.scala:83)
        at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1302)
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$1.run(AsyncEventQueue.scala:82)
19/12/26 15:51:27 INFO ShutdownHookManager: Deleting directory /private/var/folders/16/g0s_dk6j66x_3qldj2656yq00000gn/T/spark-b101d55f-787a-4528-b013-065a3ff47fc9
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:32Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alemorcuq** [comment]
Hi, @will-beta.

We currently have a known issue when submitting applications from outside the cluster. We have a task assigned to this, and we will update the issue when we have some news. However, I can't give you an ETA on this.

**Comment by will-beta** [comment]
@alemorcuq Thanks for the reply! Could you tell me how to submit applications from inside the cluster?

**Comment by alemorcuq** [comment]
For example, you can get your application into the master pod and then run `spark-submit` from there.

**Comment by dani8art** [comment]
Hi, I've fixed some error/missing in the NOTES.txt for this chart that could cause this issue, also we should take into account some `spark-submit` restriction.

Spark uses a concept which is called the driver and it is responsible for allocating resources and the communication in the spark cluster during the task executions. The way `spark-submit` executes this driver depends on the value of the `--deploy-mode` flags if you want to run the driver inside the cluster you should use --deploy-mode cluster and all should work correctly. If this flag is not set the driver is running locally, because of that, the connectivity is failing with the workers since the workers have not external IPs. Also, `--deploy-mode cluster` is not supported for Python in a spark standalone cluster so you can not run Python apps from outside the cluster using `spark-submit` and this chart because we are using standalone spark cluster configuration.

Regards.

**Comment by will-beta** [comment]
@dani8art ,I updated the helm repo, reinstall the spark release, port-forword the 7077 port of the `svc/r-spark-master-svc`, then submitted the app:
```sh
spark-submit   --class "SimpleApp" \
  --deploy-mode cluster
  --master "spark://127.0.0.1:7077" \
  target/scala-2.11/simple-project_2.11-1.0.jar
```

Still failed with the following messages:
```
log4j:WARN No appenders could be found for logger (org.apache.hadoop.util.NativeCodeLoader).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
20/01/08 15:30:17 INFO SecurityManager: Changing view acls to: wangweiming
20/01/08 15:30:17 INFO SecurityManager: Changing modify acls to: wangweiming
20/01/08 15:30:17 INFO SecurityManager: Changing view acls groups to: 
20/01/08 15:30:17 INFO SecurityManager: Changing modify acls groups to: 
20/01/08 15:30:17 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(wangweiming); groups with view permissions: Set(); users  with modify permissions: Set(wangweiming); groups with modify permissions: Set()
20/01/08 15:30:17 INFO Utils: Successfully started service 'driverClient' on port 56479.
20/01/08 15:30:17 INFO TransportClientFactory: Successfully created connection to /127.0.0.1:7077 after 50 ms (0 ms spent in bootstraps)
20/01/08 15:30:17 ERROR TransportResponseHandler: Still have 1 requests outstanding when connection from /127.0.0.1:7077 is closed
Exception in thread "main" org.apache.spark.SparkException: Exception thrown in awaitResult: 
        at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:226)
        at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
        at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
        at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
        at org.apache.spark.deploy.ClientApp$$anonfun$7.apply(Client.scala:243)
        at org.apache.spark.deploy.ClientApp$$anonfun$7.apply(Client.scala:243)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
        at org.apache.spark.deploy.ClientApp.start(Client.scala:243)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.io.IOException: Connection from /127.0.0.1:7077 closed
        at org.apache.spark.network.client.TransportResponseHandler.channelInactive(TransportResponseHandler.java:146)
        at org.apache.spark.network.server.TransportChannelHandler.channelInactive(TransportChannelHandler.java:108)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
        at org.apache.spark.network.util.TransportFrameDecoder.channelInactive(TransportFrameDecoder.java:182)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1354)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:917)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)
20/01/08 15:30:18 INFO ShutdownHookManager: Shutdown hook called
20/01/08 15:30:18 INFO ShutdownHookManager: Deleting directory /private/var/folders/16/g0s_dk6j66x_3qldj2656yq00000gn/T/spark-d94f00b5-58e3-4427-bdf6-3ba256fbc312
```

**Comment by dani8art** [comment]
Hi @will-beta,

`--master "spark://127.0.0.1:7077"` this IP/HOST should be accessible from outside and inside the cluster. Workers are trying to access 127.0.0.1 Are you able to use an external IP?

Regards.

**Comment by will-beta** [comment]
Hi @dani8art ,

Thanks for the reply!
Sadly, I'm not able to use an external IP.
Besides, I just tried the following way:
1. Write the `127.0.0.1    r-spark-master-svc` into */etc/hosts*.
2. Execute `kubectl port-forward --namespace default svc/r-spark-master-svc 7077:7077` 
3. Submit the app
```sh
spark-submit   --class "SimpleApp" \
  --deploy-mode cluster
  --master "spark://r-spark-master-svc:7077" \
  target/scala-2.11/simple-project_2.11-1.0.jar
```

Failed again!
```
log4j:WARN No appenders could be found for logger (org.apache.hadoop.util.NativeCodeLoader).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
20/01/08 17:26:20 INFO SecurityManager: Changing view acls to: wangweiming
20/01/08 17:26:20 INFO SecurityManager: Changing modify acls to: wangweiming
20/01/08 17:26:20 INFO SecurityManager: Changing view acls groups to: 
20/01/08 17:26:20 INFO SecurityManager: Changing modify acls groups to: 
20/01/08 17:26:20 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(wangweiming); groups with view permissions: Set(); users  with modify permissions: Set(wangweiming); groups with modify permissions: Set()
20/01/08 17:26:20 INFO Utils: Successfully started service 'driverClient' on port 58168.
20/01/08 17:26:21 INFO TransportClientFactory: Successfully created connection to r-spark-master-svc/127.0.0.1:7077 after 26 ms (0 ms spent in bootstraps)
20/01/08 17:26:22 ERROR TransportResponseHandler: Still have 1 requests outstanding when connection from r-spark-master-svc/127.0.0.1:7077 is closed
Exception in thread "main" org.apache.spark.SparkException: Exception thrown in awaitResult: 
        at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:226)
        at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
        at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
        at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
        at org.apache.spark.deploy.ClientApp$$anonfun$7.apply(Client.scala:243)
        at org.apache.spark.deploy.ClientApp$$anonfun$7.apply(Client.scala:243)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
        at org.apache.spark.deploy.ClientApp.start(Client.scala:243)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.io.IOException: Connection from r-spark-master-svc/127.0.0.1:7077 closed
        at org.apache.spark.network.client.TransportResponseHandler.channelInactive(TransportResponseHandler.java:146)
        at org.apache.spark.network.server.TransportChannelHandler.channelInactive(TransportChannelHandler.java:108)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
        at org.apache.spark.network.util.TransportFrameDecoder.channelInactive(TransportFrameDecoder.java:182)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1354)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:917)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)
20/01/08 17:26:22 INFO ShutdownHookManager: Shutdown hook called
20/01/08 17:26:22 INFO ShutdownHookManager: Deleting directory /private/var/folders/16/g0s_dk6j66x_3qldj2656yq00000gn/T/spark-cc67eec6-d88d-4f09-99b6-bc117a411d65
```

**Comment by dani8art** [comment]
Hi,

Yes, I can reproduce it, I would say that if you want to deploy spark using `ClusterIP` as a service type, due to the fact that `spark-submit` works in this way, you should submit your application from inside the cluster, you could use:

```
export WORKER=$(kubectl get pods --namespace default | awk '/r-spark-worker-0/ { print $1 }')
export MASTER_IP=$(kubectl get svc --namespace default | awk '/r-spark-master-svc/ { print $3 }')

kubectl exec -ti $WORKER -- spark-submit --master spark://$MASTER_IP:7077 \
  --class org.apache.spark.examples.SparkPi \
  examples/jars/spark-examples_2.11-2.4.4.jar 5
```

However, you can also use `NodePort` as a service type and then you will be able to submit the application from outside.

```
helm install r-spark --set service.type=NodePort --set service.nodePorts.cluster=30077 --set service.nodePorts.web=30080 bitnami/spark
```

```
export NODE_IP=$(kubectl get nodes --namespace default -o jsonpath="{.items[0].status.addresses[0].address}")

spark-submit --master spark://$NODE_IP:30077 \
    --class org.apache.spark.examples.SparkPi \
    --deploy-mode cluster \
    examples/jars/spark-examples_2.11-2.4.4.jar 1000
```

Regards.

**Comment by will-beta** [comment]
hi @dani8art ,

The way submitting the application from from inside a worker node works, though I have to upload the jar file into **every** worker nodes. Thanks very much!

But I can't figure out why `port-forward` way doesn't work and why `NodePort` way works.

Regards.

**Comment by dani8art** [comment]
Hi @will-beta,

> But I can't figure out why port-forward way doesn't work and why NodePort way works

Because when you do a `port-forward` you are making the service available in your host but workers are trying to find it on their own host and it is not available there in `127.0.0.1` you can see the log error

```
...
r-spark-master-svc/127.0.0.1:7077
...
```

However, when you use `NodePort` and give an IP, then the service is going to be always available at the same point `IP:7077` and you and the workers can reach it.

Regards.

**Comment by will-beta** [comment]
Hi @dani8art ,
> but workers are trying to find it on their own host and it is not available there in 127.0.0.1

I just executed `kubectl exec -it r-spark-worker-0 -- curl r-spark-master-svc` and got a bunch of output messages.
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/14272334/72231644-974fb900-35f7-11ea-9977-ba4433bf070b.png">
It seems like workers are able to reach the `r-spark-master-svc` through its name.

So I still couldn't figure out why. 

Regards.

**Comment by dani8art** [comment]
Hi, workers are not requesting `r-spark-master-svc`, they actually request `127.0.0.1:7077` and then it will fail. It is not a connectivity problem inside the cluster, it is a problem with the `spark-submit` script and the way it works.

Regards.

**Comment by will-beta** [comment]
Hi @dani8art ,

```sh
kubectl exec -it r-spark-worker-0 -- spark-submit   --class "SimpleApp" \
  --deploy-mode cluster \
  --master "spark://r-spark-master-svc:7077" \
  examples/jars/spark-examples_2.11-2.4.4.jar 1000
```
The command above works, so I couldn't understand why `r-spark-master-svc` got resolved to `127.0.0.1:7070` when the command was executed outside the cluster. The `spark-submit` script is confusing.

Regards.

**Comment by dani8art** [comment]
When you executed this command, `spark-submit` is executed inside the cluster on `r-spark-worker-0`.

Inside the cluster on `r-spark-worker-0`, `r-spark-master-svc` is converted into its actual IP which is `ClusterIP` of this service. From your host it is converted into `127.0.0.1` a it is wrongly used inside the cluster.

Regards.

**Comment by will-beta** [comment]
My apology!

It's me myself that got `r-spark-master-svc` resolved to `127.0.0.1` by having modified `hosts` file on my local machine.
If only workers got its own translation of the domain name `r-spark-master-svc`.

Thanks for your help!

Regards.

**Comment by dani8art** [comment]
You are welcome. 

Thank you for your feedback. 

Regards.
