### ISSUE TITLE
Kafka-init container cannot process certificates

### ISSUE THREAD

**Issue by nljakubiak** [bitnami/charts#18991]
### Name and Version

bitnami/kafka 25.1.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I got kafka installed on dev AKS cluster for testing purposes. This kafka is working with KRaft enabled and zookeeper disabled. There are 3 brokers and separated 3 controllers (in controller only mode). I got everything working as I would like to.

Next step I decided to turn on TLS/SSL on it for external endpoint. When trying to do so, I've followed README.md and updated parameters listed in below section.

### Are you using any custom parameters or values?

Those are the only parameters which I've changed after having already working kafka environment with PLAINTEXT to turn on SSL (Of course I deleted helm deployment and all existing PVC). Nginx-cert is standard tls secret with tls.crt (contains full cert chain) and tls.key.

```yaml
listeners:
  external:
    containerPort: 9095
    protocol: SASL_SSL
    name: EXTERNAL
    sslClientAuth: "required"
tls:
  type: PEM
  pemChainIncluded: true
  existingSecret: "nginx-cert"
```

### What is the expected behavior?

Kafka brokers are starting up without any issues.

### What do you see instead?

Kafka-init container is returning errors:

`cp: cannot create regular file '/certs/tls.crt': Permission denied`

I've change kafka-init script to locate all the issues and try to fix them. To do so I first added set -x to script and ls on /mountes-certs and /certs as shown below.

```sh
+ ls -l /mounted-certs/
total 0
lrwxrwxrwx 1 root root 14 Sep  3 11:17 tls.crt -> ..data/tls.crt
lrwxrwxrwx 1 root root 14 Sep  3 11:17 tls.key -> ..data/tls.key
+ ls -l /certs/
total 28
-rw-r--r-- 1 1001 root 3749 Sep  3 11:17 ca.crt                                                                                                                                                                                             -r--r----- 1 1001 root 5623 Sep  3 11:17 tls.crt
-rw-r--r-- 1 1001 root 1704 Sep  3 11:17 tls.key
-rw-r--r-- 1 1001 root 1874 Sep  3 11:17 xx00
-rw-r--r-- 1 1001 root 1826 Sep  3 11:17 xx01
-rw-r--r-- 1 1001 root 1923 Sep  3 11:17 xx02
+ rm -f /certs/kafka.keystore.jks /certs/kafka.truststore.jks
+ [[ PEM = \P\E\M ]]
+ [[ -f /mounted-certs/kafka-controller-0.crt ]]
+ [[ -f /mounted-certs/kafka.crt ]]
+ [[ -f /mounted-certs/tls.crt ]]
+ [[ -f /mounted-certs/tls.key ]]
+ cp /mounted-certs/tls.crt /certs/tls.crt
cp: cannot create regular file '/certs/tls.crt': Permission denied
```

Then trying to fix the issue I've change line that was copying file to have -f added in function configure_kafka_tls in templates/scripts-configmap.yaml.

```sh
        elif [[ -f /mounted-certs/tls.crt && -f /mounted-certs/tls.key ]]; then
          cp -f "/mounted-certs/tls.crt" /certs/tls.crt
          # Copy the PEM key ensuring the key used PEM format with PKCS#8
```

This moved forward and script started failing on next place:

```sh
+ ls -l /mounted-certs/
total 0
lrwxrwxrwx 1 root root 14 Sep  3 11:23 tls.crt -> ..data/tls.crt
lrwxrwxrwx 1 root root 14 Sep  3 11:23 tls.key -> ..data/tls.key
+ ls -l /certs/
total 28
-rw-r--r-- 1 1001 root 3749 Sep  3 11:24 ca.crt
-r--r----- 1 1001 root 5623 Sep  3 11:24 tls.crt
-rw-r--r-- 1 1001 root 1704 Sep  3 11:24 tls.key
-rw-r--r-- 1 1001 root 1874 Sep  3 11:24 xx00
-rw-r--r-- 1 1001 root 1826 Sep  3 11:24 xx01
-rw-r--r-- 1 1001 root 1923 Sep  3 11:24 xx02
+ rm -f /certs/kafka.keystore.jks /certs/kafka.truststore.jks
+ [[ PEM = \P\E\M ]]
+ [[ -f /mounted-certs/kafka-controller-0.crt ]]
+ [[ -f /mounted-certs/kafka.crt ]]
+ [[ -f /mounted-certs/tls.crt ]]
+ [[ -f /mounted-certs/tls.key ]]
+ cp -f /mounted-certs/tls.crt /certs/tls.crt
+ openssl pkcs8 -topk8 -nocrypt -in /mounted-certs/tls.key
+ cat /certs/tls.crt
+ csplit - -s -z '/\-*END CERTIFICATE\-*/+1' '{*}' -f /certs/xx
++ find /certs -not -name xx00 -name 'xx*'
+ FIND_CA_RESULT='/certs/xx01
/certs/xx02'
++ echo /certs/xx01 /certs/xx02
++ wc -l
+ [[ 1 < 1 ]]
+ echo /certs/xx01 /certs/xx02
+ sort
+ xargs cat
+ cat /certs/xx00
/scripts/kafka-init.sh: line 162: /certs/tls.crt: Permission denied
```

It seems that this time faulty line was `cat /certs/xx00 > /certs/tls.crt` so I've changed it to `cp -f /certs/xx00 /certs/tls.crt` in section:

```sh
        echo $FIND_CA_RESULT | sort | xargs cat >> /certs/ca.crt
        cp -f /certs/xx00 /certs/tls.crt
        find /certs -name "xx*" -exec rm {} \;
```

### Additional information

My changes in script seemed to fix the problem for me. Could you elaborate if this is a bug in the scripts-config, or some miss configuration i.e. with pod/containerSecurityPolicies?

**Comment by nljakubiak** [comment]
Yes, in the end, I deleted that line completely (`cat /certs/xx00 > /certs/tls.crt`). Still for me first modification was required otherwise I had a problem with not being able to copy certificate in section below.

```sh
        elif [[ -f /mounted-certs/tls.crt && -f /mounted-certs/tls.key ]]; then
# From:
          cp "/mounted-certs/tls.crt" /certs/tls.crt
# To
          cp -f "/mounted-certs/tls.crt" /certs/tls.crt
```

I'm starting to think that first run of kafka-init was breaking on certificate containing only end certificate, and all next restarts of kafka-init container, were creating problem with overwriting tls.crt file since script didn't finish and didn't remove it from emptyDir mount.

**Comment by migruiz4** [comment]
Hi there!

If I'm not mistaken, the problem I see is that any issue in the initialization may cause files `tls.crt/tls.key/ca.crt` to remain in the emptyDir, causing the initialization process to stuck.

I have implemented these changes to ensure the `/certs` folder does not include any file from previous executions that could cause this issue: #19427 

@jvstein @nljakubiak Could you please give it a try and let me know if it solves your issue?

**Comment by nljakubiak** [comment]
Hello,
I've just tried it and it still failes with those changes. I've added ls -l /certs in 2 places and set -x to show a bit more info like previously. Adding rm -f on /certs/tls.crt solved the problem with next containers restarts, as tls.crt ets removed. But later in the scripts you still try to copy over that file on cat section. To be honest, it seems like a broken loophole where

1. you have full tls certificate (cert + CA) and key. You copy cert (and CA) from "/mounted-certs/tls.crt" to "/certs/tls.crt"
2. you create all certificates as xx*
3. You try to overwrite just certificate as tls.crt (is that overwrite even necessary?)

```sh
        echo $FIND_CA_RESULT | sort | xargs cat >> /certs/ca.crt
        cat /certs/xx00 > /certs/tls.crt
        find /certs -name "xx*" -exec rm {} \;
```

First container creation:

```sh
+ ls -l /certs
total 0
+ rm -f /certs/kafka.keystore.jks /certs/kafka.truststore.jks
+ rm -f /certs/tls.crt /certs/tls.key /certs/ca.crt
+ [[ PEM = \P\E\M ]]
+ [[ -f /mounted-certs/kafka-broker-0.crt ]]
+ [[ -f /mounted-certs/kafka.crt ]]
+ [[ -f /mounted-certs/tls.crt ]]
+ [[ -f /mounted-certs/tls.key ]]
+ ls -l /certs
total 0
+ cp /mounted-certs/tls.crt /certs/tls.crt
+ openssl pkcs8 -topk8 -nocrypt -in /mounted-certs/tls.key
+ cat /certs/tls.crt
+ csplit - -s -z '/\-*END CERTIFICATE\-*/+1' '{*}' -f /certs/xx
++ find /certs -not -name xx00 -name 'xx*'
+ FIND_CA_RESULT='/certs/xx01
/certs/xx02'
++ echo /certs/xx01 /certs/xx02
++ wc -l
+ [[ 1 < 1 ]]
+ echo /certs/xx01 /certs/xx02
+ sort
+ xargs cat
+ cat /certs/xx00
/scripts/kafka-init.sh: line 165: /certs/tls.crt: Permission denied
```

So let's assume step 3 is necessary and I change

```sh
cat /certs/xx00 > /certs/tls.crt
# to
cp -f /certs/xx00 /certs/tls.crt
```

Then it's able to start. But when you try to connect to kafka you get:

```txt
[2023-09-21 14:33:23,402] ERROR org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

This is because exposed certificate is without CA. Which means you shouldn't overwrite /certs/tls.crt which is then exposed by kafka for SSL. It works just fine when you comment out:

```sh
cat /certs/xx00 > /certs/tls.crt

# In this section
        echo $FIND_CA_RESULT | sort | xargs cat >> /certs/ca.crt
        # cat /certs/xx00 > /certs/tls.crt
        find /certs -name "xx*" -exec rm {} \;
```

**Comment by migruiz4** [comment]
Hi @nljakubiak,

I'm sorry for the late response.

The `xx*` logic is prior to the chart logic refactor (and PEM to JKS transformation) and I think it can now be entirely omitted.

This way, the keystore will contain private key + CA + public certs. And the truststore will contain CA + public certs.

```
        {{- if not .Values.tls.pemChainIncluded }}
        # Copy CA certificate
        if [[ -f /mounted-certs/kafka-ca.crt ]]; then
          cp /mounted-certs/kafka-ca.crt /certs/ca.crt
        elif [[ -f /mounted-certs/ca.crt ]]; then
          cp /mounted-certs/ca.crt /certs/ca.crt
        else
          error "CA certificate file not found"
        fi
        {{- else }}
        # CA certificates are also included in the same certificate
        # All public certs will be included in the truststore
        cp /certs/tls.crt /certs/ca.crt
        {{- end }}
```

I have updated the PR, could you please give it a try again?

**Comment by josmo** [comment]
@migruiz4 fyi the current updated https://github.com/bitnami/charts/pull/19427 fixes my issue that matches whats going on here
