### ISSUE TITLE
[mongodb] resources in yaml under-indented

### ISSUE THREAD

**Issue by lwj5** [bitnami/charts#2137]
**Which chart**:
mongodb 7.10.2

**Describe the bug**
All resources values in templates/deployment-standalone.yaml are under indented.
For example {{ toYaml .Values.resources | indent 10 }} (should be 12)

Other "resources:" in the same file are affected as well.
Other yaml files might be affected.

**To Reproduce**
1. Install with helm 3, set resources.limits.cpu=1
2. See yaml output (no resources set)

resources set with limit.cpu=1

**Version of Helm and Kubernetes**:
- Output of `helm version`:
```
3
```

- Output of `kubectl version`:
```
1.17
```

**Additional context**

**Comment by miguelaeh** [comment]
Hi @lwj5 ,
Thank you for reporting the issue, it should be fixed with the following PR, it was merged yesterday: https://github.com/bitnami/charts/pull/2139

**Comment by lwj5** [comment]
Hi @miguelaeh, it's still not fixed {{ toYaml .Values.resources | indent 10 }} should be 12

**Comment by lwj5** [comment]
Added PR
