### ISSUE TITLE
[bitnami/clickhouse] Clickhouse Pod DNS Resolution Issue

### ISSUE THREAD

**Issue by nevotheless** [bitnami/charts#23017]
### Name and Version

bitnami/clickhouse 4.5.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

This is a pretty standard EKS Cluster

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: some-cluster
  region: eu-central-1

managedNodeGroups:
  - name: compute-group-1
    instanceType: c6a.2xlarge
    desiredCapacity: 2
    privateNetworking: true
    amiFamily: AmazonLinux2
    volumeSize: 100
    volumeType: gp3
    securityGroups:
      attachIDs:
        - sg-asdf12345
    availabilityZones:
      - eu-central-1a
      - eu-central-1b
      - eu-central-1c
    iam:
      withAddonPolicies:
        ebs: true
        efs: true
    tags:
      nodegroup-type: worker
      nodegroup-environment: testing

vpc:
  id: vpc-asdf1234
  clusterEndpoints:
    privateAccess: true
    publicAccess: false
  securityGroup: sg-0asdf1234
  subnets:
    private:
      pone:
        id: subnet-asdfa
      ptwo:
        id: subnet-asdfb
      pthree:
        id: subnet-asdf

iam:
  withOIDC: true
  # The Service Account Setup creates the IAM Roles for the Service Accounts
  serviceAccounts:
    - metadata:
        name: efs-csi-controller-sa
        namespace: kube-system
      wellKnownPolicies:
        efsCSIController: true
    - metadata:
        name: ebs-csi-controller-sa
        namespace: kube-system
      wellKnownPolicies:
        ebsCSIController: true

  - account: "someAccount" # AWS Account ID without additional Keys is needed here according to the eksctl docs

addons:
  - name: aws-efs-csi-driver
  - name: aws-ebs-csi-driver
 ```

Additionally `aws-loadbalancer-controller` and `ingress-nginx` are installed as well.

I deployed the bitnami clickhouse chart with the parameters below. Without much change but the clickhouse pods aren't able to resolve the hostnames.

### Are you using any custom parameters or values?

The values file didn't get touched much. 

 ```yaml
 auth:
    username: default
    password: ""
    existingSecret: "clickhouse-admin-creds"
    existingSecretKey: "password"
```

```yaml
ingress:
    enabled: true
    hostname: somehostname.our.company.intern
    ingressClassName: "nginx"
    tls: true
    extraTls: 
      - hosts:
          - somehostname.our.company.intern
        secretName: some-tls-secret
```

```yaml
storageClass: "some-gp3-storageClass"
```

### What is the expected behavior?

Clickhouse being able to resolve the hostnames of the shard pods.

### What do you see instead?

```
2024.01.29 14:11:42.900433 [ 78 ] {} <Warning> DNSResolver: Cannot resolve host (clickhouse-shard0-0.clickhouse-headless.apps.svc.cluster.local), error 0: Host not found.
2024.01.29 14:11:42.901533 [ 78 ] {} <Warning> DNSResolver: Cannot resolve host (clickhouse-shard0-2.clickhouse-headless.apps.svc.cluster.local), error 0: Host not found.
2024.01.29 14:11:42.902724 [ 78 ] {} <Warning> DNSResolver: Cannot resolve host (clickhouse-shard1-0.clickhouse-headless.apps.svc.cluster.local), error 0: Host not found.
2024.01.29 14:11:42.903902 [ 78 ] {} <Warning> DNSResolver: Cannot resolve host (clickhouse-shard1-2.clickhouse-headless.apps.svc.cluster.local), error 0: Host not found.
2024.01.29 14:11:42.903970 [ 78 ] {} <Information> DNSResolver: Cached hosts not found: clickhouse-shard0-0.clickhouse-headless.apps.svc.cluster.local, clickhouse-shard0-2.clickhouse-headless.apps.svc.cluster.local, clickhouse-shard1-0.clickhouse-headless.apps.svc.cluster.local, clickhouse-shard1-2.clickhouse-headless.apps.svc.cluster.local

```

### Additional information

Debugging this is quite hard, since i can't install anything into the containers but i tried the best i can.

Pods have the proper kubernetes dns entry in `/etc/resolv.conf`

```
I have no name!@clickhouse-shard0-0:/$ cat /etc/resolv.conf 
search apps.svc.cluster.local svc.cluster.local cluster.local eu-central-1.compute.internal
nameserver 10.100.0.10
options ndots:5
```

Other pods in the same namespace can resolve the headless service and the pods specifically just fine.

```
/ # dig +short clickhouse-headless.apps.svc.cluster.local
172.30.12.160
172.30.11.133
172.30.11.213
172.30.11.111
172.30.12.148
172.30.12.44
/ # dig +short clickhouse-shard0-2.clickhouse-headless.apps.svc.cluster.local
172.30.12.160
```

I suspect that the pod networking works as expected and the clickhouse pods themselves would resolve everything fine but that clickhouse maybe doing some internal dns resolving? Just assuming here, i have no clue.

**Comment by javsalgar** [comment]
Hi,

Just to confirm, could you try deploying with `networkPolicy.enabled=false`?

**Comment by javsalgar** [comment]
If that's the case, then after merging this it should work https://github.com/bitnami/charts/pull/23031

**Comment by nevotheless** [comment]
I set `networkPolicy.enabled=false` but unfortunately i still see those issues.

**Comment by javsalgar** [comment]
In principle, it seems that there may be something incorrect in the Kubernetes cluster, but this is strange as other nodes are able to resolve. My advice would be to install the chart with `runAsUser:0` and `runAsNonRoot: false`, there you can install extra debugging software and maybe discover anything extra.

**Comment by nevotheless** [comment]
Will do and investigate further. Thanks.

**Comment by nevotheless** [comment]
```
clickhouse 09:20:19.15 INFO  ==>
clickhouse 09:20:19.15 INFO  ==> Welcome to the Bitnami clickhouse container
clickhouse 09:20:19.15 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
clickhouse 09:20:19.15 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
clickhouse 09:20:19.15 INFO  ==>
clickhouse 09:20:19.15 INFO  ==> ** Starting ClickHouse setup **
clickhouse 09:20:19.17 INFO  ==> Copying mounted configuration from /bitnami/clickhouse/etc
cp: -r not specified; omitting directory '/bitnami/clickhouse/etc/conf.d/default/..data'
clickhouse 09:20:19.19 INFO  ==> ** ClickHouse setup finished! **
clickhouse 09:20:19.19 INFO  ==> ** Starting ClickHouse **
chroot: cannot change root directory to '/': Operation not permitted
```

Is what i got when trying to change 
```
runAsUser:0
runAsNonRoot: false
```

This crashed the container unfortunately and doesn't quite help with troubleshooting 😄

**Comment by Kareem-Afaneh** [comment]
Hi @nevotheless 

I have deployed it with **chart version: clickhouse-4.5.4** and **app version: 23.12.3**. Once i deploy it, i receive the same warnings, but after some time they stop.  

Did you find anything about this issue? 

Thanks in advance.

**Comment by gcosta-lively** [comment]
How did you fix this @nevotheless ? I'm experiencing the exact same issue

**Comment by nevotheless** [comment]
No i didnt fix this, but i didnt look much more into it after posting the issue here. What i did is disabling sharding / clustering all together, which defeats the purpose of the deployment but works for small/dev purposes i guess.
