### ISSUE TITLE
bitnami/postgresql: CrashLoopBackOff when trying to start the pod

### ISSUE THREAD

**Issue by jouvin** [bitnami/charts#24050]
### Name and Version

bitnami/postgresql 14.2.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Kubernetes 1.21 cluster (instantiated through OpenStack Magnum Wallaby version)
2. A storage class defined to provision storage from OpenStack Cinder (storage service)
3. Run `helm install postgres bitnami/postgresql -f values-postgres-test.yaml`
4. Pod is going to status CrashLoopBackOff 

### Are you using any custom parameters or values?

* values-postgres-test.yaml: 
 
    ```yaml
    image:
        debug: true
    ```

### What is the expected behavior?

I expect the pod to run successfully! I don't understand why it worked the first time I did it. After some time, I decided to delete the cluster and create a new one with the same parameters (as far as I can tell/remember) and since then it has been failing every time I tried to do it, recreating a new cluster a large number of times.

I got this error `Cannot allocate memory` after adding `image: debug: true` in the YAML file. Else there was absolutely no error message anywhere... Maybe this kind of error should be logged even if `debug: false`... But it doesn't give me much information about the reason for the problem and I don't understand if the `initdb` error after this first error is the cause of the problem (but I did nothing to the container as the logs show) or the consequence...

Help would be very much appreciated. I have been completely stuck with this problem for a week... It is not related to recent changes because my first attempt was with chart version 13.4.4 and an attempt to force the use of this version resulted in the same problem.

### What do you see instead?

1. Running `kubectl describe pod pod/postgres-postgresql-0`:

    ```
    Events:
        Type     Reason                  Age                     From                     Message
        ----     ------                  ----                    ----                     -------
        Normal   Scheduled               4m44s                   default-scheduler        Successfully assigned rucio/postgres-postgresql-0 to mesonet-k8s-preprod-m3-psp-w-w3crcmov6llv-node-2
        Normal   SuccessfulAttachVolume  4m42s                   attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-df379d4a-b8f6-4395-a302-feaa144ccd7e"
        Normal   Pulled                  3m48s (x4 over 4m39s)   kubelet                  Container image "docker.io/bitnami/postgresql:16.2.0-debian-12-r5" already present on machine
        Normal   Created                 3m47s (x4 over 4m38s)   kubelet                  Created container postgresql
        Normal   Started                 3m47s (x4 over 4m38s)   kubelet                  Started container postgresql
        Warning  BackOff                 3m20s (x13 over 4m35s)  kubelet                  Back-off restarting failed container
    ```
2. Running `kubectl logs pod/postgres-postgresql-0`:

   ```
    postgresql 20:41:59.02 INFO  ==>
    postgresql 20:41:59.02 INFO  ==> Welcome to the Bitnami postgresql container
    postgresql 20:41:59.02 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
    postgresql 20:41:59.02 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
    postgresql 20:41:59.02 INFO  ==>
    postgresql 20:41:59.02 DEBUG ==> Configuring libnss_wrapper...
    postgresql 20:41:59.03 DEBUG ==> Copying files from /opt/bitnami/postgresql/conf.default to /opt/bitnami/postgresql/conf
    postgresql 20:41:59.03 INFO  ==> ** Starting PostgreSQL setup **
    postgresql 20:41:59.05 INFO  ==> Validating settings in POSTGRESQL_* env vars..
    postgresql 20:41:59.05 INFO  ==> Loading custom pre-init scripts...
    postgresql 20:41:59.06 INFO  ==> Initializing PostgreSQL database...
    postgresql 20:41:59.06 DEBUG ==> Ensuring expected directories/files exist...
    postgresql 20:41:59.07 INFO  ==> pg_hba.conf file not detected. Generating it...
    postgresql 20:41:59.07 INFO  ==> Generating local authentication configuration
    popen failure: Cannot allocate memory
    initdb: error: program "postgres" is needed by initdb but was not found in the same directory as "/opt/bitnami/postgresql/bin/initdb"
   ```

### Additional information

```console
$ kubectl top node
NAME                                                 CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
mesonet-k8s-preprod-m3-psp-w-w3crcmov6llv-master-0   173m         8%     1617Mi          43%
mesonet-k8s-preprod-m3-psp-w-w3crcmov6llv-master-1   135m         6%     1697Mi          45%
mesonet-k8s-preprod-m3-psp-w-w3crcmov6llv-master-2   123m         6%     1618Mi          43%
mesonet-k8s-preprod-m3-psp-w-w3crcmov6llv-node-1     58m          1%     777Mi           10%
mesonet-k8s-preprod-m3-psp-w-w3crcmov6llv-node-2     89m          2%     799Mi           10%
```

**Comment by jouvin** [comment]
Problem fixed after upgrading the Kubernetes cluster to 1.23. It doesn't explain why it worked once in 1.21 and never worked again after that... but I close the issue as I don't think it is worth spending time on it...

**Comment by philm5** [comment]
Ok, this is really strange. I am experiencing the same issue and was hoping for a solution. My version is: `Server Version: v1.23.17`.

**Comment by FraPazGal** [comment]
Hello @jouvin, I'm glad the issue got fixed with the cluster upgrade. As per our [documentation](https://github.com/bitnami/charts?tab=readme-ov-file#prerequisites), our charts require `k8s@1.23+` so you should be fine using your updated cluster.

@philm5 Could you confirm you are getting the same reported error with our latest `bitnami/postgresql` chart release:
```
popen failure: Cannot allocate memory
initdb: error: program "postgres" is needed by initdb but was not found in the same directory as "/opt/bitnami/postgresql/bin/initdb"
```

Additionally, please share if you are using any custom parameters as well as relevant info regarding your cluster config (cluster provider, storage class, etc). This will help us reproduce the error and get to the root issue faster.

**Comment by jouvin** [comment]
I'm running K8s 1.23.16 but I would be surprise it makes a difference... Clearly, after the 1.21 -> 1.23 upgrade, I don't see the problem (I already did it a lot of times today).

**Comment by jouvin** [comment]
Hi,

Unfortunately the same problem is back. Same error as before with the same configuration, except the K8s cluster used is a 1.24 cluster instead of 1.23. The error happens whether I use the version that was successfully running before (14.2.4) or the last one available.

As far as I can say, other workloads run fine in this cluster... The sidecars don't seem to have errors. I increased the minion memory from 8 GB to 16 but it doesn't help.

Any suggestion on how to identify the actual issue (probably in the underlying infrastructure)....

Michel
