### ISSUE TITLE
FATAL:  database "repmgr" does not exist

### ISSUE THREAD

**Issue by xRTRx** [bitnami/charts#25671]
### Name and Version

bitnami/postgresql-ha:14.0.10

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Kubernetes version: v1.28.6
Helm: v3.13.1

### Are you using any custom parameters or values?
```
--set global.postgresql.username=user1 \
--set global.postgresql.database=db1 \
--set postgresql.audit.logConnections=true \
--set postgresql.audit.logDisconnections=true \
--set pgpool.logConnections=true \
--set pgpool.logPerNodeStatement=true \
--set witness.create=true \
--set witness.audit.logConnections=true \
--set witness.audit.logDisconnections=true \
--set metrics.enabled=true \
--set metrics.serviceMonitor.enabled=true \
--set persistence.enabled=false
```
### What do you see instead?
```
postgresql-repmgr 11:03:31.32 INFO  ==> 
postgresql-repmgr 11:03:31.33 INFO  ==> Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 11:03:31.33 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql-repmgr 11:03:31.33 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
postgresql-repmgr 11:03:31.34 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
postgresql-repmgr 11:03:31.34 INFO  ==> 
postgresql-repmgr 11:03:31.43 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 11:03:31.54 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 11:03:31.55 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 11:03:31.56 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 11:03:31.82 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgresql-repmgr 11:03:31.84 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 11:03:31.84 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 11:03:32.25 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 11:03:32.34 INFO  ==> Initializing Repmgr...
postgresql-repmgr 11:03:32.34 INFO  ==> Initializing PostgreSQL database...
postgresql-repmgr 11:03:32.35 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql-repmgr 11:03:32.42 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgresql-repmgr 11:03:32.52 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql-repmgr 11:03:32.63 INFO  ==> Configuring replication parameters
postgresql-repmgr 11:03:32.75 INFO  ==> Configuring fsync

postgresql-repmgr 11:03:32.83 INFO  ==> ** PostgreSQL with Replication Manager setup finished! **
postgresql-repmgr 11:03:32.94 INFO  ==> Starting PostgreSQL in background...
waiting for server to start....2024-05-10 11:03:33.062 GMT [153] LOG:  pgaudit extension initialized
2024-05-10 11:03:33.128 GMT [153] LOG:  redirecting log output to logging collector process
2024-05-10 11:03:33.128 GMT [153] HINT:  Future log output will appear in directory "/opt/bitnami/postgresql/logs".
2024-05-10 11:03:33.128 GMT [153] LOG:  starting PostgreSQL 16.2 on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-05-10 11:03:33.129 GMT [153] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-05-10 11:03:33.129 GMT [153] LOG:  listening on IPv6 address "::", port 5432
2024-05-10 11:03:33.141 GMT [153] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2024-05-10 11:03:33.160 GMT [157] LOG:  database system was shut down at 2024-05-10 11:03:30 GMT
2024-05-10 11:03:33.172 GMT [153] LOG:  database system is ready to accept connections
 done
server started
2024-05-10 11:03:33.243 GMT [163] LOG:  connection received: host=[local]
postgresql-repmgr 11:03:33.24 INFO  ==> ** Starting repmgrd **
[2024-05-10 11:03:33] [NOTICE] repmgrd (repmgrd 5.4.1) starting up
2024-05-10 11:03:33.264 GMT [166] LOG:  connection received: host=postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.default.svc.cluster.local port=32870
2024-05-10 11:03:33.340 GMT [166] LOG:  connection authenticated: identity="repmgr" method=md5 (/opt/bitnami/postgresql/conf/pg_hba.conf:1)
2024-05-10 11:03:33.340 GMT [166] LOG:  connection authorized: user=repmgr database=repmgr application_name=repmgr
2024-05-10 11:03:33.340 GMT [166] FATAL:  database "repmgr" does not exist
[2024-05-10 11:03:33] [ERROR] connection to database failed
[2024-05-10 11:03:33] [DETAIL] 
connection to server at "postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.default.svc.cluster.local" (10.233.96.193), port 5432 failed: FATAL:  database "repmgr" does not exist

[2024-05-10 11:03:33] [DETAIL] attempted to connect using:
  user=repmgr password=Iqo2VU54uk connect_timeout=5 dbname=repmgr host=postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.default.svc.cluster.local port=5432 fallback_application_name=repmgr options=-csearch_path=
```
### Additional information

If I remove these parameters everything starts working
- global.postgresql.username=user1
- global.postgresql.database=db1

**Comment by carrodher** [comment]
The issue may not be directly related to the Bitnami container image or Helm chart, but rather to how the application is being utilized or configured in your specific environment.

Having said that, if you think that's not the case and are interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

If you have any questions about the application itself, customizing its content, or questions about technology and infrastructure usage, we highly recommend that you refer to the forums and user guides provided by the project responsible for the application or technology.

With that said, we'll keep this ticket open until the stale bot automatically closes it, in case someone from the community contributes valuable insights.

**Comment by 8ball030** [comment]
I additionally experienced this
Would love to knwo what i am doing wrong

**Comment by AminMkh** [comment]
yep, same problem here:
chart version: 
postgresql-ha:14.1.2

if i pass custom credentials, it doesn't work, if I leave empty, it works.

```
  postgresql:
    username: someusername
    password: somepassword

    repmgrUsername: someusername2
    repmgrPassword: somepassword2
  pgpool:
    adminUsername: somepassword3
    adminPassword: somepassword3
```

**Comment by rafariossaa** [comment]
I was able to reproduce the issue. I am trying to identify the cause and provide a fix.

**Comment by rafariossaa** [comment]
Could you give the new version a try ?

**Comment by lpmhouben** [comment]
I'm currently running into the same issue -- having a custom database, username and password in the values breaks repmgr. Is there any word on progress approving the PR?

**Comment by harveyjing** [comment]
Chart postgresql-ha-15.1.0. When assign a custom user like blow, it's throw `database "repmgr" does not exist `.
```
postgresql:
  username: "user1"
  password: "123456"
```

**Comment by kgaurav29** [comment]
Is there any update on this ?, I am facing same issue with Chart Version - 15.1.2

**Comment by avanschie** [comment]
@rafariossaa I'm still facing this issue with chart version 15.3.3

**Comment by gongomgra** [comment]
Hi all,

I have been able to reproduce this issue with [the custom values provided](https://github.com/bitnami/charts/issues/25671#issuecomment-2537808315) and the most recent version of our chart. I will create an internal task to work on this. I'm adding the on-hold tag to avoid the stale bot to close this issue.

**Comment by MuhammedAbduRafi** [comment]
## Root cause & fix

The **`bitnami/postgresql‑ha`** chart needs the built‑in super‑user `postgres` to bootstrap `repmgr`.  
If you change

```yaml
postgresql.username: <anything‑but‑postgres>
```

but **forget to set**

```yaml
postgresql.postgresPassword: <some‑password>
```

the bootstrap SQL that creates the `repmgr` role fails, and every pod then crashes with:

```
FATAL:  role "repmgr" does not exist
```

### Reproduce

1. Deploy the chart with a custom `postgresql.username` and *no* `postgresql.postgresPassword`.  
2. Pod log shows `role "repmgr" does not exist` (confirmed in issues #8438, #26436, #4986).

### Fix

Add the missing key (can match `repmgrPassword` or be unique):

```yaml
postgresql:
  username: pg_root
  password: PgRootPwd!23
  postgresPassword: SuperPwd!      # <- **required**
  repmgrPassword: SuperPwd!        # <- internal HA user
```

With `postgresql.postgresPassword` present, the chart’s init scripts succeed and the pod stays **Running**.

### References

* Chart README:  
  > “`postgresql.postgresPassword` – PostgreSQL password for the `postgres` user **when `username` is not `postgres`**.” 
* Default `values.yaml` shows the same note and empty default.

Hope this helps anyone who hits the *“role repmgr does not exist”* loop!

**Comment by gongomgra** [comment]
Hi all,

We have just released the PostgreSQL HA Chart version `15.3.13` addressing this issue. Can you confirm it works now with the provided structure for your custom values so we can close this as solved?

**Comment by Stevenpc3** [comment]
I am still having a similar issue with 15.3.15

I actually did not realize it was the passwords that were the issue.  I noticed the problem happened with the update to the images to -r2 https://github.com/bitnami/containers/commit/cfe50241bcb0408a9a64deb8152dbed262347703 which also happened in 16 version of the images.  I had to stay on "16.6.0-debian-12-r1" and hoped that moving to the version 17 of the images would fix the issue, but it did not.

Seeing this post I removed the custom db name and pass and it worked when set to below where they are commented out.  With them uncommented it breaks with the same error only on the primary instance.

```
postgresql:
      image:
        tag: 17.2.0-debian-12-r2
      #database: test
      #username: test
```

images '17.2.0-debian-12-r1' and '17.2.0-debian-12-r0' do not have this issue.

**Comment by Stevenpc3** [comment]
in the chart update to 15.3.15 there was a change from the env var of ```PGPASSFILE``` to ```PGPASSWORD_FILE```

![Image](https://github.com/user-attachments/assets/c57c7ca6-f4cc-4ba6-bdb6-ffbe1a49fdee)

which the variable does not exist https://github.com/search?q=repo%3Abitnami%2Fcontainers%20PGPASSWORD_FILE&type=code and only the old one does https://github.com/search?q=repo%3Abitnami%2Fcontainers+PGPASSFILE&type=code in the container image. 

So I think this variable change broke that part of the chart.

**Comment by gongomgra** [comment]
Hi all,

Thanks for reporting these errors. @fmulero as you released chart version 15.3.15, would you mind taking a look into this?

**Comment by fmulero** [comment]
About `PGPASSWORD_FILE`, you can see the variable here: https://github.com/bitnami/charts/blob/261a2519c584fb942b26ab2dbf5fd230607a9483/bitnami/postgresql-ha/values.yaml#L2210

And more details about that change in the PR https://github.com/bitnami/charts/pull/33145

@Stevenpc3 Could you share concrete steps to reproduce your issue and/or file a new issue? We have made several changes about the password generation and password files lately and this issue is becoming a monster difficult to solve.

**Comment by Stevenpc3** [comment]
@fmulero I will retract the comments about the changes related to 5.3.15 as they might be fine and I have no issue as I don't use the backup provided.  I just seemed to think this was an issue while digging into this issue of repmgr db not existing.

@gongomgra I am MUCH more concerned about the current issue which does not appear solved.  I have laid out what I think is easy to reproduce steps here that point to the container version being the issue.  You can simple deploy with the database and username set as laid out using any chart version with image prior to those ending in ```-r2``` such as ```-r0``` or ```-r1``` and it will work, but > -r2 will break.

**Comment by Stevenpc3** [comment]
This a related issue that describe the same problem.  https://github.com/bitnami/charts/issues/25576

**Comment by Stevenpc3** [comment]
Ok.  Sorry for the imformation overload, but I assume more data is better than less.

I systematically deployed chart 15.3.15 with the values.yaml settings in the above comment and between each helm delete I deleted the pvc to ensure clean deploys and only updated the tag to change the container version.  Then I compared and noted the failures.  Here is the list where 'SAME' means the fail was the same as the last one.

- 17.2.0-debian-12-r0 - works
- 17.2.0-debian-12-r1 - works
- 17.2.0-debian-12-r2 - FATAL:  database "repmgr" does not exist
- 17.2.0-debian-12-r3 - SAME
- 17.2.0-debian-12-r4 - SAME
- 17.2.0-debian-12-r5 - SAME
- 17.2.0-debian-12-r6 - SAME
- 17.2.0-debian-12-r7 - SAME
- 17.2.0-debian-12-r8 - SAME
- 17.2.0-debian-12-r9 - FATAL:  password authentication failed for user "repmgr"
								< 2025-05-06 15:51:19.832 UTC [unknown] repmgr repmgr 178 681a2ff7.b2 2025-05-06 15:51:19 UTC 10.42.0.92(37414) >DETAIL:  Role "repmgr" does not exist.
										Connection matched file "/opt/bitnami/postgresql/conf/pg_hba.conf" line 9: "hostnossl    all             all             all                     md5"
								[2025-05-06 15:51:19] [ERROR] connection to database failed
								[2025-05-06 15:51:19] [DETAIL] connection to server at "infrastructure-postgresql-ha-postgresql-0.infrastructure-postgresql-ha-postgresql-headless.default.svc.cluster.local" (10.42.0.92), port 5432 failed: FATAL:  password authentication failed for user "repmgr"
									password retrieved from file "/opt/bitnami/repmgr/conf/.pgpass"
								[2025-05-06 15:51:19] [DETAIL] attempted to connect using:
									user=repmgr passfile=/opt/bitnami/repmgr/conf/.pgpass connect_timeout=5 dbname=repmgr host=infrastructure-postgresql-ha-postgresql-0.infrastructure-postgresql-ha-postgresql-headless.default.svc.cluster.local port=5432 fallback_application_name=repmgr options=-csearch_path=

- 17.3.0-debian-12-r0 - SAME
- 17.3.0-debian-12-r1 - SAME
- 17.3.0-debian-12-r2 - SAME
- 17.3.0-debian-12-r3 - SAME
- 17.3.0-debian-12-r4 - SAME
- 17.4.0-debian-12-r0 - SAME
- 17.4.0-debian-12-r1 - SAME
- 17.4.0-debian-12-r2 - SAME
- 17.4.0-debian-12-r3 - SAME
- 17.4.0-debian-12-r4 - SAME
- 17.4.0-debian-12-r5 - SAME
- 17.4.0-debian-12-r6 - SAME
- 17.4.0-debian-12-r7 - SAME
- 17.4.0-debian-12-r8 - SAME
- 17.4.0-debian-12-r9 - SAME
- 17.4.0-debian-12-r10 - SAME
- 17.4.0-debian-12-r11 - SAME
- 17.4.0-debian-12-r12 - SAME
- 17.4.0-debian-12-r13 - SAME
- 17.4.0-debian-12-r14 - SAME
- 17.4.0-debian-12-r15 - SAME
- 17.4.0-debian-12-r16 - SAME


Here is the order of logs.  The primary pod will come up with a set of logs then RESTART with a second set of logs.


*******************FIRST ********************
postgresql-repmgr 15:59:22.81 INFO  ==>
postgresql-repmgr 15:59:22.82 INFO  ==> Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 15:59:22.82 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql-repmgr 15:59:22.82 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
postgresql-repmgr 15:59:22.82 INFO  ==>
postgresql-repmgr 15:59:22.84 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 15:59:22.87 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 15:59:22.88 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 15:59:22.89 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 15:59:23.03 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgresql-repmgr 15:59:23.04 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 15:59:23.04 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 15:59:23.16 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 15:59:23.17 INFO  ==> Initializing Repmgr...
postgresql-repmgr 15:59:23.18 INFO  ==> Initializing PostgreSQL database...
postgresql-repmgr 15:59:23.20 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql-repmgr 15:59:23.21 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql-repmgr 15:59:23.21 INFO  ==> Generating local authentication configuration
postgresql-repmgr 15:59:24.01 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 15:59:25.09 INFO  ==> Creating user beast
postgresql-repmgr 15:59:25.10 INFO  ==> Granting access to "beast" to the database "beast"
postgresql-repmgr 15:59:25.13 INFO  ==> Setting ownership for the 'public' schema database "beast" to "beast"
postgresql-repmgr 15:59:25.15 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
postgresql-repmgr 15:59:25.38 INFO  ==> Configuring replication parameters
postgresql-repmgr 15:59:25.41 INFO  ==> Configuring fsync
postgresql-repmgr 15:59:25.41 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 15:59:26.46 INFO  ==> Creating repmgr user: repmgr
postgresql-repmgr 15:59:26.49 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped

*********************SECOND ************************
postgresql-repmgr 16:00:25.49 INFO  ==>
postgresql-repmgr 16:00:25.50 INFO  ==> Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 16:00:25.50 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql-repmgr 16:00:25.50 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
postgresql-repmgr 16:00:25.50 INFO  ==>
postgresql-repmgr 16:00:25.51 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 16:00:25.53 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 16:00:25.55 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 16:00:25.57 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 16:00:25.75 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgresql-repmgr 16:00:25.75 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 16:00:25.75 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 16:00:25.86 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 16:00:25.87 INFO  ==> Initializing Repmgr...
postgresql-repmgr 16:00:25.88 INFO  ==> Initializing PostgreSQL database...
postgresql-repmgr 16:00:25.88 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql-repmgr 16:00:25.90 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql-repmgr 16:00:25.90 INFO  ==> Generating local authentication configuration
postgresql-repmgr 16:00:25.92 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql-repmgr 16:00:25.94 INFO  ==> Configuring replication parameters
postgresql-repmgr 16:00:25.96 INFO  ==> Configuring fsync
postgresql-repmgr 16:00:25.97 INFO  ==> Applying custom /opt/bitnami/postgresql/conf/pg_hba.conf
postgresql-repmgr 16:00:25.97 INFO  ==> ** PostgreSQL with Replication Manager setup finished! **

postgresql-repmgr 16:00:25.99 INFO  ==> Starting PostgreSQL in background...
pg_ctl: another server might be running; trying to start server anyway
server starting
< 2025-05-06 16:00:26.029 UTC    163 681a321a.a3 2025-05-06 16:00:26 UTC  >LOG:  pgaudit extension initialized
< 2025-05-06 16:00:26.040 UTC    163 681a321a.a3 2025-05-06 16:00:26 UTC  >LOG:  redirecting log output to logging collector process
< 2025-05-06 16:00:26.040 UTC    163 681a321a.a3 2025-05-06 16:00:26 UTC  >HINT:  Future log output will appear in directory "/opt/bitnami/postgresql/logs".
< 2025-05-06 16:00:26.040 UTC    163 681a321a.a3 2025-05-06 16:00:26 UTC  >LOG:  starting PostgreSQL 17.3 on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
< 2025-05-06 16:00:26.041 UTC    163 681a321a.a3 2025-05-06 16:00:26 UTC  >LOG:  listening on IPv4 address "0.0.0.0", port 5432
< 2025-05-06 16:00:26.041 UTC    163 681a321a.a3 2025-05-06 16:00:26 UTC  >LOG:  listening on IPv6 address "::", port 5432
< 2025-05-06 16:00:26.043 UTC    163 681a321a.a3 2025-05-06 16:00:26 UTC  >LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
< 2025-05-06 16:00:26.044 UTC    163 681a321a.a3 2025-05-06 16:00:26 UTC  >LOG:  hostssl record cannot match because SSL is disabled
< 2025-05-06 16:00:26.044 UTC    163 681a321a.a3 2025-05-06 16:00:26 UTC  >HINT:  Set "ssl = on" in postgresql.conf.
< 2025-05-06 16:00:26.044 UTC    163 681a321a.a3 2025-05-06 16:00:26 UTC  >CONTEXT:  line 10 of configuration file "/opt/bitnami/postgresql/conf/pg_hba.conf"
< 2025-05-06 16:00:26.046 UTC    169 681a321a.a9 2025-05-06 16:00:26 UTC  >LOG:  database system was interrupted; last known up at 2025-05-06 15:59:55 UTC
< 2025-05-06 16:00:26.243 UTC    169 681a321a.a9 2025-05-06 16:00:26 UTC  >LOG:  database system was not properly shut down; automatic recovery in progress
< 2025-05-06 16:00:26.245 UTC    169 681a321a.a9 2025-05-06 16:00:26 UTC  >LOG:  invalid record length at 0/3000118: expected at least 24, got 0
< 2025-05-06 16:00:26.245 UTC    169 681a321a.a9 2025-05-06 16:00:26 UTC  >LOG:  redo is not required
< 2025-05-06 16:00:26.247 UTC    167 681a321a.a7 2025-05-06 16:00:26 UTC  >LOG:  checkpoint starting: end-of-recovery immediate wait
< 2025-05-06 16:00:26.251 UTC    167 681a321a.a7 2025-05-06 16:00:26 UTC  >LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.002 s, total=0.005 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB; lsn=0/3000118, redo lsn=0/3000118
< 2025-05-06 16:00:26.254 UTC    163 681a321a.a3 2025-05-06 16:00:26 UTC  >LOG:  database system is ready to accept connections
< 2025-05-06 16:00:27.029 UTC [unknown] [unknown] [unknown] 175 681a321b.af 2025-05-06 16:00:27 UTC 127.0.0.1(52008) >LOG:  connection received: host=127.0.0.1 port=52008
< 2025-05-06 16:00:27.029 UTC [unknown] postgres postgres 175 681a321b.af 2025-05-06 16:00:27 UTC 127.0.0.1(52008) >LOG:  connection authenticated: user="postgres" method=trust (/opt/bitnami/postgresql/conf/pg_hba.conf:3)
< 2025-05-06 16:00:27.029 UTC [unknown] postgres postgres 175 681a321b.af 2025-05-06 16:00:27 UTC 127.0.0.1(52008) >LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
< 2025-05-06 16:00:27.043 UTC pg_isready postgres postgres 175 681a321b.af 2025-05-06 16:00:27 UTC 127.0.0.1(52008) >LOG:  disconnection: session time: 0:00:00.014 user=postgres database=postgres host=127.0.0.1 port=52008
postgresql-repmgr 16:00:27.04 INFO  ==> ** Starting repmgrd **
[2025-05-06 16:00:27] [NOTICE] repmgrd (repmgrd 5.5.0) starting up
< 2025-05-06 16:00:27.063 UTC [unknown] [unknown] [unknown] 178 681a321b.b2 2025-05-06 16:00:27 UTC 10.42.0.113(49516) >LOG:  connection received: host=10.42.0.113 port=49516
< 2025-05-06 16:00:27.075 UTC [unknown] repmgr repmgr 178 681a321b.b2 2025-05-06 16:00:27 UTC 10.42.0.113(49516) >FATAL:  password authentication failed for user "repmgr"
< 2025-05-06 16:00:27.075 UTC [unknown] repmgr repmgr 178 681a321b.b2 2025-05-06 16:00:27 UTC 10.42.0.113(49516) >DETAIL:  Role "repmgr" does not exist.
        Connection matched file "/opt/bitnami/postgresql/conf/pg_hba.conf" line 9: "hostnossl    all             all             all                     md5"
[2025-05-06 16:00:27] [ERROR] connection to database failed
[2025-05-06 16:00:27] [DETAIL]
connection to server at "infrastructure-postgresql-ha-postgresql-0.infrastructure-postgresql-ha-postgresql-headless.default.svc.cluster.local" (10.42.0.113), port 5432 failed: FATAL:  password authentication failed for user "repmgr"
password retrieved from file "/opt/bitnami/repmgr/conf/.pgpass"

[2025-05-06 16:00:27] [DETAIL] attempted to connect using:
  user=repmgr passfile=/opt/bitnami/repmgr/conf/.pgpass connect_timeout=5 dbname=repmgr host=infrastructure-postgresql-ha-postgresql-0.infrastructure-postgresql-ha-postgresql-headless.default.svc.cluster.local port=5432 fallback_application_name=repmgr options=-csearch_path=

**Comment by gongomgra** [comment]
Hi @Stevenpc3 

I'm afraid I have not being able to reproduce your issue with the Chart version 15.3.16, the predefined images (`docker.io/bitnami/postgresql-repmgr:17.4.0-debian-12-r15` and `docker.io/bitnami/pgpool:4.6.0-debian-12-r5`), and your [custom values](https://github.com/bitnami/charts/issues/25671#issuecomment-2854744021) (except that I removed the private registries configuration you have set up). 

I have manually populated the TLS secrets for both the PostgreSQL and the pgpool objects, and the deployments has been running without issues for 15 minutes already

```
$ kubectl -n postgresql get all

NAME                                                   READY   STATUS    RESTARTS   AGE
pod/postgresql-postgresql-ha-pgpool-867fbbfcb6-hrkwn   1/1     Running   0          15m
pod/postgresql-postgresql-ha-postgresql-0              1/1     Running   0          15m
pod/postgresql-postgresql-ha-postgresql-1              1/1     Running   0          15m
pod/postgresql-postgresql-ha-postgresql-2              1/1     Running   0          15m

NAME                                                   TYPE        CLUSTER-IP        EXTERNAL-IP   PORT(S)    AGE
service/postgresql-postgresql-ha-pgpool                ClusterIP   192.168.194.229   <none>        5432/TCP   15m
service/postgresql-postgresql-ha-postgresql            ClusterIP   192.168.194.184   <none>        5432/TCP   15m
service/postgresql-postgresql-ha-postgresql-headless   ClusterIP   None              <none>        5432/TCP   15m

NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/postgresql-postgresql-ha-pgpool   1/1     1            1           15m

NAME                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/postgresql-postgresql-ha-pgpool-867fbbfcb6   1         1         1       15m

NAME                                                   READY   AGE
statefulset.apps/postgresql-postgresql-ha-postgresql   3/3     15m
```

Regarding PostgreSQL initialization, I see both the custom user and database have been created successfully, and also that repmgr starts just fine:

```
$ k -n postgresql logs postgresql-postgresql-ha-postgresql-0
postgresql-repmgr 10:53:00.81 INFO  ==>
postgresql-repmgr 10:53:00.81 INFO  ==> Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 10:53:00.82 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql-repmgr 10:53:00.82 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.ar
row.com/globalecs/na/vendors/bitnami/ for more information.
postgresql-repmgr 10:53:00.82 INFO  ==>
postgresql-repmgr 10:53:00.82 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 10:53:00.84 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 10:53:00.84 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 10:53:00.85 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 10:53:00.87 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgresql-repmgr 10:53:00.88 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 10:53:00.88 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 10:53:00.93 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 10:53:00.93 INFO  ==> Initializing Repmgr...
postgresql-repmgr 10:53:00.94 INFO  ==> Initializing PostgreSQL database...
postgresql-repmgr 10:53:00.94 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql-repmgr 10:53:00.94 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql-repmgr 10:53:00.94 INFO  ==> Generating local authentication configuration
postgresql-repmgr 10:53:02.46 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 10:53:03.57 INFO  ==> Changing password of postgres
postgresql-repmgr 10:53:03.59 INFO  ==> Creating user beast
postgresql-repmgr 10:53:03.60 INFO  ==> Granting access to "beast" to the database "beast"
postgresql-repmgr 10:53:03.61 INFO  ==> Setting ownership for the 'public' schema database "beast" to "beast"
postgresql-repmgr 10:53:03.62 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
postgresql-repmgr 10:53:04.04 INFO  ==> Configuring replication parameters
postgresql-repmgr 10:53:04.06 INFO  ==> Configuring fsync
postgresql-repmgr 10:53:04.06 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 10:53:05.10 INFO  ==> Creating repmgr user: repmgr
postgresql-repmgr 10:53:05.17 INFO  ==> Creating repmgr database: repmgr
postgresql-repmgr 10:53:05.21 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
postgresql-repmgr 10:53:05.62 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 10:53:06.65 INFO  ==> Registering Primary...
postgresql-repmgr 10:53:06.75 INFO  ==> Loading custom scripts...
postgresql-repmgr 10:53:06.75 INFO  ==> Configuring synchronous_replication
postgresql-repmgr 10:53:06.75 INFO  ==> Applying custom /opt/bitnami/postgresql/conf/pg_hba.conf
postgresql-repmgr 10:53:06.75 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
postgresql-repmgr 10:53:06.96 INFO  ==> ** PostgreSQL with Replication Manager setup finished! **

postgresql-repmgr 10:53:06.98 INFO  ==> Starting PostgreSQL in background...
(...)
postgresql-repmgr 10:53:08.01 INFO  ==> ** Starting repmgrd **
[2025-05-07 10:53:08] [NOTICE] repmgrd (repmgrd 5.5.0) starting up
< 2025-05-07 10:53:08.025 UTC [unknown] [unknown] [unknown] 345 681b3b94.159 2025-05-07 10:53:08 UTC fd07:b51a:cc66:a::81(50822) >LOG:  connection received: host=fd07:b51a:cc66:a::81 port=50822
< 2025-05-07 10:53:08.033 UTC [unknown] repmgr repmgr 345 681b3b94.159 2025-05-07 10:53:08 UTC fd07:b51a:cc66:a::81(50822) >LOG:  connection authenticated: identity="repmgr" method=md5 (/opt/bitnami/postgresql/conf/pg_hba.conf:9)
< 2025-05-07 10:53:08.033 UTC [unknown] repmgr repmgr 345 681b3b94.159 2025-05-07 10:53:08 UTC fd07:b51a:cc66:a::81(50822) >LOG:  connection authorized: user=repmgr database=repmgr application_name=repmgr
< 2025-05-07 10:53:08.038 UTC repmgr repmgr repmgr 345 681b3b94.159 2025-05-07 10:53:08 UTC fd07:b51a:cc66:a::81(50822) >LOG:  AUDIT: SESSION,1,1,READ,SELECT,,,"SELECT ae.name, e.extname,            ae.default_version,            (((FLOOR(ae.default_version::NUMERIC)::INT) * 10000) + (ae.default_ve
rsion::NUMERIC - FLOOR(ae.default_version::NUMERIC)::INT) * 1000)::INT AS available,            ae.installed_version,            (((FLOOR(ae.installed_version::NUMERIC)::INT) * 10000) + (ae.installed_version::NUMERIC - FLOOR(ae.installed_version::NUMERIC)::INT) * 1000)::INT AS installed      FROM p
g_catalog.pg_available_extensions ae LEFT JOIN pg_catalog.pg_extension e        ON e.extname=ae.name       WHERE ae.name='repmgr'",<not logged>
< 2025-05-07 10:53:08.040 UTC repmgr repmgr repmgr 345 681b3b94.159 2025-05-07 10:53:08 UTC fd07:b51a:cc66:a::81(50822) >LOG:  AUDIT: SESSION,2,1,READ,SELECT,,,"SELECT n.node_id, n.type, n.upstream_node_id, n.node_name,  n.conninfo, n.repluser, n.slot_name, n.location, n.priority, n.active, n.confi
g_file, '' AS upstream_node_name, NULL AS attached   FROM repmgr.nodes n  WHERE n.node_id = 1000",<not logged>
(...)
```

**Comment by Stevenpc3** [comment]
Thank you for trying.  It is early for me, but NOT reproducing is a GOOD thing 😉   It gives me more to work with while isolating.  I will dig more into your response and try a few things to reduce my set until it works.

I did notice that I forgot to add some global values that I use for the ```existingSecret``` that we use.  Under the current deploy you used I assume postgresql generated it's own secret.

```
global:
  infrastructureRelease: infrastructure
  postgresql:
    existingSecret: '{{ printf "%s-%s" (default .Release.Name .Values.global.infrastructureRelease) "postgresql-secrets-auth" }}'
    tls:
      disabled: true
  pgpool:
    existingSecret: '{{ printf "%s-%s" (default .Release.Name .Values.global.infrastructureRelease) "postgresql-secrets-auth" }}'
```

with the custom secret (it has legacy values in it for those that didn't get to migrate fully yet)

```
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "common/names/fullname" . }}-auth
  labels: {{ include "common/labels/metadata" . | nindent 4 }}
type: Opaque
data:
  password: cGFzc3dvcmQ=
  postgres-password: cGFzc3dvcmQ=
  postgresql-password: cGFzc3dvcmQ=
  postgresql-postgres-password: cGFzc3dvcmQ=
  repmgr-password: cGFzc3dvcmQ=
  admin-password: cGFzc3dvcmQ=
```

We need to provide custom secrets.  I will attempt today to test without them and see if it works.  I will also look into passing the generated secret to our services so we no longer need to generate our own.

**Comment by Stevenpc3** [comment]
Yeah so I tested with and without ```existingSecret``` and it breaks with one.

So it appears the "repmgr does not exist" is solved from container images ```17.2.0-debian-12-r9  -> 17.4.0-debian-12-r16``` but for some reason passing an existing secret appears to no longer work in those versions.... at least in my combination.

**Comment by Stevenpc3** [comment]
I got it to work.  

It has to do with the pgHbaConfigurtation.  I udpated our hba override to be 

```
pgHbaConfiguration: |
      # "local" is for Unix domain socket connections only
      local        all             all                                     trust
      host         repmgr          repmgr          0.0.0.0/0               trust
      host         repmgr          repmgr          ::/0                    trust
      host         replication     repmgr          0.0.0.0/0               trust
      host         replication     repmgr          ::/0                    trust
      host         all             all             127.0.0.1/32            trust
      host         all             all             ::1/128                 trust
      local        replication     all                                     trust
      host         replication     all             127.0.0.1/32            trust
      host         replication     all             ::1/128                 trust
      hostnossl    replication     all             all                     md5
      hostnossl    all             all             all                     md5
      hostssl      all             all             all                     cert map=cert-users
```

I had tested with it OFF to use the default HBA in [17.4.0-debian-12-r17](https://github.com/bitnami/containers/pull/80877/files#top) but it was broken from a recent change https://github.com/bitnami/containers/pull/80877/files#diff-66058caf4e80bb21d7f4a880b4b481835ade503727fafac613e21d31f73236afL435 flipped the order and I got the following error

![Image](https://github.com/user-attachments/assets/fe7a9c8a-d17f-4060-9d1b-0bede6ca8384)

This is similar to the older errors listed because the hba didn't have a match or matched something too relaxed first.

I suggest reverting the HBA order changes made in the r17 image.

**Comment by juan131** [comment]
Hi @Stevenpc3 

In the PostgreSQL with Repmgr container the database set in the `REPMGR_DATABASE` env. variable must exist in the `ph_hba.conf` file for Repmgr to work properly. In the chart, we set this to `repmgr` by default (it can be customized by setting `postgresql.repmgrDatabase` or `global.postgresql.repmgrDatabase`).

If you're customizing this file, you need to ensure you properly add an entry for this database.

**Comment by Stevenpc3** [comment]
I will give it a try, but as I said it did not work by DEFAULT without introducing that file when strung "global.existingSecrets"

**Comment by juan131** [comment]
> I will give it a try

Please keep us updated @Stevenpc3 !

> as I said it did not work by DEFAULT without overriding that file when using "global.existingSecrets"

Regarding this, I'm sorry but I didn't find any reference on this issue to that, maybe you mentioned it in another issue/pr or sth like that. I'm assuming you're referring to the `global.postgresql.existingSecret` and `global.pgpool.existingSecret` parameters, right? The ones declared below:

- https://github.com/bitnami/charts/blob/main/bitnami/postgresql-ha/values.yaml#L18
- https://github.com/bitnami/charts/blob/main/bitnami/postgresql-ha/values.yaml#L25

**Comment by Stevenpc3** [comment]
Yes using those values you linked as stated in this comment above https://github.com/bitnami/charts/issues/25671#issuecomment-2858502207 and the one below it.

I ran ```helm install my-release oci://registry-1.docker.io/bitnamicharts/postgresql-ha --set global.postgresql.existingSecret=postgresql-secrets-auth --set global.pgpool.existingSecret=postgresql-secrets-auth --version=15.3.17``` as you can see in the image.

![Image](https://github.com/user-attachments/assets/238c5569-5c27-455f-9448-56bb1972b4ed)

This actually worked fine.

![Image](https://github.com/user-attachments/assets/bfdefe95-720d-4e82-82b9-b9ddd6eceeb8)

**BUT** setting the following does NOT WORK.

```helm install my-release oci://registry-1.docker.io/bitnamicharts/postgresql-ha --version=15.3.17 --set global.postgresql.existingSecret=postgresql-secrets-auth --set global.pgpool.existingSecret=postgresql-secrets-auth --set postgresql.database=test --set postgresql.username=test```

![Image](https://github.com/user-attachments/assets/bdf7d252-fa23-4ed5-aabb-0040525cd890)

This fails with the following error

![Image](https://github.com/user-attachments/assets/20b78121-6383-4437-a33e-9d388f257b42)

So the fail combination requires setting existingSecrets AND setting custom postgresql.database AND postgresql.username

**Comment by juan131** [comment]
Hi @Stevenpc3 

Thanks for providing the context and sorry I missed that previous comment.

The [changes you pointed out](https://github.com/bitnami/containers/pull/80877/files#diff-66058caf4e80bb21d7f4a880b4b481835ade503727fafac613e21d31f73236afL435) introduced on the `17.4.0-debian-12-r17` container image release were designed to work with other changes we introduced in the chart on the version `16.0.0`. This is explained in the upgrading notes below:

- https://github.com/bitnami/charts/tree/main/bitnami/postgresql-ha#to-1600

It seems our automations released a chart version in the middle (`15.3.17`) bumping the container version before I sent [this PR](https://github.com/bitnami/charts/pull/33552). We should've tried to avoid that.

Are you able to reproduce the issue using `16.0.0`? Please note that, if you're using `global.pgpool.existingSecret`, in the new chart major version the Pgpool secret actually expects two keys: `admin-password` and `sr-check-password`.

**Comment by Stevenpc3** [comment]
yes this fails with the latest also

```helm install my-release oci://registry-1.docker.io/bitnamicharts/postgresql-ha --set global.postgresql.existingSecret=postgresql-secrets-auth --set global.pgpool.existingSecret=postgresql-secrets-auth --set postgresql.database=test --set postgresql.username=test```

![Image](https://github.com/user-attachments/assets/91757ada-3590-41c5-8b52-2a41d0983219)

![Image](https://github.com/user-attachments/assets/adb51714-8847-4f31-b821-7fe5b39f2d88)
