### ISSUE TITLE
mastodon fails to startup

### ISSUE THREAD

**Issue by robertbovens** [bitnami/charts#31025]
### Name and Version

bitnami/mastodon App Version: 4.2.12 Package Version: 7.0.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Mastodon runs well until I need to reboot the system or just restart kubernetes, mastodon won't be able to start. It only helps to redeploy mastodon-web container.

### Are you using any custom parameters or values?

yes, but it does not have to do with a directory issue

### What is the expected behavior?

Mastodon start without any problem

### What do you see instead?

Mastodon won't start normally and the pod of mastodon-web gives the error:
```
Container: prepare-tmp-dir
Filter
Disconnected
mkdir: cannot create directory '/tmp/tmp-dir': File exists
```

**Comment by robertbovens** [comment]
By the way, it also helps to scale down mastodon-web to 0 and then to 1 again, then it starts normally

**Comment by robertbovens** [comment]
I am still on 4.2.12 Package Version: 7.0.5, i will try upgrade

**Comment by robertbovens** [comment]
I upgraded to Package Version: 8.0.0, same issue. I need more time to upgrade further

**Comment by robertbovens** [comment]
Upgrade to 9.0.4 didnt help either, i install with kubeapps and since kubeapps is giving me now sql error i cant upgrade, will try tomorrow.

**Comment by robertbovens** [comment]
Now I`m stuck when i want to upgrade further. I already reinstalled kubeapps, but when i try to upgrade to 9.0.5 or 9.1, kubeapps throws an error:
Unable to fetch the package "bitnami/mastodon (9.0.4)": Unable to get the available package detail for the package "bitnami/mastodon" using the plugin "helm.packages": internal: Unable to retrieve chart files: sql: no rows in result set.

Thanx

**Comment by migruiz4** [comment]
Hi @robertbovens,

That error is caused by an issue with the latest version of kubeapps. 
We plan to release a new version of kubeapps (2.12.1) fixing this in the next days.

**Comment by robertbovens** [comment]
Ok thanx for the info @migruiz4

**Comment by migruiz4** [comment]
@robertbovens we have just released a new version of kubeapps (v2.12.1) which should fix the chart upgrade issue.

You can not install the bitnami/kubeapps chart version 17.1.1 that use the kubeapps version v2.12.1: 
https://hub.docker.com/layers/bitnamicharts/kubeapps/17.1.1/images/sha256-a0bd2dcb9264e261e20a1f96dc6703e0fd3132524a991a085efac3364b8b7777

**Comment by robertbovens** [comment]
I reinstalled kubeapps, now i was able to upgrade mastodon. The problem is still there after rebooting/restarting kubernetes.
cannot create directory '/tmp/tmp-dir': File exists

When i scale down and scale up mastodon-web, everything resumes operations like it should be.

**Comment by dgomezleon** [comment]
Hi @robertbovens 

Thanks for upgrading to the latest version.

> By the way, it also helps to scale down mastodon-web to 0 and then to 1 again, then it starts normally

I was not able to reproduce the issue on GKE. This is what I tried:

1. `helm install mastodon . -f ../../.vib/mastodon/runtime-parameters.yaml`
2. Edit `mastodon-web` deployment to 0 replicas
3. Edit `mastodon-web` deployment to 1 replicas

It was properly started as you can see from the output below:
```
mastodon-apache-777fdf8f85-tl8gs        1/1     Running     0          34m
mastodon-elasticsearch-coordinating-0   1/1     Running     0          34m
mastodon-elasticsearch-data-0           1/1     Running     0          34m
mastodon-elasticsearch-ingest-0         1/1     Running     0          34m
mastodon-elasticsearch-master-0         1/1     Running     0          34m
mastodon-minio-697cd5f7fd-zq57l         1/1     Running     0          34m
mastodon-minio-provisioning-zmzcw       0/1     Completed   0          34m
mastodon-postgresql-0                   1/1     Running     0          34m
mastodon-redis-master-0                 1/1     Running     0          34m
mastodon-sidekiq-6d8b5cdcd5-xjlmg       1/1     Running     0          34m
mastodon-streaming-75d7755976-glmqg     1/1     Running     0          34m
mastodon-web-7d769f6d88-kmz22           1/1     Running     0          55s
```

Could you please le me know what could differ from your scenario?

**Comment by robertbovens** [comment]
My scenario is:
no apache, no elasticsearch and no minio, i use pvs.
I have all resourcesPreset set to none.

I took my settings to other vm with kubernetes. Installed with helm3.
The install is fine, and it works. The problem is ONLY and ONLY when i reboot the vm or restart kubernetes, then the error still exist: I even put all settings to standard settings, so now it boots also elasticsearch, apache etc, but i also end with the same problem AFTER a reboot of the vm:

CrashLoopBackOff (back-off 5m0s restarting failed container=prepare-tmp-dir pod=mastodon-web-6ffc96ffbc-p2jgk_mastodon-test(672133b6-062e-4630-bd4f-5ffefab4ad70)) | Last state: Terminated with 1: Error, started: Thu, Dec 26 2024 2:51:10 pm, finished: Thu, Dec 26 2024 2:51:11 pm

mkdir: cannot create directory '/tmp/tmp-dir': File exists

At this moment i need to set mastodon-web to 0 deployments and then 1, then it boots like it should. I need to tell you that i use rancher for my kubernetes vms, so i have a + and a - button to scale my deployment.

Thanks again for you support

**Comment by robertbovens** [comment]
- [ ] mastodon-elasticsearch-coordinating-0        1/1     Running        1 (11m ago)   26m
- [ ] mastodon-elasticsearch-data-0                      1/1     Running        1 (11m ago)   26m
- [ ] mastodon-elasticsearch-ingest-0                   1/1     Running        1 (11m ago)   26m
- [ ] mastodon-elasticsearch-master-0                  1/1     Running        1 (11m ago)   26m
- [ ] mastodon-init-jr2dm                                      0/2     Completed    0             26m
- [ ] mastodon-postgresql-0                                  1/1     Running        1 (11m ago)   26m
- [ ] mastodon-redis-master-0                               1/1     Running        1 (11m ago)   26m
- [ ] mastodon-sidekiq-84cbbc7d48-g8tfd            0/1     Unknown      0             26m
- [ ] mastodon-streaming-6d8948d45c-dzmkn     0/1     Unknown      0             26m
- [ ] mastodon-web-6ffc96ffbc-p2jgk                    0/1     Unknown      5             26m

**Comment by robertbovens** [comment]
I can see now a difference, my init job is still in the list, not sure if it tells you anything, but yours doesn`t show that. Not sure if it has something to do with it or not though.
