### ISSUE TITLE
[bitnami/redis] Sentinel master-slave with ACL - Startup probe failed: NOAUTH Authentication required.

### ISSUE THREAD

**Issue by alekseytivonchik** [bitnami/charts#36237]
### Name and Version

bitnami/redis 23.0.0

### What steps will reproduce the bug?

1. Env:
K8s: v1.30.4
Helm: v3.14.2
Redis 2 node cluster with Sentinel

2. My [values.yaml](https://gist.github.com/alekseytivonchik/994dbab371bf1a09b53710382c742fbb) configuration
3. Steps
```bash
$ helm install redis -n redis -f values.yaml .
```

### Are you using any custom parameters or values?

Custom auth block
```yaml
auth:
  enabled: true
  sentinel: true
  password: ""
  existingSecret: ""
  existingSecretPasswordKey: ""
  usePasswordFiles: true
  usePasswordFileFromSecret: true
  acl:
    enabled: true
    sentinel: true
    users: 
      - username: "user-test"
        password: ""
        enabled: "on"
        commands: "+@all"
        keys: "~*"
        channels: "&*"
    userSecret: "redis-acl"
```
redis-acl secret
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: redis-acl
  namespace: redis
type: Opaque
data:
  user-test: d1ErTWY4RXFGRw==
  
```

### What is the expected behavior?

Success install Redis master-slave with sentinel

### What do you see instead?

Error on redis-node-0 pod:
```bash
$ k get po -n redis -o wide
NAME           READY   STATUS    RESTARTS   AGE   IP              NODE                     NOMINATED NODE   READINESS GATES
redis-node-0   1/2     Running   0          31s   10.233.116.47   loyalty-dev-kube-pool0   <none>           <none>

$ k describe po redis-node-0 -n redis
...
Warning  Unhealthy  58s   kubelet            Startup probe failed:
Could not connect to Redis at localhost:26379: Connection refused
  Warning  Unhealthy  58s  kubelet  Startup probe failed:
Could not connect to Redis at localhost:6379: Connection refused
  Warning  Unhealthy  8s (x5 over 48s)  kubelet  Startup probe failed: NOAUTH Authentication required.
AUTH failed: WRONGPASS invalid username-password pair or user is disabled.
```
Redis pod log
```
Defaulted container "redis" out of: redis, sentinel
 12:47:17.55 INFO  ==> about to run the command: REDISCLI_AUTH=$REDIS_PASSWORD  timeout 90 redis-cli -h redis.redis.svc.cluster.local -p 26379 sentinel get-master-addr-by-name loyaltymaster
Could not connect to Redis at redis.redis.svc.cluster.local:26379: Connection refused
Could not connect to Redis at redis.redis.svc.cluster.local:26379: Connection refused
 12:47:27.57 INFO  ==> Found previous master redis-node-0.redis-headless.redis.svc.cluster.local:6379 in /opt/bitnami/redis-sentinel/etc/sentinel.conf
 12:47:27.58 INFO  ==> Configuring the node as master
1:C 04 Sep 2025 12:47:27.655 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 04 Sep 2025 12:47:27.655 * Redis version=8.2.1, bits=64, commit=00000000, modified=1, pid=1, just started
1:C 04 Sep 2025 12:47:27.655 * Configuration loaded
1:M 04 Sep 2025 12:47:27.655 * monotonic clock: POSIX clock_gettime
1:M 04 Sep 2025 12:47:27.656 * Running mode=standalone, port=6379.
1:M 04 Sep 2025 12:47:27.657 * Server initialized
1:M 04 Sep 2025 12:47:27.657 * Reading RDB base file on AOF loading...
1:M 04 Sep 2025 12:47:27.657 * Loading RDB produced by version 8.2.1
1:M 04 Sep 2025 12:47:27.657 * RDB age 5068 seconds
1:M 04 Sep 2025 12:47:27.657 * RDB memory usage when created 0.62 Mb
1:M 04 Sep 2025 12:47:27.657 * RDB is base AOF
1:M 04 Sep 2025 12:47:27.657 * Done loading RDB, keys loaded: 0, keys expired: 0.
1:M 04 Sep 2025 12:47:27.657 * DB loaded from base file appendonly.aof.1.base.rdb: 0.000 seconds
1:M 04 Sep 2025 12:47:27.657 * DB loaded from append only file: 0.000 seconds
1:M 04 Sep 2025 12:47:27.659 * Opening AOF incr file appendonly.aof.1.incr.aof on server start
1:M 04 Sep 2025 12:47:27.659 * Ready to accept connections tcp
```

**Comment by alekseytivonchik** [comment]
I'm not sure if this configuration option is standard, but the following configuration of the auth block worked for me:
```yaml
auth:
  enabled: true
  sentinel: true
  password: ""
  existingSecret: "redis-acl"
  existingSecretPasswordKey: "user-test"
  usePasswordFiles: true
  usePasswordFileFromSecret: true
  acl:
    enabled: true
    sentinel: true
    users: 
      - username: "user-test"
        password: ""
        enabled: "on"
        commands: "+@all"
        keys: "~*"
        channels: "&*"
    userSecret: "redis-acl"
```
Changes:
```yaml
auth:
  existingSecret: "redis-acl"
  existingSecretPasswordKey: "user-test"
```
The final idea of Redis deployment is to manage the helm chart using argocd. This remains to be verified.

**Comment by alekseytivonchik** [comment]
When deploying via argocd, the problem persists

pod events
```
Warning  Unhealthy  6m29s  kubelet            Startup probe failed:
Could not connect to Redis at localhost:26379: Connection refused
  Warning  Unhealthy  6m29s  kubelet  Startup probe failed:
Could not connect to Redis at localhost:6379: Connection refused
  Warning  Unhealthy  89s (x29 over 6m19s)  kubelet  Startup probe failed: NOAUTH Authentication required.
AUTH failed: WRONGPASS invalid username-password pair or user is disabled.
```
redis-node-0 log
```
Defaulted container "redis" out of: redis, sentinel
 14:25:41.69 INFO  ==> about to run the command: REDISCLI_AUTH=$REDIS_PASSWORD  timeout 90 redis-cli -h redis.redis.svc.cluster.local -p 26379 sentinel get-master-addr-by-name loyaltymaster
Could not connect to Redis at redis.redis.svc.cluster.local:26379: Connection refused
Could not connect to Redis at redis.redis.svc.cluster.local:26379: Connection refused
 14:25:51.76 INFO  ==> Found previous master redis-node-0.redis-headless.redis.svc.cluster.local:6379 in /opt/bitnami/redis-sentinel/etc/sentinel.conf
 14:25:51.77 INFO  ==> Configuring the node as master
1:C 04 Sep 2025 14:25:51.850 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 04 Sep 2025 14:25:51.850 * Redis version=8.2.1, bits=64, commit=00000000, modified=1, pid=1, just started
1:C 04 Sep 2025 14:25:51.850 * Configuration loaded
1:M 04 Sep 2025 14:25:51.851 * monotonic clock: POSIX clock_gettime
1:M 04 Sep 2025 14:25:51.851 * Running mode=standalone, port=6379.
1:M 04 Sep 2025 14:25:51.852 * Server initialized
1:M 04 Sep 2025 14:25:51.852 * Reading RDB base file on AOF loading...
1:M 04 Sep 2025 14:25:51.852 * Loading RDB produced by version 8.2.1
1:M 04 Sep 2025 14:25:51.852 * RDB age 220 seconds
1:M 04 Sep 2025 14:25:51.852 * RDB memory usage when created 0.62 Mb
1:M 04 Sep 2025 14:25:51.852 * RDB is base AOF
1:M 04 Sep 2025 14:25:51.852 * Done loading RDB, keys loaded: 0, keys expired: 0.
1:M 04 Sep 2025 14:25:51.852 * DB loaded from base file appendonly.aof.1.base.rdb: 0.001 seconds
1:M 04 Sep 2025 14:25:51.852 * DB loaded from append only file: 0.001 seconds
1:M 04 Sep 2025 14:25:51.854 * Opening AOF incr file appendonly.aof.1.incr.aof on server start
1:M 04 Sep 2025 14:25:51.854 * Ready to accept connections tcp
```

The architectural idea of my infrastructure involves management through argocd. Any ideas how to fix it, or is this question no longer for you?

P.S. The secret "redis-acl" deployed via other app in ArgoCD and always present in redis namespace

**Comment by javsalgar** [comment]
Hi,

Indeed, for the readiness/liveness probe to work you need to have the REDIS_PASSWORD variable set because `auth.enabled`

```
        echo "{{- if and .Values.auth.enabled .Values.auth.sentinel }}REDISCLI_AUTH="\$REDIS_PASSWORD" {{ end }} $command ${args[*]}"
``` 

About argo-cd, could you confirm that the REDIS_PASSWORD variable is set or it is missing in the pod YAML?

**Comment by alekseytivonchik** [comment]
@javsalgar Hi, REDIS_PASSWORD variable is set for redis and sentinel containers:
```bash
$ k describe po redis-node-0 -n redis | grep REDIS_PASSWORD
      REDIS_PASSWORD_FILE:         /opt/bitnami/redis/secrets/redis-password
      REDIS_PASSWORD_FILE:         /opt/bitnami/redis/secrets/redis-password

$ cat /opt/bitnami/redis/secrets/redis-password;echo
wQ+Mf8EqFG
```
Also try:
```yaml
auth:
  usePasswordFiles: false
  usePasswordFileFromSecret: false
```

```bash
$ k describe po redis-node-0 -n redis | grep REDIS_PASSWORD
      REDIS_PASSWORD:              <set to the key 'loyalty-user' in secret 'redis-acl'>  Optional: false
      REDIS_PASSWORD:              <set to the key 'loyalty-user' in secret 'redis-acl'>  Optional: false
```
Result is the same

The sentinel container has status ready and value of REDIS_PASSWORD is correct
```
echo $REDIS_PASSWORD
wQ+Mf8EqFG
```

If i disable all probes for redis node, exec into pod and run `/health/ping_sentinel.sh 30`, the script completes without errors
I have no ideas how to fix it for now(
```bash
/health/ping_sentinel.sh 10;echo $?
0
```

**Comment by alekseytivonchik** [comment]
@javsalgar i have an idea, look for probes cmd in pod description and run manualy inside pod

```bash
/bin/bash -ec /health/ping_sentinel.sh 5;echo $?
timeout: invalid time interval 'redis-cli'
Try 'timeout --help' for more information.

1
```
let's try another way
```bash
/bin/bash -ec '/health/ping_sentinel.sh 5';echo $?
0
```

We have `/bin/bash -ec` so we should use `'/health/ping_sentinel.sh 5'`
Am i right?

**Comment by toxabol** [comment]
@alekseytivonchik Hi there! Faced kinda same issue. For me it looks like `userSecret` is an actual issue. 

While using ACL users with `userSecret` configured, users are creating with blank passwords which cause `NOAUTH Authentication required`. If you'll define them using `password` field directly in `users` block for test, they'll be created correctly. Keep in mind that enabled `userSecret` will override your hardcoded passwords.

You can check created acl users by this commands:

```
kubectl exec -n redis redis-master-0 -- cat /opt/bitnami/redis/etc/users.acl
kubectl exec -n redis redis-replicas-0 -- cat /opt/bitnami/redis/etc/users.acl

```


Also you may want to use `extraFlags` to fix replica connection since it will try to connect as default user.

```
extraFlags:
    - "--masteruser admin"
    - "--masterauth somepass1"
```


My auth block for reference

```
auth:
  enabled: true
  acl:
    enabled: true
    # userSecret: "somesecret"
    users:
      - username: "admin"
        password: "somepass1"
        enabled: "on"
        commands: "+@all"
        keys: "~*"
        channels: "&*"
      - username: "readonly"
        password: "somepass2"
        enabled: "on" 
        commands: "+get"
        keys: "~*"
        channels: "&*"
```

My secret for reference
```
apiVersion: v1
kind: Secret
metadata:
  name: somesecret
  namespace: redis
type: Opaque
stringData:
  admin: somepass1
  readonly: somepass2
```

**Comment by alekseytivonchik** [comment]
@toxabol hi! thx for the response, but with ArgoCD doesn't work for me. Now i am using standalone arch :(
any information about fix?

**Comment by Nickmman** [comment]
I've encountered the issue where when the ACL is enabled and the redis password is set via `existingSecret` and `existingSecretPasswordKey`, the hash generated that ends up in the users.acl section of the `redis-configuration` ConfigMap does not match up with the hash that it *should* be.

Instead, it is a different hash that I can't figure out where it comes from. I've tried the secret name, the secret key name, the base64 password of the secret, even removing the pre-established secret and let one get created by default, none of these match up with the generated hash in `users.acl`.

The resulting hash of an additional user, with the password specified in the `users` section, does match up with what it should be. Just not the hash for the `default` user.

**Comment by jotamartos** [comment]
Sorry for the delay here. I'm going to work on reproducing the issue and will update this thread as soon as I have more information.

**Comment by jotamartos** [comment]
Hi again, 

I tried to reproduce the error but I couldn't do so. I deployed the solution from the command line and using Argo CD, and Redis got deployed correctly.

```
➜  redis git:(main) k get pods 
NAME                                      READY   STATUS    RESTARTS      AGE
argo-cd-app-controller-786f955bb6-dcvj5   1/1     Running   0             27m
argo-cd-redis-master-0                    1/1     Running   0             27m
argo-cd-repo-server-6c9ccc759f-z75pz      1/1     Running   2 (18m ago)   27m
argo-cd-server-759b988479-g6srq           1/1     Running   0             27m
redis-node-0                              2/2     Running   0             107s
redis-node-1                              2/2     Running   0             59s
➜  redis git:(main) k logs redis-node-0
Defaulted container "redis" out of: redis, sentinel
 07:07:34.29 INFO  ==> about to run the command: REDISCLI_AUTH=$REDIS_PASSWORD  timeout 90 redis-cli -h redis.test.svc.cluster.local -p 26379 sentinel get-master-addr-by-name mymaster
Could not connect to Redis at redis.test.svc.cluster.local:26379: Connection refused
Could not connect to Redis at redis.test.svc.cluster.local:26379: Connection refused
 07:07:44.46 INFO  ==> Configuring the node as master
1:C 15 Oct 2025 07:07:44.499 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 15 Oct 2025 07:07:44.499 * Redis version=8.2.1, bits=64, commit=00000000, modified=1, pid=1, just started
1:C 15 Oct 2025 07:07:44.499 * Configuration loaded
1:M 15 Oct 2025 07:07:44.499 * monotonic clock: POSIX clock_gettime
1:M 15 Oct 2025 07:07:44.500 * Running mode=standalone, port=6379.
1:M 15 Oct 2025 07:07:44.501 * Server initialized
1:M 15 Oct 2025 07:07:44.505 * Creating AOF base file appendonly.aof.1.base.rdb on server start
1:M 15 Oct 2025 07:07:44.510 * Creating AOF incr file appendonly.aof.1.incr.aof on server start
1:M 15 Oct 2025 07:07:44.510 * Ready to accept connections tcp
1:M 15 Oct 2025 07:08:18.052 * Replica redis-node-1.redis-headless.test.svc.cluster.local:6379 asks for synchronization
1:M 15 Oct 2025 07:08:18.052 * Full resync requested by replica redis-node-1.redis-headless.test.svc.cluster.local:6379 
1:M 15 Oct 2025 07:08:18.052 * Replication backlog created, my new replication IDs are '325196da5403e5a3711e638fd31ad9b0f7ca5ec5' and '0000000000000000000000000000000000000000'
1:M 15 Oct 2025 07:08:18.052 * Replica redis-node-1.redis-headless.test.svc.cluster.local:6379 is capable of rdb channel synchronization, and partial sync isn't possible. Full sync will continue with dedicated rdb channel.
1:M 15 Oct 2025 07:08:18.054 * Replica 240.0.176.18:6379 asks for synchronization
1:M 15 Oct 2025 07:08:18.054 * Full resync requested by replica 240.0.176.18:6379 (rdb-channel)
1:M 15 Oct 2025 07:08:18.054 * Delay next BGSAVE for diskless SYNC
1:M 15 Oct 2025 07:08:23.304 * Starting BGSAVE for SYNC with target: replicas sockets (rdb-channel)
1:M 15 Oct 2025 07:08:23.304 * Starting to deliver RDB and replication stream to replica: redis-node-1.redis-headless.test.svc.cluster.local:6379
1:M 15 Oct 2025 07:08:23.305 * Background RDB transfer started by pid 167 to replica socket
167:C 15 Oct 2025 07:08:23.306 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
1:M 15 Oct 2025 07:08:23.319 * Synchronization with replica redis-node-1.redis-headless.test.svc.cluster.local:6379 succeeded
1:M 15 Oct 2025 07:08:23.325 * Connection with replica (rdbchannel) 240.0.176.18:6379 lost.
1:M 15 Oct 2025 07:08:23.407 * Background RDB transfer terminated with success
```

<img width="1538" height="1127" alt="Image" src="https://github.com/user-attachments/assets/ed2610f6-98e2-49b0-b265-88976a77ed94" />

Regarding the values I used, this is the custom.yaml file 

```
auth:
  existingSecret: "redis-acl"
  existingSecretPasswordKey: "user-test"
  acl:
    enabled: true
    sentinel: true
    users: 
      - username: "user-test"
        password: ""
        enabled: "on"
        commands: "+@all"
        keys: "~*"
        channels: "&*"
    userSecret: "redis-acl"
sentinel:
  enabled: true
replica:
  replicaCount: 2
```

and the redis-acl secret is the same you posted above.

**Comment by Nickmman** [comment]
@jotamartos Maybe there needs to be some tweaking in the way you are deploying your test case. I just tried again with a fresh deployment of redis and am still seeing the same issue.

For reference, I am using chart version 22.0.7, with the following custom values:
```
auth:
  acl:
    enabled: true
    userSecret: redis-custom-users
    users:
    - channels: '&*'
      commands: +@all
      enabled: "on"
      keys: ~*
      username: testUser
  existingSecret: redis
  existingSecretPasswordKey: redis-password
fullNameOverride: redis-test
global:
  security:
    allowInsecureImages: true
  storageClass: standard-rwo
image:
  debug: true
  repository: bitnamilegacy/redis
kubectl:
  image:
    repository: bitnamilegacy/kubectl
master:
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 4Gi
metrics:
  enabled: true
  image:
    repository: bitnamilegacy/redis-exporter
replica:
  replicaCount: 1
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 4Gi
```

I personally am not deploying using command line, but rather using an ArgoCD Application Spec, via template, which wouldn't have a difference between CLI or GitOps:
```
{{- if .Values.redisTest.enabled }}
{{- $this := .Values.redisTest }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ if .Values.project.namespace }}{{ .Values.project.namespace }}-{{ end }}redis-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ if .Values.project.namespace }}{{ .Values.project.namespace }}{{ else if $this.namespace }}{{ $this.namespace }}{{ else }}redis{{ end }}
    server: {{ $.Values.cluster.address }}
  project: {{ $.Values.project.name }}
  source:
    repoURL: {{ if semverCompare "<18.0.0" .Values.redisTest.version }}https://charts.bitnami.com/bitnami{{ else }}registry-1.docker.io/bitnamicharts{{ end }}
    targetRevision: {{ $this.version }}
    chart: redis
    helm:
      releaseName: redis-test
    {{- with $this.values }}
      values: |-
      {{ toYaml . | nindent 8 }}
    {{- end }}
  {{- if $this.syncPolicy }}
  syncPolicy:{{- toYaml $this.syncPolicy | nindent 4 }}
  {{- else }}
  syncPolicy:{{- toYaml $.Values.syncPolicy | nindent 4 }}
  {{- end }}
{{- end -}}
```


The `redis-custom-users` secret, contains the following (decoded):
```
testUser: hcd5wkd-jat4qze0JGH
```

However, the generated configuration ConfigMap contains this:
```
users.acl:
----
user default on #6e7e68cedbc9227d0805ffb96474e4af6b76bd4f3761bc601669ae86cc056c93 ~* &* +@all
user testUser on nopass ~* &* +@all
```
Notice that testUser has `nopass` instead of the password that is in the secret.
Additionally, the hashed password for the default user does not match up compared to running `echo -n passwordHere| sha256sum`.

Even though I have set `image.debug=-true`, this is the generated log from the master:
```
1:C 15 Oct 2025 15:06:44.301 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 15 Oct 2025 15:06:44.301 * Redis version=8.2.1, bits=64, commit=00000000, modified=1, pid=1, just started
1:C 15 Oct 2025 15:06:44.301 * Configuration loaded
1:M 15 Oct 2025 15:06:44.302 * monotonic clock: POSIX clock_gettime
1:M 15 Oct 2025 15:06:44.303 * Running mode=standalone, port=6379.
1:M 15 Oct 2025 15:06:44.303 * Server initialized
1:M 15 Oct 2025 15:06:44.305 * Reading RDB base file on AOF loading...
1:M 15 Oct 2025 15:06:44.305 * Loading RDB produced by version 8.2.1
1:M 15 Oct 2025 15:06:44.305 * RDB age 475 seconds
1:M 15 Oct 2025 15:06:44.305 * RDB memory usage when created 0.62 Mb
1:M 15 Oct 2025 15:06:44.305 * RDB is base AOF
1:M 15 Oct 2025 15:06:44.305 * Done loading RDB, keys loaded: 0, keys expired: 0.
1:M 15 Oct 2025 15:06:44.305 * DB loaded from base file appendonly.aof.1.base.rdb: 0.002 seconds
1:M 15 Oct 2025 15:06:44.305 * DB loaded from append only file: 0.002 seconds
1:M 15 Oct 2025 15:06:44.310 * Opening AOF incr file appendonly.aof.1.incr.aof on server start
1:M 15 Oct 2025 15:06:44.310 * Ready to accept connections tcp
1:signal-handler (1760540844) Received SIGTERM scheduling shutdown...
1:M 15 Oct 2025 15:07:24.510 * User requested shutdown...
1:M 15 Oct 2025 15:07:24.510 * Calling fsync() on the AOF file.
1:M 15 Oct 2025 15:07:24.515 # Redis is now ready to exit, bye bye...
stream closed: EOF for redis/redis-test-master-0 (redis)
```

As expected, unfortunately, the deployment enters a crashloop.

<img width="2435" height="1153" alt="Image" src="https://github.com/user-attachments/assets/c9a506ea-f357-48ba-bd63-5389e9020c5c" />

Side note: I am not using sentinel, but I do not think that it would make a difference.

**Comment by jotamartos** [comment]
> I've encountered the issue where when the ACL is enabled and the redis password is set via existingSecret and existingSecretPasswordKey, the hash generated that ends up in the users.acl section of the redis-configuration ConfigMap does not match up with the hash that it should be.

> users.acl:
> ----
> user default on #6e7e68cedbc9227d0805ffb96474e4af6b76bd4f3761bc601669ae86cc056c93 ~* &* +@all
> user testUser on nopass ~* &* +@all

That checksum is the sha256 hash of the password. You can learn how that file is generated here:

https://github.com/bitnami/charts/blob/main/bitnami/redis/templates/configmap.yaml#L51

If you have any suggestions, please follow the [contribution guidelines](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

>@jotamartos Maybe there needs to be some tweaking in the way you are deploying your test case. I just tried again with a fresh deployment of redis and am still seeing the same issue.

Regarding the deployment issue, I deployed it with a simpler configuration and everything worked as expected 

```
global:
  security:
    allowInsecureImages: true
auth:
  existingSecret: "redis-acl"
  existingSecretPasswordKey: "user-test"
  acl:
    enabled: true
    users: 
      - username: "user-test"
        password: ""
        enabled: "on"
        commands: "+@all"
        keys: "~*"
        channels: "&*"
    userSecret: "redis-acl"
replica:
  replicaCount: 1
image:
  repository: bitnamilegacy/redis
kubectl:
  image:
    repository: bitnamilegacy/kubectl
```

```
apiVersion: v1
kind: Secret
metadata:
  name: redis-acl
type: Opaque
data:
  user-test: d1ErTWY4RXFGRw==
```

```
➜  redis git:(main) k get all 
Warning: Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
NAME                   READY   STATUS    RESTARTS   AGE
pod/redis-master-0     1/1     Running   0          55s
pod/redis-replicas-0   1/1     Running   0          54s

NAME                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/redis-headless   ClusterIP   None             <none>        6379/TCP   56s
service/redis-master     ClusterIP   240.226.73.216   <none>        6379/TCP   56s
service/redis-replicas   ClusterIP   240.226.79.56    <none>        6379/TCP   56s

NAME                              READY   AGE
statefulset.apps/redis-master     1/1     57s
statefulset.apps/redis-replicas   1/1     57s
```

I do not know if the storageclass you are using or your cluster needs to be changed somehow. Have you tried in a different environment?

**Comment by Nickmman** [comment]
@jotamartos The storage class is fine, the PVCs get created as intended. The deployment was fresh as well. 

The problem with the hashed password is that the sha256sum does not correspond to the hash of the password for the default user, which is what I believe is the root of the issue.

With ACL disabled:
```
I have no name!@redis-test-master-0:/$ cat /opt/bitnami/redis/secrets/redis-password ; echo
asdf1234
I have no name!@redis-test-master-0:/$ redis-cli --user default -a asdf1234
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
127.0.0.1:6379> ping
PONG
127.0.0.1:6379>
```
Relevant config:
```
auth:
  existingSecret: redis-test
  existingSecretPasswordKey: password
```

With ACL enabled (PVCs recreated to avoid any stale/conflicting data):
```
I have no name!@redis-test-master-0:/$ cat /opt/bitnami/redis/secrets/redis-password ; echo
asdf1234
I have no name!@redis-test-master-0:/$ redis-cli --user default -a asdf1234
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
AUTH failed: WRONGPASS invalid username-password pair or user is disabled.
127.0.0.1:6379> ping
(error) NOAUTH Authentication required.
127.0.0.1:6379>
```
Relevant config:
```
auth:
  acl:
    enabled: true
    userSecret: redis-custom-users
    users:
    - channels: '&*'
      commands: +@all
      enabled: "on"
      keys: ~*
      username: testUser
  existingSecret: redis-test
  existingSecretPasswordKey: password
```

Additionally, the generated hashed password for the default user (which has not changed) does not match up what it should be.

In the ConfigMap:
```
  users.acl: |-
    user default on #ff3cb817e442684a70fb9b03f5702eb150f66685125ac2d7a8988c93d1197f5f ~* &* +@all
```

Running sha256sum locally (omitting the starting # since we're just concerned about the actual sha256 hash):
```
echo -n "asdf1234" | sha256sum
312433c28349f63c4f387953ff337046e794bea0f9b9ebfcb08e90046ded9c76  -
```

This is a problem because the health check uses the default user (no user is explicitly specified).
Would this mean that when ACL is enabled, the default user can no longer be used for the health check?

**Comment by jotamartos** [comment]
As you have not shared your redis-test secret, I can't review your data but I can confirm that everything works on my side. Using these custom values 

```
global:
  security:
    allowInsecureImages: true
auth:
  existingSecret: "redis-acl"
  existingSecretPasswordKey: "adminUser"
  acl:
    enabled: true
    users: 
      - username: "adminUser"
        password: ""
        enabled: "on"
        commands: "+@all"
        keys: "~*"
        channels: "&*"
      - username: "testUser"
        password: ""
        enabled: "on"
        commands: "+@all"
        keys: "~*"
        channels: "&*"
    userSecret: "redis-acl"
replica:
  replicaCount: 1
image:
  repository: bitnamilegacy/redis
kubectl:
  image:
    repository: bitnamilegacy/kubectl
```

```
➜  redis git:(main) echo -n "bitnami1" | base64
Yml0bmFtaTE=
➜  redis git:(main) echo -n "bitnami2" | base64
Yml0bmFtaTI=
➜  redis git:(main) k create secret generic redis-acl --from-literal=adminUser=bitnami1 --from-literal=testUser=bitnami2
secret/redis-acl created
➜  redis git:(main) echo -n "bitnami1" | sha256sum 
e0b05f04503d90db2b85a2d3f50246100f6086fc842eee61125d3dd7462e0208  -
➜  redis git:(main) echo -n "bitnami2" | sha256sum
4f633ba2c857cb3621ca04e30d07385a6a3641b734034a6b584810a3901d1462  -
➜  redis git:(main) k get cm redis-configuration -o yaml
apiVersion: v1
data:
...
  users.acl: |-
    user default on #e0b05f04503d90db2b85a2d3f50246100f6086fc842eee61125d3dd7462e0208 ~* &* +@all
    user adminUser on #e0b05f04503d90db2b85a2d3f50246100f6086fc842eee61125d3dd7462e0208 ~* &* +@all
    user testUser on #4f633ba2c857cb3621ca04e30d07385a6a3641b734034a6b584810a3901d1462 ~* &* +@all
kind: ConfigMap
...
➜  redis git:(main) k exec -it pod/redis-master-0 -- cat /opt/bitnami/redis/secrets/redis-password
bitnami1
```

**Comment by Nickmman** [comment]
@jotamartos My bad for not sharing the secret. With your test above, did you deploy redis manually via helm or via an ArgoCD application deployment?

**Comment by jotamartos** [comment]
It was a manual deployment.

**Comment by Nickmman** [comment]
@jotamartos I think that's where the problem lies, it will work on a manual deployment but not when deployed via ArgoCD.

What comes to mind is to build the configuration file somehow that can read the secret properly and then populate the config file, possibly via a kubectl job or something similar. It sounds a bit of a hack though, what are your thoughts?

**Comment by jotamartos** [comment]
This issue seems to be related with how the lookup function works

https://github.com/argoproj/argo-cd/issues/5202

As an alternative, you can set the passwords to use in the custom values instead of using the secret

```
auth:
...
  acl:
    enabled: true
    users: 
      - username: "adminUser"
        password: "bitnami1"
        enabled: "on"
        commands: "+@all"
        keys: "~*"
        channels: "&*"
      - username: "testUser"
        password: "bitnami2"
        enabled: "on"
        commands: "+@all"
        keys: "~*"
        channels: "&*"
replica:
  replicaCount: 1
...
```

**Comment by Nickmman** [comment]
Hi @jotamartos, I don't think that putting plain-text passwords in a file is ever a good idea, especially when using GitOps. If it was a local, manually applied manifest/values file, then I can understand. But checking in credentials to a git repo is never a good idea.

I've been thinking about a way to possibly get around this and the only thing that comes to mind is to create a job that leverages kubectl to obtain the secret and then populate the file with the credentials. By doing this, it will skip generating the file from the template, as it is currently set to do, and instead rely on that job. Obviously it would have to be through some flags/conditionals, so that only one or the other happens.

**Comment by Nickmman** [comment]
Hi @jotamartos, tagging you to check on your thoughts and keep the issue fresh.

**Comment by jotamartos** [comment]
Sorry for the delay here @Nickmman, I lost track of the ticket. As an alternative, you can use the *.extraVolume and *.extraVolumeMounts parameters to mount your users.acl file. You simply need to mount the file at "/opt/bitnami/redis/mounted-etc/users.acl" as described in the container's README

https://github.com/bitnami/containers/tree/main/bitnami/redis#enabling-access-control-list

You do not need to set the REDIS_ACLFILE in this case as it'll be copied to the /opt/bitnami/redis/etc folder 

https://github.com/bitnami/charts/blob/main/bitnami/redis/templates/scripts-configmap.yaml#L849

**Comment by Nickmman** [comment]
@jotamartos Thanks for the suggestion, I will test it out when I get a chance, haven't been able to do so due to the holiday season. Commenting to keep this open.
