### ISSUE TITLE
[bitnami/odoo] bn_odoo postgresql user name

### ISSUE THREAD

**Issue by ruddy32** [bitnami/charts#3817]
**Which chart**:
Odoo 14.0.20

**Describe the bug**
Restarting Odoo pod failed with message :
`psycopg2.OperationalError: FATAL:  password authentication failed for user "bn_odoo"`

**To Reproduce**
1. Deploy Odoo
2. Delete pod Odoo
3. See error

**Expected behavior**
Odoo server should be configured with postgres instead of bn_odoo (odoo-server.conf) 

**Version of Helm and Kubernetes**: 

- Output of `helm version`:

```
3.3.4
```

- Output of `kubectl version`:

```
1.19.2
```

**Additional context**
minikube 1.13.1

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue. I deployed the chart with the default values, deleted the pod and then it worked without issues:

```
NAME                        READY   STATUS    RESTARTS   AGE
odootest-6f64d9bdbb-lvmdb   1/1     Running   0          60s
odootest-postgresql-0       1/1     Running   0          3m39s
```

**Comment by ruddy32** [comment]
Odoo persistence was set to false. Using true works better.
I don't understand because the configuration file still the same.

Odoo is using 'odoo-server.conf' file or environment variable DB_USER.
DB_USER is not defined on the pod and 'odoo-server.conf' file is defining 'bn_odoo' postgres user.
PostgreSQL pod is defined with postgres user.
I understand that 'odoo-server.conf' is update when Odoo started, right ?

**Comment by ruddy32** [comment]
Using persistence: false, the first odoo pod restart show message and then stop:
`Error executing 'postInstallation': User bn_odoo already exists` 
Does post installation process is a nami specific feature?

**Comment by javsalgar** [comment]
Hi,

This is a special case where the odoo pod does not have persistence but the database has. Could you explain the use case for the lack of persistence only in Odoo?

**Comment by ruddy32** [comment]
I was just testing different configuration. I understand that odoo and postgres need to be setup with the same persistence flag.
Thanks for your support.
