### ISSUE TITLE
Error: UPGRADE FAILED: YAML parse error on kibana/templates/deployment.yaml: error converting YAML to JSON: yaml: line 41: could not find expected ':'

### ISSUE THREAD

**Issue by shankyup43** [bitnami/charts#3912]
**Description**

Trying to run:
```
helm install kibana-1 bitnami/kibana --set service.type=NodePort,service.nodePort=30015,elasticsearch.hosts[0]=elasticsearch-1-elasticsearch-coordinating-only.monitor.svc.cluster.local,elasticsearch.port=9200,volumePermissions.enabled=true -n monitor
```
**Steps to reproduce the issue:**

1. CIFS mount on ubuntu 18.04
2. Persistent folder with 777 permission
3. Tried `helm install kibana-1 bitnami/kibana --set service.type=NodePort,service.nodePort=30015,elasticsearch.hosts[0]=elasticsearch-1-elasticsearch-coordinating-only.monitor.svc.cluster.local,elasticsearch.port=9200,volumePermissions.enabled=true -n monitor` but received below error in pod log:
```
nami    INFO  Initializing kibana
Error executing 'postInstallation': EPERM: operation not permitted, utime '/bitnami/kibana/.restored'
```
4. Followed chart documentation and tried: 
```
helm install kibana-1 bitnami/kibana --set service.type=NodePort,service.nodePort=30015,elasticsearch.hosts[0]=elasticsearch-1-elasticsearch-coordinating-only.monitor.svc.cluster.local,elasticsearch.port=9200,volumePermissions.enabled=true -n monitor
```
**Describe the results you received:**
```
Error: UPGRADE FAILED: YAML parse error on kibana/templates/deployment.yaml: error converting YAML to JSON: yaml: line 41: could not find expected ':'
```
**Describe the results you expected:**

container spins up.
**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Docker version 19.03.13, build 4484c46d9d
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 19
  Running: 16
  Paused: 0
  Stopped: 3
 Images: 9
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-118-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 23.5GiB
 Name: uat-master.<domain>.com
 ID: N4CX:THN4:W7NN:RTMB:5KRH:SZVI:7QRD:OPYQ:IJ6T:4EG5:7PF6:ZKKR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Kubeadm, kubectl and kubelet version:

```
kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:54:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Kubernetes v1.18.9

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:56:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
VM on Hyper-V

**Comment by carrodher** [comment]
Hi, thanks for reporting this issue, it seems a typo introduced in #3702, I was able to reproduce the issue using the `5.3.11` version but not with the previous one `5.3.10`:

```console
$ helm template kibana-1 bitnami/kibana --version 5.3.11 --set service.type=NodePort,service.nodePort=30015,elasticsearch.hosts[0]=elasticsearch-1-elasticsearch-coordinating-only.monitor.svc.cluster.local,elasticsearch.port=9200,volumePermissions.enabled=true
Error: YAML parse error on kibana/templates/deployment.yaml: error converting YAML to JSON: yaml: line 41: could not find expected ':'

$ echo $?
1

$ helm template kibana-1 bitnami/kibana --version 5.3.10 --set service.type=NodePort,service.nodePort=30015,elasticsearch.hosts[0]=elasticsearch-1-elasticsearch-coordinating-only.monitor.svc.cluster.local,elasticsearch.port=9200,volumePermissions.enabled=true
# Source: kibana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-1-conf
...

$ echo $?
0
```

If you are in hurry, you can install the chart by setting `--version 5.3.10`, you shouldn't find any issues in that version. Also please, remember to remove the existing PVCs/PVs to avoid any weird issue, just in case.

Apart from that, I just created the above PR that appears attached to this issue fixing the typo, once reviewed and validated in our internal CI/CD a new chart version should be released so you can't skip setting the `--version` flag.

**Comment by shankyup43** [comment]
Thanks carrodher. I tried below command:

helm install kibana-1 --version 5.3.10 bitnami/kibana --set service.type=NodePort,service.nodePort=30015,elasticsearch.hosts[0]=elasticsearch-1-elasticsearch-coordinating-only.monitor.svc.cluster.local,elasticsearch.port=9200,volumePermissions.enabled=true -n monitor

but its giving me below error:

nami    INFO  Initializing kibana
Error executing 'postInstallation': EPERM: operation not permitted, utime '/bitnami/kibana/.restored'

I have 777 as permission on pv directory.

**Comment by carrodher** [comment]
I don't think this is related to permissions but something present from a previous (maybe wrong/corrupted deployment), can you remove the PVC and try again from scratch?

**Comment by carrodher** [comment]
The issue was closed because the attached PR was merged. Please, take into account once the PR with the fix is merged in GitHub, we need to trigger our internal test & release pipeline if the tests work as expected, the new version of the Kibana chart should appear in the Helm repository after some time.

Once the new version in the repository you can use it after execute `helm repo update` and you shouldn't need to add the `--version` flag to the `helm install` command. Feel free to reopen this issue if the new version doesn't solve the issue or the `'/bitnami/kibana/.restored'` issue is still present even removing the PV/PVC

**Comment by shankyup43** [comment]
I removed pvc, pv and all the files including .restored for kibana. I have also removed the entire directory and re-created it but I am still getting this error:
nami    INFO  Initializing kibana
Error executing 'postInstallation': EPERM: operation not permitted, utime '/bitnami/kibana/.restored'

I used the latest chart after doing "helm repo update".

**Comment by carrodher** [comment]
I am not able to reproduce the issue, those are the steps I followed:
- Install Elasticsearch
```console
$ helm install elastic bitnami/elasticsearch
NAME: elastic
LAST DEPLOYED: Tue Oct 13 12:32:37 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
-------------------------------------------------------------------------------
 WARNING

    Elasticsearch requires some changes in the kernel of the host machine to
    work as expected. If those values are not set in the underlying operating
    system, the ES containers fail to boot with ERROR messages.

    More information about these requirements can be found in the links below:

      https://www.elastic.co/guide/en/elasticsearch/reference/current/file-descriptors.html
      https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html

    This chart uses a privileged initContainer to change those settings in the Kernel
    by running: sysctl -w vm.max_map_count=262144 && sysctl -w fs.file-max=65536

** Please be patient while the chart is being deployed **

  Elasticsearch can be accessed within the cluster on port 9200 at elastic-elasticsearch-coordinating-only.default.svc.cluster.local

  To access from outside the cluster execute the following commands:

    kubectl port-forward --namespace default svc/elastic-elasticsearch-coordinating-only 9200:9200 &
    curl http://127.0.0.1:9200/
```

- Install Kibana:
```console
$ helm install kibana bitnami/kibana --set elasticsearch.hosts[0]=elastic-elasticsearch-coordinating-only.default.svc.cluster.local --set elasticsearch.port=9200 --set volumePermissions.enabled=true
NAME: kibana
LAST DEPLOYED: Tue Oct 13 12:36:06 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=kibana,app.kubernetes.io/instance=kibana" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward svc/kibana399 8080:5601
```
- Check the pods:
```console
$ kubectl get pods
NAME                                                       READY   STATUS    RESTARTS   AGE
elastic-elasticsearch-coordinating-only-7496cfd57b-6jmcs   1/1     Running   0          8m5s
elastic-elasticsearch-coordinating-only-7496cfd57b-972cb   1/1     Running   0          8m5s
elastic-elasticsearch-data-0                               1/1     Running   0          8m5s
elastic-elasticsearch-data-1                               1/1     Running   0          8m5s
elastic-elasticsearch-master-0                             1/1     Running   0          8m5s
elastic-elasticsearch-master-1                             1/1     Running   0          8m5s
kibana-6bbff798d7-58qb2                                    1/1     Running   0          4m36s
```

Are you able to reproduce those steps? I am using a fresh deployment (no previous PV, PVC, etc)

**Comment by shankyup43** [comment]
The issue seems to be with PV. I had defined path for PV to a CIFS mounted folder. When I switched to NFS mounted folder, it worked.
It wasn't working even though I had 777 set as permissions for PV folder(CIFS mounted).

**Comment by carrodher** [comment]
I am glad you are not facing the issue at this moment, let's see how it works with the new method used for volumes

**Comment by jienckebd** [comment]
Was also getting this error on a new GKE cluster when trying to install your awesome work using this helmfile:

```
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: elasticsearch
    namespace: gitlab-managed-apps
    chart: bitnami/elasticsearch
    installed: true
    values:
      - values.yaml
``` 

Error stopped after changing to chart version 16.0.2 from the default latest (17.0.0):

```
releases:
  - name: elasticsearch
    namespace: gitlab-managed-apps
    chart: bitnami/elasticsearch
    version: 16.0.2
    installed: true
    values:
      - values.yaml
```

Thank you so much for your good work at Bitnami! I'm learning so much from it.

**Comment by carrodher** [comment]
Please note the issue described in this thread is mainly related to upgrades, in your case, it seems you're trying to install the chart from scratch, right?

In that case (installing the chart from scratch) you shouldn't find any issue, can you share here if you're using any custom parameters and also the error you are facing?

**Comment by jienckebd** [comment]
Hi Carlos -- thanks for your time. Wasn't using any custom parameters. But no longer facing an error here.
