### ISSUE TITLE
Using wildcards in Wordpress ingress configuration: YAML parse error on wordpress/templates/ingress.yaml

### ISSUE THREAD

**Issue by floek** [bitnami/charts#4839]
**Which chart**:
wordpress 10.1.5

**Describe the bug**
When I add a wildcard entry like "*.domain.tld" to ingress.extraHosts I get the following error:
```
Error: UPGRADE FAILED: YAML parse error on wordpress/templates/ingress.yaml: error converting YAML to JSON: yaml: line 21: did not find expected alphabetic or numeric character
```

**To Reproduce**

1. add a domain with a wildcard to  ingress.extraHosts

**Expected behavior**
I want to configure a subdomain multisite installation and need to use wildcard subdomains with cert_manager DNS validation.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:52:24Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
--

**Comment by alemorcuq** [comment]
Hi, @floek. Thanks for reporting this. I've created #4844, that should fix the issue.

**Comment by floek** [comment]
This issue is back. For me in chart version 10.4.4, butI think it came back with 10.4.1 and merge request #4953
