### ISSUE TITLE
Bitnami Kafka: Couldn't find the expected Java Key Stores (JKS) files!

### ISSUE THREAD

**Issue by TsuyoshiUshio** [bitnami/charts#4947]
**Which chart**:
kafka-12.5.0

**Describe the bug**
I install kafka using following command. 

```bash
$ kubectl create secret generic kafka-jks --from-file=./kafka.truststore.jks --from-file=./kafka-0.keystore.jks

$ helm install my-release \
  --debug \
  --set externalAccess.enabled=true \
  --set externalAccess.service.type=LoadBalancer \
  --set externalAccess.service.port=9094 \
  --set externalAccess.autoDiscovery.enabled=true \
  --set serviceAccount.create=true \
  --set rbac.create=true \
  --set auth.clientProtocol=tls \
  --set auth.jksSecret=kafka-jks \
  --set auth.jksPassword=MY_PASSWORD \
bitnami/kafka
```

However, the kafka broker pod says

```bash 
$ kubectl logs my-release-kafka-0
Couldn't find the expected Java Key Stores (JKS) files! They are mandatory when encryption via TLS is enabled.
```

The secret looks mounted on the pod. 

```
    - mountPath: /certs
      name: kafka-certificates
      readOnly: true
```

As I use Azure, I also try `azure-marketplace/kafka` however, it can't deploy at all that looks fail on init container. 

**To Reproduce**

I described it already.

**Expected behavior**

The broker started without saying the error message.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"afea77eefe3272c0f53c4552183ecb16c091db41", GitTreeState:"clean", BuildDate:"2020-09-17T06:32:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

I'm using AKS.  I try to enable SSL configuration for external access. It looks not available for now according to the other issue. It's ok for now. However, it looks, I might miss the configuration. Could you help me to solve this?

**Comment by marcosbc** [comment]
Hi @TsuyoshiUshio, unfortunately I could not reproduce this issue. When I deploy with the exact same options as you, the certs are created and the script succeeds (by copying them to the `/opt/bitnami/kafka/config/certs` directory).

```console
$ helm install my-kafka-release \
  --debug \
  --set externalAccess.enabled=true \
  --set externalAccess.service.type=LoadBalancer \
  --set externalAccess.service.port=9094 \
  --set externalAccess.autoDiscovery.enabled=true \
  --set serviceAccount.create=true \
  --set rbac.create=true \
  --set auth.clientProtocol=tls \
  --set auth.jksSecret=my-kafka-jks \
  --set auth.jksPassword=passwd321 \
bitnami/kafka
```

And to generate the secrets:

```console
$ kubectl create secret generic my-kafka-jks --from-file=./kafka.truststore.jks --from-file=./kafka-0.keystore.jks
```

I would recommend you to deploy with `--set 'command[0]=sleep,args[0]=infinity'`, then `kubectl exec -ti` into the pod and check that the `certs` directory is properly mounted. The you can try to run the `/scripts/setup.sh` script and see what happens, if it fails you will be in the containerized environment and be able to debug more.

**Comment by andrisdru** [comment]
Hi,

i can reproduce same issue on AKS but not with helm kafka clean intsall, error appears when doing helm update. Seems there is something wrong with /scripts/setup.sh , ID value is not assigned .

i manually added line  ID=${KAFKA_CFG_BROKER_ID} and issue dissapeared. Yes but this will not solve problem scripts-configmap.yaml should be fixed.

`	"setup.sh": "#!/bin/bash
	
		if [[ -f \"/bitnami/kafka/data/meta.properties\" ]]; then
		    export KAFKA_CFG_BROKER_ID=\"$(grep \"broker.id\" /bitnami/kafka/data/meta.properties | awk -F '=' '{print $2}')\"
		    ID=${KAFKA_CFG_BROKER_ID}
		else
		    ID=\"${MY_POD_NAME#\"kafka-\"}\"
		    export KAFKA_CFG_BROKER_ID=\"$((ID + 0))\"
		fi`

**Comment by marcosbc** [comment]
Hi @andrisdru, the ID value is determined from the node name so if it is named something like `myrelease-kafka-0` it will extract that 0 from it.

It wouldn't make much sense for this to be related to any upgrade due to that, as the node name would still follow the same format. In fact, I have just run an upgrade (same parameters as `helm install` except for the port, to force an upgrade) and I could not reproduce it.

If you could send some steps to reliable reproduce this issue on our side it would be helpful, including the full commands and all that.

**Comment by andrisdru** [comment]
nothing special with install from pipeline
```
helm init
helm repo add azure-marketplace https://marketplace.azurecr.io/helm/v1/repo
helm repo update
helm upgrade kafka azure-marketplace/kafka --install --namespace kafka --values values.yaml
```


this is complete auto generated setup.sh, but take a look if file /bitnami/kafka/data/meta.properties exsits, ID value is not assigned and script fails, ofc i dont know full picture of whole chart, but this is what i understand problem.

```
{
	"setup.sh": "#!/bin/bash
		
		if [[ -f \"/bitnami/kafka/data/meta.properties\" ]]; then
		    export KAFKA_CFG_BROKER_ID=\"$(grep \"broker.id\" /bitnami/kafka/data/meta.properties | awk -F '=' '{print $2}')\"
		else
		    ID=\"${MY_POD_NAME#\"kafka-\"}\"
		    export KAFKA_CFG_BROKER_ID=\"$((ID + 0))\"
		fi
		# Configure external ip and port
		export EXTERNAL_ACCESS_IP=$(echo '[10.86.194.168 10.86.194.169]' | tr -d '[]' | cut -d ' ' -f \"$(($ID + 1))\")
		export EXTERNAL_ACCESS_PORT=9094
		
		# Configure Kafka advertised listeners
		export KAFKA_CFG_ADVERTISED_LISTENERS=\"INTERNAL://${MY_POD_NAME}.kafka-headless.kafka.svc.cluster.local:9093,CLIENT://${MY_POD_NAME}.kafka-headless.kafka.svc.cluster.local:9092,EXTERNAL://${EXTERNAL_ACCESS_IP}:${EXTERNAL_ACCESS_PORT}\"
		if [[ -f \"/certs/kafka.truststore.jks\" ]] && [[ -f \"/certs/kafka-${ID}.keystore.jks\" ]]; then
		    mkdir -p /opt/bitnami/kafka/config/certs
		    cp \"/certs/kafka.truststore.jks\" \"/opt/bitnami/kafka/config/certs/kafka.truststore.jks\"
		    cp \"/certs/kafka-${ID}.keystore.jks\" \"/opt/bitnami/kafka/config/certs/kafka.keystore.jks\"
		else
		    echo \"Couldn't find the expected Java Key Stores (JKS) files! They are mandatory when encryption via TLS is enabled.\"
		    exit 1
		fi
		
		exec /entrypoint.sh /run.sh"
}
```

es workarund currently i created manually new setup1.sh script with ID assignment and edited also values.yml file.

**Comment by lturmel** [comment]
Have the same issue when I passed from Helm Chart 11.8.9 to 12.4.0... I don't try from 11.8.9 to 12.x.y version but I confirm that I've the same problem too

**Comment by marcosbc** [comment]
Hi @andrisdru, unfortunately we're still unable to reproduce it. Could you share some specific steps with all the info (i.e. values.yaml/--set options included) to reproduce it on our side?

@lturmel Not sure what may be happening on your side. If the PVC was mounted then /bitnami/kafka/data/meta.properties should exist. Are you able to reproduce this issue in a clean environment? (if so please share the steps)

**Comment by lturmel** [comment]
Hi @marcosbc, as @andrisdru said, the $ID variable is not set when passing through an upgrade scenario, this is what is causing the upgrade scenario. This was introduced by this commit on December 14, 2020 -> [](https://github.com/bitnami/charts/commit/f4eb7172411355ba3ebf164e05ecaa37dbb2f5c2#diff-d66da5348bd3175a782700e0f07824213afb6c787db21dab9b819171bb776ae2)

Has you can see in this image
![MicrosoftTeams-image](https://user-images.githubusercontent.com/46848645/104955379-2d02ee80-5998-11eb-97e8-41e6469d5220.png)

So the fix should be really simple...

**Comment by marcosbc** [comment]
Oh, I see now @lturmel. It looks like it should be as simple as replacing `ID` there with `KAFKA_CFG_BROKER_ID`. Would you be open to contributing this change via a PR? We'd be glad to review and help with the release.

**Comment by lturmel** [comment]
Thanks @marcosbc, I'm open to fix it, but I look the code, the PR and the #4626 issue, and that part with the "minBrokerId" seems not right at all.

The question is: How you expect the ID to be used. 
This #4626 Issue is a very tricky one that open the doors to a lot of confusion

I was expecting the usage of minBrokerId to also drive the Kafka Pod Name, but seems to not be the case at all.

The value of ID variable is take from the pod name like 'kafka-0' but the KAFKA_CFG_BROKER_ID stored into the meta.properties seems to intend to have the ID+.Values.minBrokerId, which is really confusing. Plus in upgrade scenario, we can't use that .Values.minBrokerId... to use it KafkaCluster will need to be created from scratch and without a PVC.

In all cases, from what I also see, is the fact that anyone who using "Kafka-X.keystore.jks" should use it with the ID of the PodName instead ID+minBrokerId. In the moment, anyone who already deploy it at it is, clearly use it with that format, even if their minBrokerId is somethings else from 0.

**Comment by marcosbc** [comment]
Thanks for all the details and for the PR! I agree it might be a bit confusing, although at least now we have something that works with the mentioned scenarios. We can continuing improving on this later on.

I'm assuming this issue should be fixed once the chart with #4683 is released, which hopefully will happen later today, so I'm proceeding to close this issue.

**Comment by arasic** [comment]
Re-opening the ticket as the problem persists.

I spent considerable amount of time trying to make this work.

I relied on the following link:
https://docs.bitnami.com/kubernetes/infrastructure/kafka/administration/enable-tls/#use-jks-format
and many more similar to this one.

Basically, what I am trying to achieve is to use my own generated keystore/truststore JKS.

Can someone please confirm that following the documentation from: https://docs.bitnami.com/kubernetes/infrastructure/kafka/administration/enable-tls/#use-jks-format do actually work?

Thanks.


Here are the steps I followed:

Used the script, https://raw.githubusercontent.com/confluentinc/confluent-platform-security-tools/master/kafka-generate-ssl.sh to generate truststore and multiple keystores. I used identical password for each keystore (replicas of 3 -> 3 keystores).

```
kubectl create secret generic kafka-tls --from-file=./generated-certs/kafka.truststore.jks  --from-file=kafka-0.keystore.jks=./generated-certs/kafka.keystore-0.jks  --from-file=kafka-1.keystore.jks=./generated-certs/kafka.keystore-1.jks  --from-file=kafka-2.keystore.jks=./generated-certs/kafka.keystore-2.jks
```

the yaml I am using
```
replicaCount: 3
auth:
  interBrokerProtocol: tls
  clientProtocol: tls
  tls:
    type: jks
    existingSecret: kafka-tls
    auth.tls.password: some-password
```


The error keeps appearing:

```
Error: template: kafka/templates/NOTES.txt:304:4: executing "kafka/templates/NOTES.txt" at <include "kafka.validateValues" .>: error calling include: template: kafka/templates/_helpers.tpl:363:51: executing "kafka.validateValues" at <fail>: error calling fail: 
VALUES VALIDATION:

kafka: auth.tls.existingSecrets
    A secret containing the Kafka JKS keystores and truststore is required
    when TLS encryption in enabled and TLS format is "JKS"
helm.go:81: [debug] template: kafka/templates/NOTES.txt:304:4: executing "kafka/templates/NOTES.txt" at <include "kafka.validateValues" .>: error calling include: template: kafka/templates/_helpers.tpl:363:51: executing "kafka.validateValues" at <fail>: error calling fail: 
VALUES VALIDATION:

kafka: auth.tls.existingSecrets
    A secret containing the Kafka JKS keystores and truststore is required
    when TLS encryption in enabled and TLS format is "JKS"

```

Secret description
```
$ kubectl describe secret kafka-tls
Name:         kafka-tls
Namespace:    default
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
kafka-0.keystore.jks:  5471 bytes
kafka-1.keystore.jks:  5471 bytes
kafka-2.keystore.jks:  5471 bytes
kafka.truststore.jks:  1447 bytes
```

I also tried by creating multiple secrets, kafka-tls-0, kafka-tls-1, kafka-tls-2 with kafka.truststore.jks and kafka.keystore.jks pairs but I did not work either, same error.

What worked was to use the option `autoGenerated: true`.

Thanks.

**Comment by arasic** [comment]
> Re-opening the ticket as the problem persists.
> 
> I spent considerable amount of time trying to make this work.
> 
> I relied on the following link: https://docs.bitnami.com/kubernetes/infrastructure/kafka/administration/enable-tls/#use-jks-format and many more similar to this one.
> 
> Basically, what I am trying to achieve is to use my own generated keystore/truststore JKS.
> 
> Can someone please confirm that following the documentation from: https://docs.bitnami.com/kubernetes/infrastructure/kafka/administration/enable-tls/#use-jks-format do actually work?
> 
> Thanks.
> 
> Here are the steps I followed:
> 
> Used the script, https://raw.githubusercontent.com/confluentinc/confluent-platform-security-tools/master/kafka-generate-ssl.sh to generate truststore and multiple keystores. I used identical password for each keystore (replicas of 3 -> 3 keystores).
> 
> ```
> kubectl create secret generic kafka-tls --from-file=./generated-certs/kafka.truststore.jks  --from-file=kafka-0.keystore.jks=./generated-certs/kafka.keystore-0.jks  --from-file=kafka-1.keystore.jks=./generated-certs/kafka.keystore-1.jks  --from-file=kafka-2.keystore.jks=./generated-certs/kafka.keystore-2.jks
> ```
> 
> the yaml I am using
> 
> ```
> replicaCount: 3
> auth:
>   interBrokerProtocol: tls
>   clientProtocol: tls
>   tls:
>     type: jks
>     existingSecret: kafka-tls
>     auth.tls.password: some-password
> ```
> 
> The error keeps appearing:
> 
> ```
> Error: template: kafka/templates/NOTES.txt:304:4: executing "kafka/templates/NOTES.txt" at <include "kafka.validateValues" .>: error calling include: template: kafka/templates/_helpers.tpl:363:51: executing "kafka.validateValues" at <fail>: error calling fail: 
> VALUES VALIDATION:
> 
> kafka: auth.tls.existingSecrets
>     A secret containing the Kafka JKS keystores and truststore is required
>     when TLS encryption in enabled and TLS format is "JKS"
> helm.go:81: [debug] template: kafka/templates/NOTES.txt:304:4: executing "kafka/templates/NOTES.txt" at <include "kafka.validateValues" .>: error calling include: template: kafka/templates/_helpers.tpl:363:51: executing "kafka.validateValues" at <fail>: error calling fail: 
> VALUES VALIDATION:
> 
> kafka: auth.tls.existingSecrets
>     A secret containing the Kafka JKS keystores and truststore is required
>     when TLS encryption in enabled and TLS format is "JKS"
> ```
> 
> Secret description
> 
> ```
> $ kubectl describe secret kafka-tls
> Name:         kafka-tls
> Namespace:    default
> Labels:       <none>
> Annotations:  <none>
> 
> Type:  Opaque
> 
> Data
> ====
> kafka-0.keystore.jks:  5471 bytes
> kafka-1.keystore.jks:  5471 bytes
> kafka-2.keystore.jks:  5471 bytes
> kafka.truststore.jks:  1447 bytes
> ```
> 
> I also tried by creating multiple secrets, kafka-tls-0, kafka-tls-1, kafka-tls-2 with kafka.truststore.jks and kafka.keystore.jks pairs but I did not work either, same error.
> 
> What worked was to use the option `autoGenerated: true`.
> 
> Thanks.

Figured it out...finally.

1. The documentation from the official site is misleading, https://docs.bitnami.com/kubernetes/infrastructure/kafka/administration/enable-tls/#use-jks-format:

```
kubectl create secret generic kafka-tls --from-file=./kafka.truststore.jks --from-file=./kafka-0.keystore.jks --from-file=./kafka-1.keystore.jks
```


2. I tried the following configs from https://github.com/bitnami/charts/issues/8593, but it did not work:

```
auth:
  interBrokerProtocol: tls
  clientProtocol: tls
  tls:
    type: jks
    existingSecrets[0]: kafka-tls-0
    existingSecrets[1]: kafka-tls-1
    existingSecrets[2]: kafka-tls-2
    password: some-password
```

3. Solution: what worked was the example from here: https://github.com/bitnami/charts/issues/9607
Which does make sense because that's what is explained in the documentation, https://artifacthub.io/packages/helm/bitnami/kafka.

auth.tls.existingSecrets | Array existing secrets containing the TLS certificates for the Kafka brokers | with brackets, [] to indicate an array.

4. What I suggest is simply to update the documentation with following example:
```
kubectl create secret generic kafka-tls-0 --from-file=kafka.truststore.jks=./generated-certs/kafka.truststore.jks --from-file=kafka.keystore.jks=./generated-certs/kafka.keystore-0.jks
kubectl create secret generic kafka-tls-1 --from-file=kafka.truststore.jks=./generated-certs/kafka.truststore.jks --from-file=kafka.keystore.jks=./generated-certs/kafka.keystore-1.jks
kubectl create secret generic kafka-tls-2 --from-file=kafka.truststore.jks=./generated-certs/kafka.truststore.jks --from-file=kafka.keystore.jks=./generated-certs/kafka.keystore-2.jks
```
Then, in the config, use:
```
auth:
  interBrokerProtocol: tls
  clientProtocol: tls
  tls:
    type: jks
    existingSecrets: ["kafka-tls-0", "kafka-tls-1", "kafka-tls-2"]
    password: some-password
metrics:
```

**Comment by javsalgar** [comment]
Hi,

Thank you so much for spotting the issue in our documentation. This is the page with the documentation: https://github.com/bitnami/charts-docs/blob/main/charts/kafka/_enable_tls.md.erb

Would you like to update it with a PR?

**Comment by arasic** [comment]
Certainly, I will do it today, but it will need someone else for a review&validation.

Thanks!

**Comment by javsalgar** [comment]
Just ping us and we will review it

**Comment by arasic** [comment]
Sure,

Here it is: https://github.com/bitnami/charts-docs/pull/111

Sorry Javier, I did not keep my promise last Friday, but it's ready for a
review now.

Who's information do we put in Signed-off-by: ?

Thanks!

**Comment by arasic** [comment]
I'' re-open a new one that will be signed-off correctly.

**Comment by javsalgar** [comment]
Thanks! For the signed-off part you can commit using the `--signoff` flag
