### ISSUE TITLE
When Load-definitions config is used in values file rabbitmq-password is nowhere to be found in the secrets created

### ISSUE THREAD

**Issue by Eugenevml** [bitnami/charts#5976]
**Which chart**:
rabbitmq (latest version)

**Describe the bug**
When deploying latest rabbitmq chart using load definitions as described in the manual the first secret gets deployed only containing Erlang cookie and user password to access RabbitMQ Management Console is nowhere to be found. 

This is what my values file contains (as suggested in the part of the manual that speaks about load-definitions): 
```yaml
auth:
  password: CHANGEME
extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "users": [
          {
            "name": "{{ .Values.auth.username }}",
            "password": "{{ .Values.auth.password }}",
            "tags": "administrator"
          }
        ],
        "vhosts": [
          {
            "name": "/"
          }
        ]
      }
loadDefinition:
  enabled: true
  existingSecret: load-definition
extraConfiguration: |
  load_definitions = /app/load_definition.json
```
I deploy it via Jenkins using the following configs. Main part of the Jenkins config below: 

```
 RELEASE_NAME = 'rabbitmq-test'
      }
      steps {
        sh "mkdir -p ${HELM_HOME}"
        sh "mkdir -p ${XDG_CACHE_HOME}"
        sh "mkdir -p ${XDG_CONFIG_HOME}"
        sh "mkdir -p ${XDG_DATA_HOME}"

        sh "helm repo add bitnami https://charts.bitnami.com/bitnami"
        sh "helm repo update"

        sh "kubectl config set-cluster staging --server=${CLUSTER_IP}"
        sh "kubectl config set-credentials jenkins --token=${JENKINS_TOKEN}"
        sh "kubectl config set clusters.staging.certificate-authority-data ${KUBERNETES_CA}"
        sh "kubectl config set-context jenkins@staging --cluster=staging --user=jenkins"
        sh "kubectl config use-context jenkins@staging"

        sh """helm upgrade ${env.RELEASE_NAME} bitnami/rabbitmq \
          --install \
          --kubeconfig ${KUBECONFIG} \
          --namespace ${env.NAMESPACE} \
          --values rabbitmq/values.bitnami-rabbitmq.stg.yaml \
          --set rabbitmqErlangCookie=${ERLANG_COOKIE} \
          --wait"""
      }
    }
```

values.bitnami-rabbitmq.stg.yaml  only contains load-definition config stated above. 
I realize that load-definition secret takes precedence over any configuration done through Helm values. But please explain how to access management console now. 

**Expected behavior**

My goal is to template via values file a number of users, policies, vhosts and permissions and make them deployable on each upgrade to the rabbitmq instance. This is working very well in rabbitmq-ha (deprecated chart). At the same time I need to have an option to access management console. I tried putting administrator user in the load-definitions but this doesn't seem to work as I can't query the password from there as follows: 
kubectl get secret --namespace rabbitmq load-definition -o jsonpath="{.data.rabbitmq-password}" | base64 --decode -o yaml

When chart is deployed without that load-definitions config secret rabbitmq-test gets created containing rabbitmq-password that can be decoded and used to access management console. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-02T11:40:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.7800", GitCommit:"cef3156c566a1d1a4b23ee360a760f45bfbaaac1", GitTreeState:"clean", BuildDate:"2020-12-14T09:12:37Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by javsalgar** [comment]
Hi,

Could you check using the CLI that the user credentials and tags for accessing the UI are correctly set with your definition? Just to confirm if the definition is consumed correctly. We disabled the creation of the password secret when using definitions because it caused conflicts, you can see here more context https://github.com/bitnami/charts/pull/5939

**Comment by Eugenevml** [comment]
Hi 
Thank you for your response. Are you saying that user credentials and tags for accessing the UI should be set within the helm command when installing / updating helm chart in CLI? Just wanted to clarify. Thanks for assisting me with this matter

**Comment by javsalgar** [comment]
If I'm not mistaken, as you are using definitions, it should be set in the definitions. What I was asking is if you could confirm that the user was created using the rabbitmq CLI.

Example:

```
I have no name!@rb-rabbitmq-0:/$ rabbitmqctl authenticate_user user
Authenticating user "user" ...
Password:
73elj8hB2c
Success
```

**Comment by chukka** [comment]
@javsalgar @andresbono Looks like we are running into same issue .We are planning to upgrade rabbitmq chart from `7.7.1` to `8.11.5`. we used below configuration in 7.7.1 chart  

 ```
 extraSecrets:
    load-definition:
      load_definition.json: |
        { 
          "vhosts": [
            {
              "name": "/"
            }
          ],
          "policies": [
            {
              "name": "ha-all",
              "apply-to": "all",
              "pattern": ".*",
              "vhost": "/",
              "definition": {
                "ha-mode": "all",
                "ha-sync-mode": "automatic",
              }
            }
          ]
        }
  loadDefinition:
    enabled: true
    existingSecret: load-definition
  extraConfiguration: |
    load_definitions = /app/load_definition.json
```
Looking at recent changes in this PR https://github.com/bitnami/charts/pull/5939. If we set `.Values.loadDefinition.enabled` to `true`, we can't set env variable`RABBITMQ_PASSWORD` as `rabbitmq.secretPasswordName`  won't be generated. This will  break our upgrade scenarios . Can you please suggest a way to get around this .

**Comment by javsalgar** [comment]
Hi,

If you already have the secret, you could copy it and provide it to the chart so it doesn't re-generate it. Would it work for your case?

**Comment by chukka** [comment]
Hi @javsalgar 

It will not work , we set/use default rabbitmq's auth.password as empty  and expects chart to generate value for us.

Hope it helps.

**Comment by javsalgar** [comment]
In this case, you would need to set the user and password in the definitions. More context here https://github.com/bitnami/charts/issues/4222#issuecomment-759336389

**Comment by chukka** [comment]
@javsalgar Using  below user/password in load definitions , will not help our use case as we would like our customers  to use password as securely using Kubernetes secrets.

```
{
        "users": [
          {
            "name": "{{ .Values.auth.username }}",
            "password": "{{ .Values.auth.password }}",
            "tags": "administrator"
          }
        ]
}
```

Also, we set default password for [rabbitmq](https://github.com/jfrog/charts/blob/master/stable/xray/values.yaml#L285) as empty so that rabbitmq chart generates random password and thereby creates a secret out of it . I think this is a secured way of dealing with passwords.This is case with 7.x.x  and < 8.11.5 chart versions of rabbitmq.

**Comment by javsalgar** [comment]
The issues is that we found incompatibilities when using load definitions and using the chart password values. Several issues were reported by users about losing the password on restarts. 

Looking at the official documentation, when loading definitions, it won't create the default vhost and user 

> The definitions in the file will not overwrite anything already in the broker. However, if a blank (uninitialised) node imports a definition file, it will not create the default virtual host and user.

https://www.rabbitmq.com/definitions.html#import-on-boot

As an alternative at the moment, you could add something like this

```
{
        "users": [
          {
            "name": "{{ .Values.auth.username }}",
            "password": "{{ randAlphaNum 10 }}",
            "tags": "administrator"
          }
        ]
}
```

This definition goes inside a secret. Then you could decode it using `kubectl get secret` and obtain the generated password. Would that work for you?

**Comment by chukka** [comment]
> The issues is that we found incompatibilities when using load definitions and using the chart password values. Several issues were reported by users about losing the password on restarts. 

we had similar issue during restarts but this may be due to bug in the [chart](https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/values.yaml#L205) using default password and setting different password in values.yaml .

However, your suggested  solution may not work for  user provided password  scenario (providing password instead of default  empty value) , Can't we allow users to pass password via values.yaml file and not allow user's json via definitions. That way customers can still use secure passwords via k8s secrets.

**Comment by chukka** [comment]
FYI - This is the current values.yaml file we use 
```
auth:
    username: guest
    password: ""
..
  ## Load Definitions - https://www.rabbitmq.com/management.html#load-definitions
  # ref : https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#load-definitions
  extraSecrets:
    load-definition:
      load_definition.json: |
        {
          "vhosts": [
            {
              "name": "/"
            }
          ],
          "policies": [
            {
              "name": "ha-all",
              "apply-to": "all",
              "pattern": ".*",
              "vhost": "/",
              "definition": {
                "ha-mode": "all",
                "ha-sync-mode": "automatic",
              }
            }
          ]
        }
  loadDefinition:
    enabled: true
    existingSecret: load-definition
  extraConfiguration: |
    management.load_definitions = /app/load_definition.json
```

**Comment by javsalgar** [comment]
Hi,

This would require further changes in the container to cover this use case. We would need to scan the definition for user entries and then see how we could create the host and user. This is not trivial so it will take us more time to implement the feature. If you want to speed up the process, feel free to provide a PR to our rabbitmq container https://github.com/bitnami/bitnami-docker-rabbitmq and we will review it.

**Comment by chukka** [comment]
@javsalgar Thanks, For now we are good, we are going with 8.11.4 chart  which doesn't have #5939 changes.

**Comment by nodesocket** [comment]
I think I am having this problem.

See https://github.com/bitnami/charts/issues/4222#issuecomment-834063568

**Comment by javsalgar** [comment]
Which version of the chart are you using? This should have been fixed, according to the feedback from several users. Could you confirm you are using the latest version of the chart?

**Comment by Frituurpanda** [comment]
@javsalgar I can confirm this issue still being present on `8.13.1`. Just like @chukka we are also staying on the older `8.11.4` chart as we can't move forward currently. I'd love to provide more details if required.

**Comment by nodesocket** [comment]
@javsalgar thanks for the reply. I am using version `8.11.9`. Using no `loadDefinition` and the username/password works. Cluster comes up fine. However, using a simple custom `loadDefinition` such as:

```
{
      "permissions": [
        {
          "configure": ".*",
          "read": ".*",
          "user": "johndoe",
          "vhost": "/",
          "write": ".*"
        },
        {
          "configure": ".*",
          "read": ".*",
          "user": "johndoe",
          "vhost": "maximus",
          "write": ".*"
        }
      ],
      "vhosts": [
        {
          "limits": [],
          "metadata": {
            "description": "Default virtual host",
            "tags": []
          },
          "name": "/"
        },
        {
          "limits": [],
          "metadata": {
            "description": "",
            "tags": []
          },
          "name": "maximus"
        }
      ]
    }
```

Causes authentication failed with incorrect password.

**Comment by javsalgar** [comment]
Hi,

I'm missing a `users` section in the definition, like in this comment

https://github.com/bitnami/charts/issues/5976#issuecomment-819342899

Could you try adding that?

**Comment by nodesocket** [comment]
It appears that when using a custom `load_definition.json` the default user/password specific in the Helm chart is NOT created as expected.

```
2021-05-11 00:23:53.399 [info] <0.659.0> Applying definitions from file at '/app/load_definition.json'
2021-05-11 00:23:53.399 [info] <0.659.0> Asked to import definitions. Acting user: rmq-internal
2021-05-11 00:23:53.400 [info] <0.659.0> Importing concurrently 2 vhosts...
2021-05-11 00:23:53.400 [info] <0.659.0> Importing concurrently 2 permissions...
2021-05-11 00:23:53.401 [warning] <0.654.0> Failed to set permissions for 'johndoe': the user does not exist
2021-05-11 00:23:53.401 [warning] <0.655.0> Failed to set permissions for 'johndoe': the user does not exist
````

**Comment by nodesocket** [comment]
@javsalgar that worked setting:

```
users": [
        {
          "name": "johndoe",
          "password": "supersecrethere",
          "tags": "administrator"
        }
      ],
```

In the `load_definition.json`. That's a bit counterintuitive, I wish the documentation made that a bit more clear that the username and password specified in the chart WILL NOT be created if you provide a custom load definition.

**Comment by javsalgar** [comment]
Hi,

I agree with that, currently we only have one note but it is not specific enough: https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#load-custom-definitions

> NOTE: Loading a definition will take precedence over any configuration done through Helm values.

Maybe extending that note saying that, for example, the username and password will not be created? I think that makes sense. Also in the NOTES.txt section we have this:

```
{{- if not .Values.loadDefinition.enabled }}
    echo "Username      : {{ .Values.auth.username }}"
    echo "Password      : $(kubectl get secret --namespace {{ .Release.Namespace }} {{ include "rabbitmq.secretPasswordName" . }} -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)"
{{- end }}
    echo "ErLang Cookie : $(kubectl get secret --namespace {{ .Release.Namespace }} {{ include "rabbitmq.secretErlangName" . }} -o jsonpath="{.data.rabbitmq-erlang-cookie}" | base64 --decode)"

```

Maybe we should add a note saying that the username and password must have been set in the definition. Do you think that would be enough?

**Comment by mpmatti** [comment]
Another annoying issue here is that the default guest user is configured as an administrator, if loadDefinition is in use. I guess the only way is to remove it manually...?

**Comment by javsalgar** [comment]
Hi,

In other charts we have the use of init scripts. With that, you could add extra bash code to be executed which, for example, would remove the `guest` user. Would that work for you?

**Comment by mpmatti** [comment]
Yes, that could be useful. Are you planning to provide the init script feature in rabbitmq chart as well?

**Comment by javsalgar** [comment]
Hi,

Yes, I will open a task for that. We will let you know when it is ready.

**Comment by cheskayang** [comment]
having the same issue. 
For now, we just create our own secret and use `existingErlangSecret` and `existingPasswordSecret` to bypass the issue.

**Comment by chukka** [comment]
@javsalgar just following up on this [comment](https://github.com/bitnami/charts/issues/5976#issuecomment-820204040) . 

As per https://github.com/bitnami/bitnami-docker-rabbitmq docs, Looks like  loadDefinition is not compatible with secure password . 

- RABBITMQ_LOAD_DEFINITIONS: Whether to load external RabbitMQ definitions. This is incompatible with setting the RabbitMQ password securely. Default: no.

We would like to update rabbitmq docker images to `3.9.x` and rabbitmq helm chart to `8.24.12` . Any workaround solution

**Comment by javsalgar** [comment]
I will forward this ticket to the engineering team to see if we can re-prioritize the init scripts support. As soon as there are news, I will update the ticket.

**Comment by chukka** [comment]
@javsalgar  is there any ETA on this  ? we are blocked on updating to latest version of rabbitmq using latest rabbitmq chart , I assume it effects most of the  customers

**Comment by javsalgar** [comment]
Hi,

I'm afraid this issue is not yet prioritized. As a workaround, it would be possible to override the default RabbitMQ command so any extra operations can be performed. Also, if you want to speed up the process, feel free to create a PR and we will take a look.

**Comment by amithins** [comment]
Thanks for taking this up @javsalgar, helps a lot. Tried out the new chart (8.31.2), [facing an issue with this](https://github.com/bitnami/charts/issues/9730).

**Comment by javsalgar** [comment]
Thanks for reporting! Let's continue the conversation there

**Comment by aoterolorenzo** [comment]
A new version of the chart is now giving support for init scripts! Thanks for all the feedback and @Eugenevml for taking the time to submit the issue!
