### ISSUE TITLE
[bitnami/mongodb] TLS with custom certificates fails PodInitializing

### ISSUE THREAD

**Issue by asenyaev** [bitnami/charts#6714]
I started minikube with the cluster version **v1.20.0**

Also added several lines for the `override.yaml` file: 
- defined an image tag
- enabled TLS
- added a certificate and a key

But mongo does not start. I see that all containers (mongodb and generate-tls-certs) were created and started, but pod is in an error status `Back-off restarting failed container`.

What I have added:
```
image:
  tag: 3.6.23

tls:
  enabled: true
  autoGenerated: false
  caCert: <my_certificate>
  caKey: <my_key>
```
The chart version: **10.19.0**

The image for mongodb: **3.6.23**

**Comment by marcosbc** [comment]
Hi @asenyaev, could you provide the logs for the failed container? That may allow us to understand what is happening.

In addition, note that a very usual issue when base64-encoding the certs/keys is to include the ending newline, so make sure you're not doing this beforehand, i.e.:

```console
$ echo bar | base64
YmFyCg==
$ echo -n bar | base64
YmFy
```

**Comment by asenyaev** [comment]
@marcosbc cert and key are in a good condition. 

Logs are here:
```
mongodb 13:14:18.14 
mongodb 13:14:18.15 Welcome to the Bitnami mongodb container
mongodb 13:14:18.15 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 13:14:18.15 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 13:14:18.15 
mongodb 13:14:18.15 INFO  ==> ** Starting MongoDB setup **
mongodb 13:14:18.17 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 13:14:18.18 INFO  ==> Initializing MongoDB...
mongodb 13:14:18.20 INFO  ==> Deploying MongoDB from scratch...
```
But the pod in `Error` and `CrashLoopBackOff` status.

Moreover, I have tried to deploy mongo without predefined image in `override.yaml`, what means that there is a tag for the image `4.4.6`. So, everything works fine in this configuration, cert/key were deployed and container in `Running` status. But I have to use the certain tag - `3.6.23`.

Are there any dependencies which I did not notice when deployed `3.6.23` version?

**Comment by asenyaev** [comment]
@marcosbc Yes, I deployed mongo with `image.debug=true` and there is a bit more logs:

```
mongodb 11:35:23.30 
mongodb 11:35:23.30 Welcome to the Bitnami mongodb container
mongodb 11:35:23.30 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 11:35:23.30 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 11:35:23.30 
mongodb 11:35:23.31 INFO  ==> ** Starting MongoDB setup **
mongodb 11:35:23.32 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 11:35:23.33 INFO  ==> Initializing MongoDB...
mongodb 11:35:23.34 INFO  ==> Deploying MongoDB from scratch...
mongodb 11:35:23.34 DEBUG ==> Starting MongoDB in background...
Error parsing command line: unrecognised option '--tlsMode=requireTLS'
try '/opt/bitnami/mongodb/bin/mongod --help' for more information
```
As I know, the deprecated version of helm chart for mongo had a field: `mode: requireSSL`. But in the latest chart, there is no the same option. Could it be the source of this problem?

**Comment by marcosbc** [comment]
Hi @asenyaev, thanks for checking. It seems like in MongoDB 3.6, TLS was still not supported so the parameter was named `--sslMode` with these possible options: `disabled|allowSSL|preferSSL|requireSSL`.

That means that the chart does not currently support 3.6 for SSL options. We are not testing for 3.6 either.

However, adding support for 3.6 might be as simple as updating the following files:

```
templates/arbiter/statefulset.yaml
174:              value: --tlsMode=requireTLS --tlsCertificateKeyFile=/certs/mongodb.pem --tlsCAFile=/certs/mongodb-ca-cert

templates/hidden/statefulset.yaml
272:              {{- $extraFlags = printf "%s %s" "--tlsMode=requireTLS --tlsCertificateKeyFile=/certs/mongodb.pem --tlsCAFile=/certs/mongodb-ca-cert" $extraFlags  }}

templates/standalone/dep-sts.yaml
218:              {{- $extraFlags = printf "%s %s" "--tlsMode=requireTLS --tlsCertificateKeyFile=/certs/mongodb.pem --tlsCAFile=/certs/mongodb-ca-cert" $extraFlags  }}

templates/replicaset/statefulset.yaml
277:              {{- $extraFlags = printf "%s %s" "--tlsMode=requireTLS --tlsCertificateKeyFile=/certs/mongodb.pem --tlsCAFile=/certs/mongodb-ca-cert" $extraFlags  }}
```

If you find it useful to run 3.6 on the chart, we are open for contributions, so feel free to send a PR! We'd be glad to help with the review and release cycles.

**Comment by asenyaev** [comment]
> Hi @asenyaev, thanks for checking. It seems like in MongoDB 3.6, TLS was still not supported so the parameter was named `--sslMode` with these possible options: `disabled|allowSSL|preferSSL|requireSSL`.
> 
> That means that the chart does not currently support 3.6 for SSL options. We are not testing for 3.6 either.
> 
> However, adding support for 3.6 might be as simple as updating the following files:
> 
> ```
> templates/arbiter/statefulset.yaml
> 174:              value: --tlsMode=requireTLS --tlsCertificateKeyFile=/certs/mongodb.pem --tlsCAFile=/certs/mongodb-ca-cert
> 
> templates/hidden/statefulset.yaml
> 272:              {{- $extraFlags = printf "%s %s" "--tlsMode=requireTLS --tlsCertificateKeyFile=/certs/mongodb.pem --tlsCAFile=/certs/mongodb-ca-cert" $extraFlags  }}
> 
> templates/standalone/dep-sts.yaml
> 218:              {{- $extraFlags = printf "%s %s" "--tlsMode=requireTLS --tlsCertificateKeyFile=/certs/mongodb.pem --tlsCAFile=/certs/mongodb-ca-cert" $extraFlags  }}
> 
> templates/replicaset/statefulset.yaml
> 277:              {{- $extraFlags = printf "%s %s" "--tlsMode=requireTLS --tlsCertificateKeyFile=/certs/mongodb.pem --tlsCAFile=/certs/mongodb-ca-cert" $extraFlags  }}
> ```
> 
> If you find it useful to run 3.6 on the chart, we are open for contributions, so feel free to send a PR! We'd be glad to help with the review and release cycles.

@marcosbc, yes, it's true, there is a different mode which named `sslMode`. Also, there are different flags - not `--tls` but `--ssl`, not `--tlsCAFile` but `--sslCAFile`, and not `--tlsCertificateKeyFile` but `--sslPEMKeyFile`.

Okay, I will create a PR with `ssl` for old versions of mongo.

Thank you a lot!

**Comment by rafariossaa** [comment]
Thanks to you.
