### ISSUE TITLE
[Bitnami-Kafka] error java.net.UnknownHostException

### ISSUE THREAD

**Issue by VirajAttanayake** [bitnami/charts#7053]
**Which chart**:
bitnami/kafka for Kubernetes

**Describe the bug**
 have installed bitnami kafka on my k8 cluster. But I continuously see error java.net.UnknownHostException: kafka-0.kafka-headless.kafka.svc.cluster.local in kafka-o logs.

I login to the pod (kafka-o) and ran nslookup for kafka-0.kafka-headless.kafka.svc.cluster.local but the IP gets resolve with no issues

```
root@kafka-0:/# nslookup  kafka-0.kafka-headless.kafka.svc.cluster.local
Server:         10.43.0.10
Address:        10.43.0.10#53

Name:   kafka-0.kafka-headless.kafka.svc.mosip02.local
Address: 10.42.4.123
```
The netstat log from kafka-0 pod

```
root@kafka-0:/# netstat -lntp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:35267           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:9092            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:9093            0.0.0.0:*               LISTEN      -
```

Error stack from kubectl -n kafka logs kafka-0

```
[2021-07-26 07:59:29,350] WARN [Controller id=0, targetBrokerId=0] Error connecting to node kafka-0.kafka-headless.kafka.svc.cluster.local:9093 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.UnknownHostException: kafka-0.kafka-headless.kafka.svc.cluster.local
        at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
        at org.apache.kafka.clients.DefaultHostResolver.resolve(DefaultHostResolver.java:27)
        at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:111)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:512)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(ClusterConnectionStates.java:466)
        at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionStates.java:172)
        at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:985)
        at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:311)
        at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
        at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:292)
        at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:246)
        at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
```

**To Reproduce**

Just run the helm charts with default values 

**Expected behavior**
should resolve the intended pod

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Version:"v3.6.2"
```

- Output of `kubectl version`:

```

Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:35:50Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:07Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by migruiz4** [comment]
Hi @VirajAttanayake,

Please keep in mind it is a WARN message and not an error. This message may appear until the pod `kafka-0` reaches the Ready status and the headless service starts resolving its FQDN.

Does the message continue to appear after the pods are Ready?

**Comment by migruiz4** [comment]
Hi @VirajAttanayake,

In that case, based on the output of your `nslookup` command. I think the issue is caused because your cluster has a different domain: `mosip02.local` (By default, it will use `cluster.local` to configure Kafka).

Please try installing the chart with the value `--set clusterDomain=mosip02.local` and let me know if it solves the issue.

**Comment by VirajAttanayake** [comment]
Yes my domian is `mosip02.local `, I did not change the default `cluster.local` , but in my DNS any request to kafka.svc.cluster.local is changed to kafka.svc.mosip02.local. However I used the --set clusterDomain=mosip02.local and it works with one kafka and one zookeeper (default install). But not for below setup ? its again a similar error 

```
 ERROR [ListenerHandler-kafka-zookeeper-0.kafka-zookeeper-headless.kafka.svc.cluster.local:3888:QuorumCnxManager$Listener$ListenerHandler@1094] - Exception while listening
java.net.SocketException: Unresolved address
```

Note that i have still note remove my DNS rewrite (in CoreDNS) from kafka.svc.cluster.local-> kafka.svc.mosip02.local as single kafka and single zookeeper setup worked ? I am running in 6 Node Cluster (1-Master / 5 - Workers)


But when I ran with below `values.yaml `zookeeprs are giving errors.

contents of values.yaml

```
clusterDomain: mosip02.local
logRetentionBytes: _1073741824
defaultReplicationFactor: 3
offsetsTopicReplicationFactor: 3
transactionStateLogReplicationFactor: 3
numPartitions: 20
replicaCount: 5
sidecars: {}
autoCreateTopicsEnable: true

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 8Gi

zookeeper:
  replicaCount: 5
  persistence:
    enabled: true
    size: 2Gi

resources:
  limits: {}
  #   cpu: 250m
  #   memory: 1Gi
  requests:
    cpu: 200m
    memory: 2000Mi

```



```
[root@mpmaster01 kafka]# kubectl -n kafka  get all
NAME                    READY   STATUS             RESTARTS   AGE
pod/kafka-0             0/1     Error              4          3m23s
pod/kafka-1             0/1     CrashLoopBackOff   3          3m23s
pod/kafka-2             0/1     CrashLoopBackOff   3          3m23s
pod/kafka-3             0/1     Error              4          3m23s
pod/kafka-4             0/1     CrashLoopBackOff   4          3m23s
pod/kafka-zookeeper-0   0/1     CrashLoopBackOff   3          3m23s
pod/kafka-zookeeper-1   0/1     CrashLoopBackOff   4          3m23s
pod/kafka-zookeeper-2   0/1     CrashLoopBackOff   4          3m23s
pod/kafka-zookeeper-3   0/1     CrashLoopBackOff   4          3m23s
pod/kafka-zookeeper-4   0/1     CrashLoopBackOff   3          3m23s

NAME                               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
service/kafka                      ClusterIP   10.43.63.231    <none>        9092/TCP                     3m23s
service/kafka-headless             ClusterIP   None            <none>        9092/TCP,9093/TCP            3m23s
service/kafka-zookeeper            ClusterIP   10.43.176.168   <none>        2181/TCP,2888/TCP,3888/TCP   3m23s
service/kafka-zookeeper-headless   ClusterIP   None            <none>        2181/TCP,2888/TCP,3888/TCP   3m23s

NAME                               READY   AGE
statefulset.apps/kafka             0/5     3m23s
statefulset.apps/kafka-zookeeper   0/5     3m23s
```
Error in all 5 zookepers.

```
[root@mpmaster01 kafka]# kubectl -n kafka logs kafka-zookeeper-0
zookeeper 15:18:22.33
zookeeper 15:18:22.33 Welcome to the Bitnami zookeeper container
zookeeper 15:18:22.33 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-zookeeper
zookeeper 15:18:22.33 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-zookeeper/issues
zookeeper 15:18:22.33
zookeeper 15:18:22.34 INFO  ==> ** Starting ZooKeeper setup **
zookeeper 15:18:22.35 WARN  ==> You have set the environment variable ALLOW_ANONYMOUS_LOGIN=yes. For safety reasons, do not use this flag in a production environment.
zookeeper 15:18:22.37 INFO  ==> Initializing ZooKeeper...
zookeeper 15:18:22.37 INFO  ==> No injected configuration file found, creating default config files...
zookeeper 15:18:22.42 INFO  ==> Adding server: kafka-zookeeper-0.kafka-zookeeper-headless.kafka.svc.cluster.local:2888:3888 with id: 1
zookeeper 15:18:22.42 INFO  ==> Adding server: kafka-zookeeper-1.kafka-zookeeper-headless.kafka.svc.cluster.local:2888:3888 with id: 2
zookeeper 15:18:22.42 INFO  ==> Adding server: kafka-zookeeper-2.kafka-zookeeper-headless.kafka.svc.cluster.local:2888:3888 with id: 3
zookeeper 15:18:22.43 INFO  ==> Adding server: kafka-zookeeper-3.kafka-zookeeper-headless.kafka.svc.cluster.local:2888:3888 with id: 4
zookeeper 15:18:22.43 INFO  ==> Adding server: kafka-zookeeper-4.kafka-zookeeper-headless.kafka.svc.cluster.local:2888:3888 with id: 5
zookeeper 15:18:22.44 INFO  ==> Deploying ZooKeeper with persisted data...
zookeeper 15:18:22.44 INFO  ==> ** ZooKeeper setup finished! **

zookeeper 15:18:22.45 INFO  ==> ** Starting ZooKeeper **
/opt/bitnami/java/bin/java
ZooKeeper JMX enabled by default
Using config: /opt/bitnami/zookeeper/bin/../conf/zoo.cfg
2021-07-26 15:18:23,285 [myid:1] - ERROR [ListenerHandler-kafka-zookeeper-0.kafka-zookeeper-headless.kafka.svc.cluster.local:3888:QuorumCnxManager$Listener$ListenerHandler@1094] - Exception while listening
java.net.SocketException: Unresolved address
        at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
        at java.base/java.net.ServerSocket.bind(ServerSocket.java:349)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener$ListenerHandler.createNewServerSocket(QuorumCnxManager.java:1136)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener$ListenerHandler.acceptConnections(QuorumCnxManager.java:1065)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener$ListenerHandler.run(QuorumCnxManager.java:1034)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
2021-07-26 15:18:24,294 [myid:1] - ERROR [ListenerHandler-kafka-zookeeper-0.kafka-zookeeper-headless.kafka.svc.cluster.local:3888:QuorumCnxManager$Listener$ListenerHandler@1094] - Exception while listening
java.net.SocketException: Unresolved address
        at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
        at java.base/java.net.ServerSocket.bind(ServerSocket.java:349)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener$ListenerHandler.createNewServerSocket(QuorumCnxManager.java:1136)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener$ListenerHandler.acceptConnections(QuorumCnxManager.java:1065)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener$ListenerHandler.run(QuorumCnxManager.java:1034)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
2021-07-26 15:18:25,296 [myid:1] - ERROR [ListenerHandler-kafka-zookeeper-0.kafka-zookeeper-headless.kafka.svc.cluster.local:3888:QuorumCnxManager$Listener$ListenerHandler@1094] - Exception while listening
java.net.SocketException: Unresolved address
        at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
        at java.base/java.net.ServerSocket.bind(ServerSocket.java:349)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener$ListenerHandler.createNewServerSocket(QuorumCnxManager.java:1136)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener$ListenerHandler.acceptConnections(QuorumCnxManager.java:1065)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener$ListenerHandler.run(QuorumCnxManager.java:1034)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
2021-07-26 15:18:26,297 [myid:1] - ERROR [ListenerHandler-kafka-zookeeper-0.kafka-zookeeper-headless.kafka.svc.cluster.local:3888:QuorumCnxManager$Listener$ListenerHandler@1113] - Leaving listener thread for address kafka-zookeeper-0.kafka-zookeeper-headless.kafka.svc.cluster.local:3888 after 3 errors. Use zookeeper.electionPortBindRetry property to increase retry count.
2021-07-26 15:18:26,298 [myid:1] - ERROR [QuorumPeerListener:QuorumCnxManager$Listener@982] - As I'm leaving the listener thread, I won't be able to participate in leader election any longer: kafka-zookeeper-0.kafka-zookeeper-headless.kafka.svc.cluster.local:3888
2021-07-26 15:18:26,300 [myid:1] - ERROR [QuorumPeerListener:ServiceUtils@42] - Exiting JVM with code 14
```

Thanks you

**Comment by migruiz4** [comment]
Hi @VirajAttanayake,

I sorry I forgot to mention that Zookeeper needs to be configured with `clusterDomain` separatedly as it is a subchart.

Could you please try adding `zookeeper.clusterDomain=mosip02.local` too?

**Comment by VirajAttanayake** [comment]
Hi @migruiz4 

Thank you very much for your prompt support. I managed to get it working after adding `zookeeper.clusterDomain=mosip02.local`

```
[root@mpmaster01 kafka]# kubectl -n kafka get all
NAME                    READY   STATUS    RESTARTS   AGE
pod/kafka-0             1/1     Running   0          116s
pod/kafka-1             1/1     Running   0          116s
pod/kafka-2             1/1     Running   1          116s
pod/kafka-3             1/1     Running   2          116s
pod/kafka-4             1/1     Running   0          116s
pod/kafka-zookeeper-0   1/1     Running   0          116s
pod/kafka-zookeeper-1   1/1     Running   0          116s
pod/kafka-zookeeper-2   1/1     Running   0          116s
pod/kafka-zookeeper-3   1/1     Running   0          116s
pod/kafka-zookeeper-4   1/1     Running   0          116s

NAME                               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
service/kafka                      ClusterIP   10.43.247.119   <none>        9092/TCP                     116s
service/kafka-headless             ClusterIP   None            <none>        9092/TCP,9093/TCP            116s
service/kafka-zookeeper            ClusterIP   10.43.108.67    <none>        2181/TCP,2888/TCP,3888/TCP   116s
service/kafka-zookeeper-headless   ClusterIP   None            <none>        2181/TCP,2888/TCP,3888/TCP   116s
```

**Comment by migruiz4** [comment]
You are welcome @VirajAttanayake !

I'm glad the issue is now resolved. 

I will proceed to close this issue, if you need any further help please let us know.

**Comment by xuyf1001** [comment]
I have the same issue,but I didn't resolve it by configuring with their clusterDomain.

**Comment by migruiz4** [comment]
Hi @xuyf1001,

Could you please open a separate issue providing additional details about the issue you are facing? Opening a separate issue helps us track it more efficiently for a better assistance, and we need additional information to troubleshoot your issue: what version of the chart you are using, values used in your deployment, logs, and other information about the pods.

**Comment by xuyf1001** [comment]
![34319ea2b15e05988606622d3e2514f](https://github.com/bitnami/charts/assets/110028927/1a3e6df2-4d55-499f-880c-2f6d5f9134d0)
The issue are as follows.I have two unrelated k8s clusters A and B, each with a kafka cluster deployed, and I want to borrow the kafka script of the A k8s cluster to communicate kafka on the B k8s cluster to create topic.However, it did not take effect.This may cause the nodeport to be unavailable.And I use --set clusterDomain above,also did not take effect.Entering the container，there’s no nslookup command.Now,I arm very dazed and don‘t know how to deal with it.

**Comment by xuyf1001** [comment]
my listener config is advertisedListeners: "INTERNAL://:9092,EXTERNAL://:9094" and listeners: "INTERNAL://:9092,EXTERNAL://:9094",Is there any problems with this config？

**Comment by migruiz4** [comment]
Hi @xuyf1001,

If I understood correctly, your scenario is the following.

You have two Kafka nodes in two separated Kubernetes clusters, and you are performing the following operation:

* Bash session inside Kafka pod in K8S cluster 1
* Then, you use the script `kafka-topics.sh` to create a topic in the other Kafka deployment in K8S cluster 2.
* The execution of the script returns the error from your screenshot.

Is that correct?

**Comment by migruiz4** [comment]
In that case, it appears that you are using the headless service to connect from K8S cluster 1 to K8S cluster 2.

Headless services are internal and can only be resolved by the pods within the same Kubernetes cluster.

That is the reason why calling 'kafka-aa-000000021-0.kafka-aa-000000021-headless.component-ns.svc.cluster.local' results in 'Name or service not known'.

To connect to Kafka from outside its Kubernetes cluster, you need to have `externalAccess.enabled=true` using one of the different methods available. You can find more information about how to configure external access here: https://github.com/bitnami/charts/blob/main/bitnami/kafka/README.md#accessing-kafka-brokers-from-outside-the-cluster

**Comment by xuyf1001** [comment]
This way will use load balancer？Could I use istio by using virtualservice and gateway?

**Comment by migruiz4** [comment]
In the link I shared you can find our documentation on how to configure external access, which covers different cases: using LoadBalancer service, NodePord service, ClusterIP service and using external-dns.

I'm sorry but we don't have documentation on how to configure the Kafka chart using Istio nor can ensure it is possible as it is not officially supported, but our charts include features so they can customize the chart resources as much as possible, e.g adding custom labels and annotations in every resource, sidecars and init containers, additional volumes/volumeMounts, additional templates, etc.

**Comment by xuyf1001** [comment]
Well, I see, thank you, my bro.

**Comment by sahil28032005** [comment]
eper.ZooKeeper)
[2025-01-27 15:56:06,094] INFO Client environment:java.class.path=/usr/local/kafka/bin/../libs/activation-1.1.1.jar:/usr/local/kafka/bin/../libs/aopalliance-repackaged-2.5.0-b42.jar:/usr/local/kafka/bin/../libs/argparse4j-0.7.0.jar:/usr/local/kafka/bin/../libs/audience-annotations-0.5.0.jar:/usr/local/kafka/bin/../libs/aws-msk-iam-auth-2.2.0-all.jar:/usr/local/kafka/bin/../libs/commons-lang3-3.8.1.jar:/usr/local/kafka/bin/../libs/connect-api-2.2.1.jar:/usr/local/kafka/bin/../libs/connect-basic-auth-extension-2.2.1.jar:/usr/local/kafka/bin/../libs/connect-file-2.2.1.jar:/usr/local/kafka/bin/../libs/connect-json-2.2.1.jar:/usr/local/kafka/bin/../libs/connect-runtime-2.2.1.jar:/usr/local/kafka/bin/../libs/connect-transforms-2.2.1.jar:/usr/local/kafka/bin/../libs/guava-20.0.jar:/usr/local/kafka/bin/../libs/hk2-api-2.5.0-b42.jar:/usr/local/kafka/bin/../libs/hk2-locator-2.5.0-b42.jar:/usr/local/kafka/bin/../libs/hk2-utils-2.5.0-b42.jar:/usr/local/kafka/bin/../libs/jackson-annotations-2.9.8.jar:/usr/local/kafka/bin/../libs/jackson-core-2.9.8.jar:/usr/local/kafka/bin/../libs/jackson-databind-2.9.8.jar:/usr/local/kafka/bin/../libs/jackson-datatype-jdk8-2.9.8.jar:/usr/local/kafka/bin/../libs/jackson-jaxrs-base-2.9.8.jar:/usr/local/kafka/bin/../libs/jackson-jaxrs-json-provider-2.9.8.jar:/usr/local/kafka/bin/../libs/jackson-module-jaxb-annotations-2.9.8.jar:/usr/local/kafka/bin/../libs/javassist-3.22.0-CR2.jar:/usr/local/kafka/bin/../libs/javax.annotation-api-1.2.jar:/usr/local/kafka/bin/../libs/javax.inject-1.jar:/usr/local/kafka/bin/../libs/javax.inject-2.5.0-b42.jar:/usr/local/kafka/bin/../libs/javax.servlet-api-3.1.0.jar:/usr/local/kafka/bin/../libs/javax.ws.rs-api-2.1.1.jar:/usr/local/kafka/bin/../libs/javax.ws.rs-api-2.1.jar:/usr/local/kafka/bin/../libs/jaxb-api-2.3.0.jar:/usr/local/kafka/bin/../libs/jersey-client-2.27.jar:/usr/local/kafka/bin/../libs/jersey-common-2.27.jar:/usr/local/kafka/bin/../libs/jersey-container-servlet-2.27.jar:/usr/local/kafka/bin/../libs/jersey-container-servlet-core-2.27.jar:/usr/local/kafka/bin/../libs/jersey-hk2-2.27.jar:/usr/local/kafka/bin/../libs/jersey-media-jaxb-2.27.jar:/usr/local/kafka/bin/../libs/jersey-server-2.27.jar:/usr/local/kafka/bin/../libs/jetty-client-9.4.14.v20181114.jar:/usr/local/kafka/bin/../libs/jetty-continuation-9.4.14.v20181114.jar:/usr/local/kafka/bin/../libs/jetty-http-9.4.14.v20181114.jar:/usr/local/kafka/bin/../libs/jetty-io-9.4.14.v20181114.jar:/usr/local/kafka/bin/../libs/jetty-security-9.4.14.v20181114.jar:/usr/local/kafka/bin/../libs/jetty-server-9.4.14.v20181114.jar:/usr/local/kafka/bin/../libs/jetty-servlet-9.4.14.v20181114.jar:/usr/local/kafka/bin/../libs/jetty-servlets-9.4.14.v20181114.jar:/usr/local/kafka/bin/../libs/jetty-util-9.4.14.v20181114.jar:/usr/local/kafka/bin/../libs/jopt-simple-5.0.4.jar:/usr/local/kafka/bin/../libs/kafka-clients-2.2.1.jar:/usr/local/kafka/bin/../libs/kafka-log4j-appender-2.2.1.jar:/usr/local/kafka/bin/../libs/kafka-streams-2.2.1.jar:/usr/local/kafka/bin/../libs/kafka-streams-examples-2.2.1.jar:/usr/local/kafka/bin/../libs/kafka-streams-scala_2.12-2.2.1.jar:/usr/local/kafka/bin/../libs/kafka-streams-test-utils-2.2.1.jar:/usr/local/kafka/bin/../libs/kafka-tools-2.2.1.jar:/usr/local/kafka/bin/../libs/kafka_2.12-2.2.1-sources.jar:/usr/local/kafka/bin/../libs/kafka_2.12-2.2.1.jar:/usr/local/kafka/bin/../libs/log4j-1.2.17.jar:/usr/local/kafka/bin/../libs/lz4-java-1.5.0.jar:/usr/local/kafka/bin/../libs/maven-artifact-3.6.0.jar:/usr/local/kafka/bin/../libs/metrics-core-2.2.0.jar:/usr/local/kafka/bin/../libs/osgi-resource-locator-1.0.1.jar:/usr/local/kafka/bin/../libs/plexus-utils-3.1.0.jar:/usr/local/kafka/bin/../libs/reflections-0.9.11.jar:/usr/local/kafka/bin/../libs/rocksdbjni-5.15.10.jar:/usr/local/kafka/bin/../libs/scala-library-2.12.8.jar:/usr/local/kafka/bin/../libs/scala-logging_2.12-3.9.0.jar:/usr/local/kafka/bin/../libs/scala-reflect-2.12.8.jar:/usr/local/kafka/bin/../libs/slf4j-api-1.7.25.jar:/usr/local/kafka/bin/../libs/slf4j-log4j12-1.7.25.jar:/usr/local/kafka/bin/../libs/snappy-java-1.1.7.2.jar:/usr/local/kafka/bin/../libs/validation-api-1.1.0.Final.jar:/usr/local/kafka/bin/../libs/zkclient-0.11.jar:/usr/local/kafka/bin/../libs/zookeeper-3.4.13.jar:/usr/local/kafka/bin/../libs/zstd-jni-1.3.8-1.jar (org.apache.zookeeper.ZooKeeper)
[2025-01-27 15:56:06,095] INFO Client environment:java.library.path=/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib (org.apache.zookeeper.ZooKeeper)
[2025-01-27 15:56:06,095] INFO Client environment:java.io.tmpdir=/tmp (org.apache.zookeeper.ZooKeeper)
[2025-01-27 15:56:06,095] INFO Client environment:java.compiler=<NA> (org.apache.zookeeper.ZooKeeper)
[2025-01-27 15:56:06,095] INFO Client environment:os.name=Linux (org.apache.zookeeper.ZooKeeper)
[2025-01-27 15:56:06,095] INFO Client environment:os.arch=amd64 (org.apache.zookeeper.ZooKeeper)
[2025-01-27 15:56:06,095] INFO Client environment:os.version=6.1.119-129.201.amzn2023.x86_64 (org.apache.zookeeper.ZooKeeper)
[2025-01-27 15:56:06,095] INFO Client environment:user.name=ec2-user (org.apache.zookeeper.ZooKeeper)
[2025-01-27 15:56:06,095] INFO Client environment:user.home=/home/ec2-user (org.apache.zookeeper.ZooKeeper)
[2025-01-27 15:56:06,095] INFO Client environment:user.dir=/usr/local/kafka (org.apache.zookeeper.ZooKeeper)
[2025-01-27 15:56:06,096] INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=6000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@7b4c50bc (org.apache.zookeeper.ZooKeeper)
[2025-01-27 15:56:06,118] INFO Opening socket connection to server localhost/<unresolved>:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2025-01-27 15:56:06,119] INFO [ZooKeeperClient] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2025-01-27 15:56:06,124] WARN Session 0x0 for server localhost/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.nio.channels.UnresolvedAddressException
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:149)
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:157)
        at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:816)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:839)
        at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
        at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
        at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)
[2025-01-27 15:56:07,231] INFO Opening socket connection to server localhost/<unresolved>:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2025-01-27 15:56:07,232] WARN Session 0x0 for server localhost/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.nio.channels.UnresolvedAddressException
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:149)
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:157)
        at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:816)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:839)
        at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
        at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
        at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)
[2025-01-27 15:56:08,334] INFO Opening socket connection to server localhost/<unresolved>:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2025-01-27 15:56:08,334] WARN Session 0x0 for server localhost/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.nio.channels.UnresolvedAddressException
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:149)
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:157)
        at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:816)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:839)
        at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
        at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
        at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)
[2025-01-27 15:56:09,436] INFO Opening socket connection to server localhost/<unresolved>:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2025-01-27 15:56:09,437] WARN Session 0x0 for server localhost/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.nio.channels.UnresolvedAddressException
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:149)
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:157)
        at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:816)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:839)
        at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
        at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
        at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)
[2025-01-27 15:56:10,541] INFO Opening socket connection to server localhost/<unresolved>:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2025-01-27 15:56:10,541] WARN Session 0x0 for server localhost/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.nio.channels.UnresolvedAddressException
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:149)
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:157)
        at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:816)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:839)
        at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
        at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
        at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)
[2025-01-27 15:56:11,643] INFO Opening socket connection to server localhost/<unresolved>:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2025-01-27 15:56:11,643] WARN Session 0x0 for server localhost/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.nio.channels.UnresolvedAddressException
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:149)
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:157)
        at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:816)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:839)
        at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
        at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
        at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)
[2025-01-27 15:56:12,121] INFO [ZooKeeperClient] Closing. (kafka.zookeeper.ZooKeeperClient)
[2025-01-27 15:56:12,745] INFO Opening socket connection to server localhost/<unresolved>:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2025-01-27 15:56:12,847] INFO EventThread shut down for session: 0x0 (org.apache.zookeeper.ClientCnxn)
[2025-01-27 15:56:12,848] INFO Session: 0x0 closed (org.apache.zookeeper.ZooKeeper)
[2025-01-27 15:56:12,849] INFO [ZooKeeperClient] Closed. (kafka.zookeeper.ZooKeeperClient)
[2025-01-27 15:56:12,853] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
        at kafka.zookeeper.ZooKeeperClient.$anonfun$waitUntilConnected$3(ZooKeeperClient.scala:242)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:251)
        at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:238)
        at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:96)
        at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1825)
        at kafka.server.KafkaServer.createZkClient$1(KafkaServer.scala:361)
        at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:385)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:205)
        at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
        at kafka.Kafka$.main(Kafka.scala:75)
        at kafka.Kafka.main(Kafka.scala)
[2025-01-27 15:56:12,855] INFO shutting down (kafka.server.KafkaServer)
[2025-01-27 15:56:12,863] INFO shut down completed (kafka.server.KafkaServer)
[2025-01-27 15:56:12,867] ERROR Exiting Kafka. (kafka.server.KafkaServerStartable)
[2025-01-27 15:56:12,874] INFO shutting down (kafka.server.KafkaServer)
[ec2-user@ip-172-31-7-146 kafka]$ why

**Comment by sahil28032005** [comment]
hey my zookeeper starts but while starting kafka i get this type of errors i have tried lots of combinations still this issue persists please guide!
