### ISSUE TITLE
[bitnami/harbor]: Unable to authenticate with docker registry getting 404

### ISSUE THREAD

**Issue by panteparak** [bitnami/charts#8354]
**Which chart**:
GoHarbor (Kubernetes Helm Chart) 
Version: 11.1.5
App Version: 2.4.0

**Describe the bug**
Deployed using mostly default parameters, Able to access the UI. But when I attempt to authenticate with Docker Registry using Robot Account and Admin Account. I received 404 Error `login attempt to <SOME_DOMAIN>/v2/ failed with status: 404 Not Found`

**Nginx Container Log**
```
[09/Dec/2021:12:31:36 +0000]:127.0.0.6 - "HEAD /v2/gf-app/web/manifests/1.0.0 HTTP/1.1" 401 0 "-" "containerd/1.4.12" 0.010 0.011 .
[09/Dec/2021:12:31:36 +0000]:127.0.0.6 - "POST /service/token HTTP/1.1" 405 19 "-" "containerd/1.4.12" 0.007 0.007 .
[09/Dec/2021:12:31:36 +0000]:127.0.0.6 - "GET /service/token?scope=repository%3Agf-app%2Fweb%3Apull&service=harbor-registry HTTP/1.1" 200 965 "-" "containerd/1.4.12" 0.046 0.046 .
[09/Dec/2021:12:31:36 +0000]:127.0.0.6 - "HEAD /v2/gf-app/web/manifests/1.0.0 HTTP/1.1" 404 0 "-" "containerd/1.4.12" 0.015 0.015 .
```

**Harbor Core**
```
2021-12-09T12:22:54Z [DEBUG] [/server/middleware/security/unauthorized.go:28][requestID="80db34c0-fedb-4682-a29a-ce517fefb494"]: an unauthorized security context generated for request GET /api/v2.0/ping
2021-12-09T12:22:55Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id 07131170-6bb8-47dc-bb0a-2159e322f1c7 to the logger for the request GET /v2/
2021-12-09T12:22:55Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:53]: In artifact info middleware, url: /v2/
2021-12-09T12:22:55Z [DEBUG] [/server/middleware/security/unauthorized.go:28][requestID="07131170-6bb8-47dc-bb0a-2159e322f1c7"]: an unauthorized security context generated for request GET /v2/
2021-12-09T12:22:55Z [DEBUG] [/lib/http/error.go:59]: {"errors":[{"code":"UNAUTHORIZED","message":"unauthorized: unauthorized"}]}
2021-12-09T12:22:55Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id c62f168d-f7db-4b60-964b-dd01217725e1 to the logger for the request GET /service/token
2021-12-09T12:22:55Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:53]: In artifact info middleware, url: /service/token?account=robot-gitlab-cicd&client_id=docker&offline_token=true&service=harbor-registry
2021-12-09T12:22:55Z [INFO] [/server/middleware/security/robot.go:71][requestID="c62f168d-f7db-4b60-964b-dd01217725e1"]: a robot security context generated for request GET /service/token
2021-12-09T12:22:55Z [DEBUG] [/core/service/token/token.go:36]: URL for token request: /service/token?account=robot-gitlab-cicd&client_id=docker&offline_token=true&service=harbor-registry
2021-12-09T12:22:55Z [DEBUG] [/core/service/token/creator.go:230]: scopes: []
2021-12-09T12:22:55Z [DEBUG] [/core/service/token/authutils.go:50]: scopes: []
2021-12-09T12:22:55Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id 34218779-6d5c-40ed-b3b3-4f2c2bd14828 to the logger for the request GET /v2/
2021-12-09T12:22:55Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:53]: In artifact info middleware, url: /v2/
```

**Istio VirtualService**
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: goharbor-vs
  namespace: goharbor-services
spec:
  gateways:
    - goharbor-gateway
  hosts:
    - SOME_DOMAIN
  http:
    - headers:
        response:
          set:
            Strict-Transport-Security: max-age=300; includeSubDomains
            X-Forwarded-Proto: https
      match:
        - uri:
            prefix: /
      route:
        - destination:
            host: goharbor-services
            port:
              number: 80
```

**To Reproduce**
Deployed using below Helm Chart values:
```yaml
fullnameOverride: "goharbor-services"
global:
  storageClass: "rook-ceph-block"

volumePermissions:
  enabled: true

internalTLS: 
  enabled: false

externalURL: "SOME_DOMAIN"

harborAdminPassword: "REDACTED"

registry:
  relativeurls: true

service: 
  type: ClusterIP
  # Using Lets Encrypt sidecar instead
  tls:
    enabled: false 

persistence:
  persistentVolumeClaim:
    registry:
      size: 50Gi
    jobservice:
      size: 2Gi
    chartmuseum:
      size: 5Gi
    trivy: 
      size: 5Gi
    
postgresql:
  enabled: false

externalDatabase:
  host: postgresql-shared.postgresql-services.svc.cluster.local
  password: REDACTED
  user: goharbor
  sslmode: require
  coreDatabase: goharbor-core
  clairDatabase: goharbor-clair
  notaryServerDatabase: goharbor-notary

redis: 
  enabled: true
  auth:
    enabled: true
    password: REDACTED
  master:
    persistence:
      enabled: true
  
  replica:
    persistence:
      enabled: true
```

**Expected behavior**
Able to authenticate with Docker Registry and push container.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by juan131** [comment]
Hi @panteparak 

Are you accessing Harbor from outside your kubernetes cluster? It seems that you set `service.type` to `ClusterIP` which means that your configuring your Harbor installation to be only reachable from within the cluster:

- https://github.com/bitnami/charts/tree/master/bitnami/harbor#configure-the-way-how-to-expose-harbor-service

Check also these docs that describe how to configure the external URL depending on you expose Harbor:

- https://github.com/bitnami/charts/tree/master/bitnami/harbor#configure-the-external-url

**Comment by panteparak** [comment]
Hi @juan131 
I have a Istio Gateway that connects to `goharbor-services` via Istio VirtualService and Gateway. Would this cause a problem?

**Comment by juan131** [comment]
I'm sorry but I'm not familiar with Istio Gateway nor Istio VirtualService, so I'm afraid I can't tell if that could be problematic or not.

**Comment by panteparak** [comment]
@juan131 
Is it safe to assume that any request passing through **goharbor-services** should route to any type of requests within GoHarbor?

If so, the problem that I like to highlight is when core service is trying to send request to image registry it got 404. (As seen in Core Log) 

Could this be a problem between core service and Registry? Since everything routing is handled by nginx (goharbor-service)

**Comment by rafariossaa** [comment]
Hi,
  I am not sure what can be happening in this case, but maybe Istio is filtering the headers hence the 40x errors you are getting.
  Could you try without using istio ?

**Comment by panteparak** [comment]
@rafariossaa 
I will try without istio (probably port forwarding harbor-services). 

However, i like to point out that `Nginx Container` that is an entrypoint into harbor does received a request to `/v2/*` but received 40x error. This means that Istio does in fact passed on the request to harbor internal.  but somehow failed to forward the request to docker registry. See Log Above

**Comment by panteparak** [comment]
@rafariossaa @juan131 

i've tried exposing it without Istio. I am still getting the same error `docker 404`. I looked at the log from Nginx Container and it seems that:

1. request to /v2/* get routed directly to docker registry. and get a 401 unauthorized.
2. another request was sent to `/service/token` which returns 200 with authentication response payload. Within the payload, `token` key is filled with authentication token but `access_token` is returned as blank string. is this expected? 
3. Subsequence request trying to access resource at /v2/* return 404.

Could this be an issue with docker registry

```
[14/Dec/2021:10:56:57 +0000]:127.0.0.6 - "HEAD /v2/gf-app/web/manifests/1.0.0 HTTP/1.1" 401 0 "-" "containerd/1.4.12" 0.006 0.006 .
[14/Dec/2021:10:56:57 +0000]:127.0.0.6 - "POST /service/token HTTP/1.1" 405 19 "-" "containerd/1.4.12" 0.005 0.005 .
[14/Dec/2021:10:56:57 +0000]:127.0.0.6 - "GET /service/token?scope=repository%3Agf-app%2Fweb%3Apull&service=harbor-registry HTTP/1.1" 200 967 "-" "containerd/1.4.12" 0.045 0.045 .
[14/Dec/2021:10:56:57 +0000]:127.0.0.6 - "HEAD /v2/gf-app/web/manifests/1.0.0 HTTP/1.1" 404 0 "-" "containerd/1.4.12" 0.011 0.011 .
```

**Comment by rafariossaa** [comment]
I have deployed in minikube with:
```
helm install myharbor bitnami/harbor
```
and in the nginx logs I can see:
```
[17/Dec/2021:12:54:37 +0000]:172.17.0.1 - "GET /api/v2.0/scanners?page_size=15&page=1 HTTP/1.1" 200 341 "https://192.168.49.100/harbor/projects" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0" 0.005 0.004 .
[17/Dec/2021:12:54:37 +0000]:172.17.0.1 - "GET /api/v2.0/configurations HTTP/1.1" 200 2734 "https://192.168.49.100/harbor/projects" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0" 0.002 0.004 .
```

**Comment by panteparak** [comment]
@rafariossaa 

Hmmmm, Strangely i am still getting similar errord as above. I have modified my configuration to deploy an Ingress.

```
2021-12-21T13:00:14Z [DEBUG] [/server/middleware/security/session.go:46][requestID="0e511a54-82ea-4109-b9f6-4d91f9f41abc"]: a session security context generated for request GET /api/v2.0/projects
2021-12-21T13:00:14Z [DEBUG] [/pkg/permission/evaluator/admin/admin.go:35]: system administrator admin require list action for resource /system/project
2021-12-21T13:00:14Z [DEBUG] [/chartserver/handler_repo.go:166]: Getting index.yaml from 'http://harbor-test-services-chartmuseum/library/index.yaml'
2021-12-21T13:00:14Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id 3f60ded2-0a7a-406e-9ec1-130b0b641c45 to the logger for the request GET /api/v2.0/robots
2021-12-21T13:00:14Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:53]: In artifact info middleware, url: /api/v2.0/robots?page_size=15&page=1
2021-12-21T13:00:14Z [DEBUG] [/server/middleware/security/session.go:46][requestID="3f60ded2-0a7a-406e-9ec1-130b0b641c45"]: a session security context generated for request GET /api/v2.0/robots
2021-12-21T13:00:14Z [DEBUG] [/pkg/permission/evaluator/admin/admin.go:35]: system administrator admin require list action for resource /system/robot
2021-12-21T13:00:16Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id c8817ac1-dfca-4412-8c95-e42929191cac to the logger for the request GET /api/v2.0/ping
2021-12-21T13:00:16Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:53]: In artifact info middleware, url: /api/v2.0/ping
2021-12-21T13:00:16Z [DEBUG] [/server/middleware/security/unauthorized.go:28][requestID="c8817ac1-dfca-4412-8c95-e42929191cac"]: an unauthorized security context generated for request GET /api/v2.0/ping
2021-12-21T13:00:16Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id 4bab8877-b8b6-4b8f-991a-543288d2e7fe to the logger for the request GET /api/v2.0/ping
2021-12-21T13:00:16Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:53]: In artifact info middleware, url: /api/v2.0/ping
2021-12-21T13:00:16Z [DEBUG] [/server/middleware/security/unauthorized.go:28][requestID="4bab8877-b8b6-4b8f-991a-543288d2e7fe"]: an unauthorized security context generated for request GET /api/v2.0/ping
2021-12-21T13:00:19Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id 17b48519-18dd-4c97-9127-6d85826c4dc0 to the logger for the request GET /v2/
2021-12-21T13:00:19Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:53]: In artifact info middleware, url: /v2/
2021-12-21T13:00:19Z [DEBUG] [/server/middleware/security/unauthorized.go:28][requestID="17b48519-18dd-4c97-9127-6d85826c4dc0"]: an unauthorized security context generated for request GET /v2/
2021-12-21T13:00:19Z [DEBUG] [/lib/http/error.go:59]: {"errors":[{"code":"UNAUTHORIZED","message":"unauthorized: unauthorized"}]}
2021-12-21T13:00:19Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id 8e8732d2-ae80-4213-858c-3ca3e764a7ee to the logger for the request GET /service/token
2021-12-21T13:00:19Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:53]: In artifact info middleware, url: /service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry
2021-12-21T13:00:19Z [DEBUG] [/core/auth/authenticator.go:145]: Current AUTH_MODE is db_auth
2021-12-21T13:00:19Z [DEBUG] [/server/middleware/security/basic_auth.go:47][requestID="8e8732d2-ae80-4213-858c-3ca3e764a7ee"]: a basic auth security context generated for request GET /service/token
2021-12-21T13:00:19Z [DEBUG] [/core/service/token/token.go:36]: URL for token request: /service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry
2021-12-21T13:00:19Z [DEBUG] [/core/service/token/creator.go:230]: scopes: []
2021-12-21T13:00:19Z [DEBUG] [/core/service/token/authutils.go:50]: scopes: []
2021-12-21T13:00:19Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id 9c23b918-020e-4bf9-b49b-009e60ed3340 to the logger for the request GET /v2/
2021-12-21T13:00:19Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:53]: In artifact info middleware, url: /v2/
2021-12-21T13:00:26Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id 563bfad0-f86f-46dc-ae45-ab4192874584 to the logger for the request GET /api/v2.0/ping
2021-12-21T13:00:26Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:53]: In artifact info middleware, url: /api/v2.0/ping
```

**Comment by rafariossaa** [comment]
Not very sure what can be happening here, maybe it worth it  to ask in harbor related forums.
