### ISSUE TITLE
[bitnami/mariadb-galera] Multi Node cluster fails to recover with publishNotReadyAddresses=true

### ISSUE THREAD

**Issue by cwrau** [bitnami/charts#8424]
**Which chart**:
mariadb-galera:6.0.8

**Describe the bug**
After the upgrade from chart version 6.0.6 to 6.0.8 some of our cluster can't recover anymore

**To Reproduce**
Have running cluster with chart version 6.0.6, upgrade to version 6.0.8

In the logs, the following error message is logged;

```log
2021-12-15 11:04:00 0 [Note] WSREP: gcomm: connecting to group 'galera', peer 'release-name-mariadb-headless.demo-4ap.svc.cluster.local:'
2021-12-15 11:04:00 0 [Note] WSREP: (b51ed405-b451, 'tcp://0.0.0.0:4567') Found matching local endpoint for a connection, blacklisting address tcp://192.168.15.225:4567
2021-12-15 11:04:03 0 [Note] WSREP: EVS version upgrade 0 -> 1
2021-12-15 11:04:03 0 [Note] WSREP: PC protocol upgrade 0 -> 1
2021-12-15 11:04:03 0 [Warning] WSREP: no nodes coming from prim view, prim not possible
2021-12-15 11:04:03 0 [Note] WSREP: view(view_id(NON_PRIM,b51ed405-b451,1) memb {
	b51ed405-b451,0
} joined {
} left {
} partitioned {
})
2021-12-15 11:04:04 0 [Warning] WSREP: last inactive check more than PT1.5S ago (PT3.50119S), skipping check
2021-12-15 11:04:33 0 [Note] WSREP: PC protocol downgrade 1 -> 0
2021-12-15 11:04:33 0 [Note] WSREP: view((empty))
2021-12-15 11:04:33 0 [ERROR] WSREP: failed to open gcomm backend connection: 110: failed to reach primary view: 110 (Connection timed out)
	 at /bitnami/blacksmith-sandox/libgalera-26.4.9/gcomm/src/pc.cpp:connect():160
2021-12-15 11:04:33 0 [ERROR] WSREP: /bitnami/blacksmith-sandox/libgalera-26.4.9/gcs/src/gcs_core.cpp:gcs_core_open():220: Failed to open backend connection: -110 (Connection timed out)
2021-12-15 11:04:33 0 [ERROR] WSREP: /bitnami/blacksmith-sandox/libgalera-26.4.9/gcs/src/gcs.cpp:gcs_open():1633: Failed to open channel 'galera' at 'gcomm://release-name-mariadb-headless.demo-4ap.svc.cluster.local': -110 (Connection timed out)
2021-12-15 11:04:33 0 [ERROR] WSREP: gcs connect failed: Connection timed out
2021-12-15 11:04:33 0 [ERROR] WSREP: wsrep::connect(gcomm://release-name-mariadb-headless.demo-4ap.svc.cluster.local) failed: 7
2021-12-15 11:04:33 0 [ERROR] Aborting
```

**Expected behavior**
The cluster successfully recovers

**Version of Helm and Kubernetes**:

- Output of `helm version`: installed by flux helm-operator 1.4.1

- Output of `kubectl version`: synced by flux 1.24.3

**Additional context**
Setting `publishNotReadyAddresses=false` in the headless service immediately fixed the problem

**Comment by juan131** [comment]
Hi @cwrau 

Thanks for reporting the issue!! This seems to be related to these changes I introduce at:

- https://github.com/bitnami/charts/pull/8364

What version of the MariaDB Galera container image are you using? Is it `10.6.5-debian-10-r29` or higher? The changes introduce in this revision (check the PR below) should be able to mitigate this issue.

- https://github.com/bitnami/bitnami-docker-mariadb-galera/pull/69/files

**Comment by cwrau** [comment]
We're version defaulted to in the helm chart v6.0.8, `10.6.5-debian-10-r26`, I haven't tried the newer versions though

I shall report back as soon as I have tested it 👍️

**Comment by juan131** [comment]
Thanks @cwrau ! Please keep us updated.

**Comment by Sufian22** [comment]
I had the same problem with chart version `v6.0.10` (10.6.5-debian-10-r29 image). I did what @cwrau said and it fixed it for me too 🚀

**Comment by juan131** [comment]
Hi everyone!

I think that it makes sense to use `publishNotReadyAddresses=true` during the 1st installation of the chart (to boost peer discovering and a faster cluster initialization) while it's problematic once the cluster has been created. Does it make sense?

What do you think about parametrized it given "false" as default value but opening the door for using "true" when installing the chart?

**Comment by cwrau** [comment]
I haven't had the chance to test the new version yet, but it would definitely be useful to have it be changeable in the chart.

You could also set it to `true` when `replicaCount` is `1` and `false` otherwise, (with a possible override maybe?), as the change seems to be exclusively for single node clusters?

**Comment by juan131** [comment]
Hi everyone, I just created a PR to make this parameter optional.

**Comment by itmwiw** [comment]
Hello @juan131 I'm still having the same issue although publishNotReadyAddresses=false. It happens quite randomly. For exemple, after the node being stuck in a crashloopback state for 30min, sometimes a 'kubectl delete pod' fix the issue.

**Comment by juan131** [comment]
Hi @itmwiw 

What version of the MariaDB Galera container image are you using? Is it greater than `10.6.5-debian-10-r38`?

> You can retrieve this information by simply running `kubectl describe pod POD_NAME`

**Comment by itmwiw** [comment]
hello @juan131 ,
I'm using 10.5.12-debian-10-r1. Additionnal informations about the use case can be found here : https://github.com/bitnami/charts/issues/8493

**Comment by itmwiw** [comment]
hi @juan131 ,
After some digging I found out that when doing an nsloockup on my headless service I got this:
```
 nslookup transaction-mariadb-galera-headless.concentrateur-preprod
Server:    172.20.0.10
Address 1: 172.20.0.10 kube-dns.kube-system.svc.cluster.local

Name:      transaction-mariadb-galera-headless.concentrateur-preprod
Address 1: 172.22.146.122 transaction-mariadb-galera-0.transaction-mariadb-galera.concentrateur-preprod.svc.cluster.local
Address 2: 172.22.98.137 172-22-98-137.transaction-mariadb-galera-headless.concentrateur-preprod.svc.cluster.local
Address 3: 172.22.219.22 transaction-mariadb-galera-1.transaction-mariadb-galera.concentrateur-preprod.svc.cluster.local
```
My unready node is being returned. Could this be the reason of my issue? (I have publishNotReadyAddresses=false though)

**Comment by juan131** [comment]
Hi @itmwiw 

I'm very glad you were able to identify the issue, did you find any other issue after upgrading coredns?

**Comment by itmwiw** [comment]
hello @juan131,
For now everything seems fine. I'm going to do some more tests on the next days.


For now it seems fine.

**Comment by npawelek** [comment]
I'm still bumping into this issue with chart version `6.1.1` and container tag `10.6.5-debian-10-r42`. 

The first time the cluster comes up with fresh PVC, it works flawlessly. Immediately attempting to scale that down and back up, the first node fails:

```
2021-12-31 10:24:37 0 [Note] WSREP: Start replication
2021-12-31 10:24:37 0 [Note] WSREP: Connecting with bootstrap option: 0
2021-12-31 10:24:37 0 [Note] WSREP: Setting GCS initial position to 00000000-0000-0000-0000-000000000000:-1
2021-12-31 10:24:37 0 [Note] WSREP: protonet asio version 0
2021-12-31 10:24:37 0 [Note] WSREP: Using CRC-32C for message checksums.
2021-12-31 10:24:37 0 [Note] WSREP: backend: asio
2021-12-31 10:24:37 0 [Note] WSREP: gcomm thread scheduling priority set to other:0
2021-12-31 10:24:37 0 [Warning] WSREP: access file(/bitnami/mariadb/data//gvwstate.dat) failed(No such file or directory)
2021-12-31 10:24:37 0 [Note] WSREP: restore pc from disk failed
2021-12-31 10:24:37 0 [Note] WSREP: GMCast version 0
2021-12-31 10:24:43 0 [Note] WSREP: (260e808d-853a, 'tcp://0.0.0.0:4567') listening at tcp://0.0.0.0:4567
2021-12-31 10:24:43 0 [Note] WSREP: (260e808d-853a, 'tcp://0.0.0.0:4567') multicast: , ttl: 1
2021-12-31 10:24:43 0 [Note] WSREP: EVS version 1
2021-12-31 10:24:43 0 [Note] WSREP: gcomm: connecting to group 'galera', peer 'mariadb-galera-headless.galera.svc.cluster.local:'
2021-12-31 10:24:43 0 [Note] WSREP: (260e808d-853a, 'tcp://0.0.0.0:4567') Found matching local endpoint for a connection, blacklisting address tcp://10.46.0.7:4567
2021-12-31 10:24:46 0 [Note] WSREP: EVS version upgrade 0 -> 1
2021-12-31 10:24:46 0 [Note] WSREP: PC protocol upgrade 0 -> 1
2021-12-31 10:24:46 0 [Warning] WSREP: no nodes coming from prim view, prim not possible
2021-12-31 10:24:46 0 [Note] WSREP: view(view_id(NON_PRIM,260e808d-853a,1) memb {
	260e808d-853a,0
} joined {
} left {
} partitioned {
})
2021-12-31 10:24:46 0 [Warning] WSREP: last inactive check more than PT1.5S ago (PT3.50114S), skipping check
2021-12-31 10:25:16 0 [Note] WSREP: PC protocol downgrade 1 -> 0
2021-12-31 10:25:16 0 [Note] WSREP: view((empty))
2021-12-31 10:25:16 0 [ERROR] WSREP: failed to open gcomm backend connection: 110: failed to reach primary view: 110 (Connection timed out)
	 at /bitnami/blacksmith-sandox/libgalera-26.4.9/gcomm/src/pc.cpp:connect():160
2021-12-31 10:25:16 0 [ERROR] WSREP: /bitnami/blacksmith-sandox/libgalera-26.4.9/gcs/src/gcs_core.cpp:gcs_core_open():220: Failed to open backend connection: -110 (Connection timed out)
2021-12-31 10:25:16 0 [ERROR] WSREP: /bitnami/blacksmith-sandox/libgalera-26.4.9/gcs/src/gcs.cpp:gcs_open():1633: Failed to open channel 'galera' at 'gcomm://mariadb-galera-headless.galera.svc.cluster.local': -110 (Connection timed out)
2021-12-31 10:25:16 0 [ERROR] WSREP: gcs connect failed: Connection timed out
2021-12-31 10:25:16 0 [ERROR] WSREP: wsrep::connect(gcomm://mariadb-galera-headless.galera.svc.cluster.local) failed: 7
2021-12-31 10:25:16 0 [ERROR] Aborting
```

**Comment by miguelaeh** [comment]
Hi @npawelek ,
Try setting `publishNotReadyAddresses` to `false` after the initial install before scaling the cluster

**Comment by npawelek** [comment]
Hi @miguelaeh, I disabled `publishNotReadyAddresses` and scaled the cluster down and back up. Different error, but same result, the cluster refuses to come back up:

```
2022-01-03  8:24:00 0 [Note] WSREP: Start replication
2022-01-03  8:24:00 0 [Note] WSREP: Connecting with bootstrap option: 0
2022-01-03  8:24:00 0 [Note] WSREP: Setting GCS initial position to 00000000-0000-0000-0000-000000000000:-1
2022-01-03  8:24:00 0 [Note] WSREP: protonet asio version 0
2022-01-03  8:24:00 0 [Note] WSREP: Using CRC-32C for message checksums.
2022-01-03  8:24:00 0 [Note] WSREP: backend: asio
2022-01-03  8:24:00 0 [Note] WSREP: gcomm thread scheduling priority set to other:0
2022-01-03  8:24:00 0 [Warning] WSREP: access file(/bitnami/mariadb/data//gvwstate.dat) failed(No such file or directory)
2022-01-03  8:24:00 0 [Note] WSREP: restore pc from disk failed
2022-01-03  8:24:00 0 [Note] WSREP: GMCast version 0
2022-01-03  8:24:00 0 [Warning] WSREP: Failed to resolve tcp://mariadb-galera-headless.galera.svc.cluster.local:4567
2022-01-03  8:24:00 0 [Note] WSREP: (cb5d3b52-af99, 'tcp://0.0.0.0:4567') listening at tcp://0.0.0.0:4567
2022-01-03  8:24:00 0 [Note] WSREP: (cb5d3b52-af99, 'tcp://0.0.0.0:4567') multicast: , ttl: 1
2022-01-03  8:24:00 0 [Note] WSREP: EVS version 1
2022-01-03  8:24:00 0 [Note] WSREP: gcomm: connecting to group 'galera', peer 'mariadb-galera-headless.galera.svc.cluster.local:'
2022-01-03  8:24:00 0 [ERROR] WSREP: failed to open gcomm backend connection: 131: No address to connect (FATAL)
	 at /bitnami/blacksmith-sandox/libgalera-26.4.9/gcomm/src/gmcast.cpp:connect_precheck():317
2022-01-03  8:24:00 0 [ERROR] WSREP: /bitnami/blacksmith-sandox/libgalera-26.4.9/gcs/src/gcs_core.cpp:gcs_core_open():220: Failed to open backend connection: -131 (State not recoverable)
2022-01-03  8:24:00 0 [ERROR] WSREP: /bitnami/blacksmith-sandox/libgalera-26.4.9/gcs/src/gcs.cpp:gcs_open():1633: Failed to open channel 'galera' at 'gcomm://mariadb-galera-headless.galera.svc.cluster.local': -131 (State not recoverable)
2022-01-03  8:24:00 0 [ERROR] WSREP: gcs connect failed: State not recoverable
2022-01-03  8:24:00 0 [ERROR] WSREP: wsrep::connect(gcomm://mariadb-galera-headless.galera.svc.cluster.local) failed: 7
```

**Comment by npawelek** [comment]
@juan131 Can we open one of these issues back up (this or 8831)? These errors are consistently reproducible with the latest versions of the chart and container.

**Comment by miguelaeh** [comment]
Hi @npawelek ,

> 2022-01-03  8:24:00 0 [ERROR] WSREP: failed to open gcomm backend connection: 131: No address to connect (FATAL)

looks like in this case, since the `publishNotReadyAddresses` is set to `false`, if there are not any ready pod the headless does not return any address.
If you can confirm that is the case, since there are not any pods actually joining the galera cluster, you can try to set the [bootstrapping parameters](https://github.com/bitnami/charts/blob/43029d4470dd3b66623d90150f56ce6791dcb801/bitnami/mariadb-galera/values.yaml#L241) to force the cluster bootstrap.

**Comment by cwrau** [comment]
@juan131 I would also like to reopen this issue, as we're running in the same problem

I've finally tried the newest version; chart 6.1.1, galera 10.6.5-debian-10-r35 and the problem still exists;


```log
mariadb 10:51:22.07 
mariadb 10:51:22.12 Welcome to the Bitnami mariadb-galera container
mariadb 10:51:22.17 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
mariadb 10:51:22.21 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
mariadb 10:51:22.26 
mariadb 10:51:22.30 INFO  ==> ** Starting MariaDB setup **
mariadb 10:51:22.55 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 10:51:22.68 INFO  ==> Initializing mariadb database
mariadb 10:51:23.09 INFO  ==> Found mounted configuration directory
mariadb 10:51:23.25 INFO  ==> Updating 'my.cnf' with custom configuration
mariadb 10:51:23.40 INFO  ==> Setting user option
mariadb 10:51:23.47 INFO  ==> Setting wsrep_node_name option
mariadb 10:51:23.59 INFO  ==> Setting wsrep_node_address option
mariadb 10:51:23.65 INFO  ==> Setting wsrep_cluster_address option
mariadb 10:51:23.72 INFO  ==> Setting wsrep_sst_auth option
mariadb 10:51:23.79 INFO  ==> Persisted data detected. Restoring
mariadb 10:51:23.92 INFO  ==> ** MariaDB setup finished! **

mariadb 10:51:24.35 INFO  ==> ** Starting MariaDB **
mariadb 10:51:24.39 INFO  ==> Setting previous boot
2022-01-04 10:51:24 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (server 10.6.5-MariaDB-log) starting as process 1 ...
2022-01-04 10:51:24 0 [Note] WSREP: Loading provider /opt/bitnami/mariadb/lib/libgalera_smm.so initial position: 00000000-0000-0000-0000-000000000000:-1
2022-01-04 10:51:24 0 [Note] WSREP: wsrep_load(): loading provider library '/opt/bitnami/mariadb/lib/libgalera_smm.so'
2022-01-04 10:51:24 0 [Note] WSREP: wsrep_load(): Galera 4.9(rXXXX) by Codership Oy <info@codership.com> loaded successfully.
2022-01-04 10:51:24 0 [Note] WSREP: CRC-32C: using 64-bit x86 acceleration.
2022-01-04 10:51:24 0 [Note] WSREP: Found saved state: fe72db12-4f8a-11ec-9611-bb2851a89870:-1, safe_to_bootstrap: 1
2022-01-04 10:51:24 0 [Note] WSREP: GCache DEBUG: opened preamble:
Version: 2
UUID: fe72db12-4f8a-11ec-9611-bb2851a89870
Seqno: 1 - 7154
Offset: 38319048
Synced: 1
2022-01-04 10:51:24 0 [Note] WSREP: Recovering GCache ring buffer: version: 2, UUID: fe72db12-4f8a-11ec-9611-bb2851a89870, offset: 38319048
2022-01-04 10:51:24 0 [Note] WSREP: GCache::RingBuffer initial scan...  0.0% (        0/134217752 bytes) complete.
2022-01-04 10:51:24 0 [Note] WSREP: GCache::RingBuffer initial scan...100.0% (134217752/134217752 bytes) complete.
2022-01-04 10:51:24 0 [Note] WSREP: Recovering GCache ring buffer: found gapless sequence 1-7154
2022-01-04 10:51:24 0 [Note] WSREP: GCache::RingBuffer unused buffers scan...  0.0% (      0/4643504 bytes) complete.
2022-01-04 10:51:24 0 [Note] WSREP: GCache::RingBuffer unused buffers scan...100.0% (4643504/4643504 bytes) complete.
2022-01-04 10:51:24 0 [Note] WSREP: GCache DEBUG: RingBuffer::recover(): found 4/7158 locked buffers
2022-01-04 10:51:24 0 [Note] WSREP: GCache DEBUG: RingBuffer::recover(): free space: 129574720/134217728
2022-01-04 10:51:24 0 [Note] WSREP: Passing config to GCS: base_dir = /bitnami/mariadb/data/; base_host = 192.168.107.184; base_port = 4567; cert.log_conflicts = no; cert.optimistic_pa = yes; debug = no; evs.auto_evict = 0; evs.delay_margin = PT1S; evs.delayed_keep_period = PT30S; evs.inactive_check_period = PT0.5S; evs.inactive_timeout = PT15S; evs.join_retrans_period = PT1S; evs.max_install_timeouts = 3; evs.send_window = 4; evs.stats_report_period = PT1M; evs.suspect_timeout = PT5S; evs.user_send_window = 2; evs.view_forget_timeout = PT24H; gcache.dir = /bitnami/mariadb/data/; gcache.keep_pages_size = 0; gcache.mem_size = 0; gcache.name = galera.cache; gcache.page_size = 128M; gcache.recover = yes; gcache.size = 128M; gcomm.thread_prio = ; gcs.fc_debug = 0; gcs.fc_factor = 1.0; gcs.fc_limit = 16; gcs.fc_master_slave = no; gcs.max_packet_size = 64500; gcs.max_throttle = 0.25; gcs.recv_q_hard_limit = 9223372036854775807; gcs.recv_q_soft_limit = 0.25; gcs.sync_donor = no; gmcast.segment = 0; gmcast.version = 0; pc.announce_timeout = PT3
2022-01-04 10:51:24 0 [Note] WSREP: Start replication
2022-01-04 10:51:24 0 [Note] WSREP: Connecting with bootstrap option: 0
2022-01-04 10:51:24 0 [Note] WSREP: Setting GCS initial position to 00000000-0000-0000-0000-000000000000:-1
2022-01-04 10:51:24 0 [Note] WSREP: protonet asio version 0
2022-01-04 10:51:24 0 [Note] WSREP: Using CRC-32C for message checksums.
2022-01-04 10:51:24 0 [Note] WSREP: backend: asio
2022-01-04 10:51:24 0 [Note] WSREP: gcomm thread scheduling priority set to other:0 
2022-01-04 10:51:24 0 [Warning] WSREP: access file(/bitnami/mariadb/data//gvwstate.dat) failed(No such file or directory)
2022-01-04 10:51:24 0 [Note] WSREP: restore pc from disk failed
2022-01-04 10:51:24 0 [Note] WSREP: GMCast version 0
2022-01-04 10:51:24 0 [Note] WSREP: (42bd5f75-95a8, 'tcp://0.0.0.0:4567') listening at tcp://0.0.0.0:4567
2022-01-04 10:51:24 0 [Note] WSREP: (42bd5f75-95a8, 'tcp://0.0.0.0:4567') multicast: , ttl: 1
2022-01-04 10:51:24 0 [Note] WSREP: EVS version 1
2022-01-04 10:51:24 0 [Note] WSREP: gcomm: connecting to group 'galera', peer 'customer-mariadb-headless.demo-4ap.svc.cluster.local:'
2022-01-04 10:51:24 0 [Note] WSREP: (42bd5f75-95a8, 'tcp://0.0.0.0:4567') Found matching local endpoint for a connection, blacklisting address tcp://192.168.107.184:4567
2022-01-04 10:51:27 0 [Note] WSREP: EVS version upgrade 0 -> 1
2022-01-04 10:51:27 0 [Note] WSREP: PC protocol upgrade 0 -> 1
2022-01-04 10:51:27 0 [Warning] WSREP: no nodes coming from prim view, prim not possible
2022-01-04 10:51:27 0 [Note] WSREP: view(view_id(NON_PRIM,42bd5f75-95a8,1) memb {
	42bd5f75-95a8,0
} joined {
} left {
} partitioned {
})
2022-01-04 10:51:28 0 [Warning] WSREP: last inactive check more than PT1.5S ago (PT3.50132S), skipping check
2022-01-04 10:51:57 0 [Note] WSREP: PC protocol downgrade 1 -> 0
2022-01-04 10:51:57 0 [Note] WSREP: view((empty))
2022-01-04 10:51:57 0 [ERROR] WSREP: failed to open gcomm backend connection: 110: failed to reach primary view: 110 (Connection timed out)
	 at /bitnami/blacksmith-sandox/libgalera-26.4.9/gcomm/src/pc.cpp:connect():160
2022-01-04 10:51:57 0 [ERROR] WSREP: /bitnami/blacksmith-sandox/libgalera-26.4.9/gcs/src/gcs_core.cpp:gcs_core_open():220: Failed to open backend connection: -110 (Connection timed out)
2022-01-04 10:51:57 0 [ERROR] WSREP: /bitnami/blacksmith-sandox/libgalera-26.4.9/gcs/src/gcs.cpp:gcs_open():1633: Failed to open channel 'galera' at 'gcomm://customer-mariadb-headless.demo-4ap.svc.cluster.local': -110 (Connection timed out)
2022-01-04 10:51:57 0 [ERROR] WSREP: gcs connect failed: Connection timed out
2022-01-04 10:51:57 0 [ERROR] WSREP: wsrep::connect(gcomm://customer-mariadb-headless.demo-4ap.svc.cluster.local) failed: 7
2022-01-04 10:51:57 0 [ERROR] Aborting
```

**Comment by npawelek** [comment]
@miguelaeh Am I correct in the assumption that I only need to use the bootstrap options when starting the cluster from a node other than node0. In the event where I scale back gracefully, I should only need to scale the cluster back up. This all worked flawlessly on with chart `6.0.3` and container `10.6.4`.

**Comment by timsamart** [comment]
I just wanted to add I have the same error with the version 10.6.5-debian-10-r35. Changed to version 10.6.5-debian-10-r23 and it is still not working. Even setting the bootstrap option to 1 manually in the volume is not fixing the issue.

`publishNotReadyAddresses` is not set at all in headless service.

```
2022-01-04 23:04:18 0 [Note] WSREP: GCache::RingBuffer unused buffers scan... 0.0% ( 0/103448 bytes) complete.
2022-01-04 23:04:18 0 [Note] WSREP: GCache::RingBuffer unused buffers scan...100.0% (103448/103448 bytes) complete.
2022-01-04 23:04:18 0 [Note] WSREP: GCache DEBUG: RingBuffer::recover(): found 2/95 locked buffers
2022-01-04 23:04:18 0 [Note] WSREP: GCache DEBUG: RingBuffer::recover(): free space: 134114632/134217728
2022-01-04 23:04:18 0 [Note] WSREP: Passing config to GCS: base_dir = /bitnami/mariadb/data/; base_host = 10.2.1.49; base_port = 4567; cert.log_conflicts = no; cert.optimistic_pa = yes; debug = no; evs.auto_evict = 0; evs.delay_margin = PT1S; evs.delayed_keep_period = PT30S; evs.inactive_check_period = PT0.5S; evs.inactive_timeout = PT15S; evs.join_retrans_period = PT1S; evs.max_install_timeouts = 3; evs.send_window = 4; evs.stats_report_period = PT1M; evs.suspect_timeout = PT5S; evs.user_send_window = 2; evs.view_forget_timeout = PT24H; gcache.dir = /bitnami/mariadb/data/; gcache.keep_pages_size = 0; gcache.mem_size = 0; gcache.name = galera.cache; gcache.page_size = 128M; gcache.recover = yes; gcache.size = 128M; gcomm.thread_prio = ; gcs.fc_debug = 0; gcs.fc_factor = 1.0; gcs.fc_limit = 16; gcs.fc_master_slave = no; gcs.max_packet_size = 64500; gcs.max_throttle = 0.25; gcs.recv_q_hard_limit = 9223372036854775807; gcs.recv_q_soft_limit = 0.25; gcs.sync_donor = no; gmcast.segment = 0; gmcast.version = 0; pc.announce_timeout = PT3S; pc.
2022-01-04 23:04:18 0 [Note] WSREP: Start replication
2022-01-04 23:04:18 0 [Note] WSREP: Connecting with bootstrap option: 0
2022-01-04 23:04:18 0 [Note] WSREP: Setting GCS initial position to 00000000-0000-0000-0000-000000000000:-1
2022-01-04 23:04:18 0 [Note] WSREP: protonet asio version 0
2022-01-04 23:04:18 0 [Note] WSREP: Using CRC-32C for message checksums.
2022-01-04 23:04:18 0 [Note] WSREP: backend: asio
2022-01-04 23:04:18 0 [Note] WSREP: gcomm thread scheduling priority set to other:0
2022-01-04 23:04:18 0 [Warning] WSREP: access file(/bitnami/mariadb/data//gvwstate.dat) failed(No such file or directory)
2022-01-04 23:04:18 0 [Note] WSREP: restore pc from disk failed
2022-01-04 23:04:18 0 [Note] WSREP: GMCast version 0
2022-01-04 23:04:18 0 [Warning] WSREP: Failed to resolve tcp://mariadb-galera-headless.kubeprod.svc:4567
2022-01-04 23:04:18 0 [Note] WSREP: (a53344a7-bae9, 'tcp://0.0.0.0:4567') listening at tcp://0.0.0.0:4567
2022-01-04 23:04:18 0 [Note] WSREP: (a53344a7-bae9, 'tcp://0.0.0.0:4567') multicast: , ttl: 1
2022-01-04 23:04:18 0 [Note] WSREP: EVS version 1
2022-01-04 23:04:18 0 [Note] WSREP: gcomm: connecting to group 'galera', peer 'mariadb-galera-headless.kubeprod.svc:'
2022-01-04 23:04:18 0 [ERROR] WSREP: failed to open gcomm backend connection: 131: No address to connect (FATAL)
at /bitnami/blacksmith-sandox/libgalera-26.4.9/gcomm/src/gmcast.cpp:connect_precheck():317
2022-01-04 23:04:18 0 [ERROR] WSREP: /bitnami/blacksmith-sandox/libgalera-26.4.9/gcs/src/gcs_core.cpp:gcs_core_open():220: Failed to open backend connection: -131 (State not recoverable)
2022-01-04 23:04:18 0 [ERROR] WSREP: /bitnami/blacksmith-sandox/libgalera-26.4.9/gcs/src/gcs.cpp:gcs_open():1633: Failed to open channel 'galera' at 'gcomm://mariadb-galera-headless.kubeprod.svc': -131 (State not recoverable)
2022-01-04 23:04:18 0 [ERROR] WSREP: gcs connect failed: State not recoverable
2022-01-04 23:04:18 0 [ERROR] WSREP: wsrep::connect(gcomm://mariadb-galera-headless.kubeprod.svc) failed: 7
2022-01-04 23:04:18 0 [ERROR] Aborting
```

**Comment by mathtasatlime** [comment]
I got the same error as @timsamart describes with version 10.6.5

**Comment by miguelaeh** [comment]
Hi guys,
I reopened the issue. This looks like a non-trivial case of scalability issues so I am going to create an internal task in order to be able to dedicate some extra time. However, I cannot provide an ETA for solving the issue.

**Comment by cwrau** [comment]
Are there any updates? Maybe we can help in some way?

**Comment by juan131** [comment]
There are no updates yet @cwrau

We simply made this optional at https://github.com/bitnami/charts/pull/8496 (chart version `6.1.0`) so you can run a `helm upgrade` and set the `service.headless.publishNotReadyAddresses` parameter to `false`.

**Comment by cwrau** [comment]
Sadly that doesn't help, at least in some cases; https://github.com/bitnami/charts/issues/8424#issuecomment-1004708023

Something seems to have changed in the scripts.

**Comment by timsamart** [comment]
I just wanted to let you know how we fixed the problem temporarily:

We managed to get our cluster running by manually mounting the mariadb volumes (after scaling the StatefulSet to "0") in a pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: dataaccess
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ['sleep', 'infinity']
    volumeMounts:
    - name: data-mariadb-galera-0
      mountPath: /data0
    - name: data-mariadb-galera-1
      mountPath: /data1
    - name: data-mariadb-galera-2
      mountPath: /data2
  volumes:
  - name: data-mariadb-galera-0
    persistentVolumeClaim:
      claimName: data-mariadb-galera-0
  - name: data-mariadb-galera-1
    persistentVolumeClaim:
      claimName: data-mariadb-galera-1
  - name: data-mariadb-galera-2
    persistentVolumeClaim:
      claimName: data-mariadb-galera-2
```
and Applying the pod:
```
kubectl apply -f ./getdata.yaml -n mynamespace
```

Then we copied the `grastate.dat` containing at least a `seqno` greater than `-1` and/or `safe_to_bootstrap: 1`:
```
# GALERA saved state
version: 2.1
uuid:    5981f182-a4cc-11e6-98cc-77fabedd360d
seqno:   1234
safe_to_bootstrap: 1
```
to the first volume (node 0) This is important! as this is the first node to start somehow and it crashes if it fails!

The `dataaccess` node was then removed and maria galera is updated to `bitnami/mariadb-galera:10.5.10-debian-10-r25
`
Then the Stateful Set was scaled up again to the maximum number of nodes in the cluster.

**Comment by cwrau** [comment]
Sadly downgrading to chart version 6.0.6 doesn't help, still crashes
6.0.3 seems to work
Then again, 6.0.4 doesn't, so it must be a change from that version

**Comment by jk-pru** [comment]
I believe the issue is in the image, not the config files. 

When I set replicas to 0, edit the statefulset to use 10.6.4-debian-10-r31 and set replicas to 3, everything restarts correctly, every single time I do this.
Setting replicas to 0, changing the image to 10.6.4-debian-10-r32 (or newer) and setting replicas to 3 allows the cluster to boot only once. Any subsequent scale 0 scale 3 action results in the same error as the OP. Also once the pods boot with 10.6.4-debian-10-r32 setting replicas: 0 results in the last terminating pod writing "seqno:   -1" to its grastate.dat file. This does not happen, when using the r31 image.

So it may have something to do with this commit?
https://github.com/bitnami/bitnami-docker-mariadb-galera/commit/28e8ed0f76e3c2be692013a166cee4ba59dfce89

**Comment by juan131** [comment]
Hi @timsamart 

Thanks so much for sharing this awesome workaround. Hopefully, we'll find a solution for this bug soon and that won't be required.

> So it may have something to do with this commit? `bitnami/bitnami-docker-mariadb-galera@28e8ed0`

Yes @jk-pru. It's a combination of the changes I introduced at that commit + [this PR](https://github.com/bitnami/charts/pull/8364) (that was later on modified at https://github.com/bitnami/charts/pull/8496)

**Comment by dejwsz** [comment]
I just commented in https://github.com/bitnami/charts/issues/8331#issuecomment-1029885465 that the last well working image for me is 10.6.4-debian-10-r43, every next one is failing - maybe this has something in common with this thread here.

**Comment by rafariossaa** [comment]
We have released a new version of the chart that should fix the issues releated with nodes not being part of the cluster and cluster not bootstraping correctly.

Chart version: 7.0.1
Galera Docker image: 10.6.5-debian-10-r66

Could you give it a try ?

**Comment by jk-pru** [comment]
I've tried it and it seems that it fixed the issue with separate clusters. Helm update and deleting mariadb-0 (to simulate a failure of the first replica) also work correctly now (previously all replicas would throw an error).

But I can still kill the cluster by setting replicas to 0 and then back to 3 (leads to the same "gcs connect failed: Connection timed out" error as before). So it still starts only if there are other replicas already active or if it's starting a new database/cluser.

**Comment by rafariossaa** [comment]
Could you try the following ?
Scale it to 0, then delete the deployment, and then start it again. 

I am not very sure right now if it would be possible to resolve the case when scaling down and up again because the nodes are not aware of that.

**Comment by jk-pru** [comment]
I tried removing the statefulset (not deployment, since we don't have one here), nothing's changed. Nor should it, once the pods are removed all the data has been writen to the PVC.

But I probably should move this discussion to #8721, seems more relevant. Updating the cluster is now possible with 7.0.1, as long as at least one replica is available at all times.

**Comment by rafariossaa** [comment]
Sorry, when I referred to "the deployment" I wanted to mean the chart. I mean: `helm delete my-galera`.

**Comment by rafariossaa** [comment]
I think the scaling up from 0 is due that now you need to indicate explicitly that you are boostraping the cluster with the `galera.bootstrap.forceBootstrap` setting.

**Comment by cwrau** [comment]
> Sorry, when I referred to "the deployment" I wanted to mean the chart. I mean: `helm delete my-galera`.

I doubt that that's gonna help, as the data is still in the PVCs. Also, at least we don't use the chart directly but as a subchart, meaning we can't easily delete the chart.
