### ISSUE TITLE
[bitnami/keycloak] keycloak-config-cli is broken in Version 5.2.7

### ISSUE THREAD

**Issue by marcos-scholtz** [bitnami/charts#8460]
The keycloak-config-cli does not work in the latest keycloak chart (5.2.7). The reason is, the "appVersion" is set to "15.1.1", so the keycloak-config-cli Job tries to run a "keycloak-config-cli-15.1.1.jar", which does not exist.

The chart uses version "4.4.0" from "bitnami/keycloak-config-cli", which I assume uses version 4.4.0 from keycloak-config-cli itself. This version does not contain a jar file for "15.1.1"  (only 15.0.2). Check https://github.com/adorsys/keycloak-config-cli/releases

There is a new version for keycloak-config-cli, "4.5.0", which also supports "15.1.1", so the solution would be to:

- update the bitnami keycloak-config-cli docker image to 4.5.0
- update the bitnami keycloak helm-chart to use the 4.5.0 image

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the information! It seems that there is an issue in our pipeline packaging the latest version of keycloak-config-cli. As soon as it is fixed we will release a new version of the keycloak chart.

As soon as there are more news we will let you know

**Comment by marcos-scholtz** [comment]
Cool, thanks a lot!

**Comment by marcos-scholtz** [comment]
I'd like to keep this issue open, since the problem still exists in the newer version. Actually the problem seems to be that there is no check or guarantee, that the embedded keycloak-config-cli compatible to the keycloak-version.

To exemplify: with Chart version 5.2.8 this was fixed, the keycloak-config-cli was updated to 4.5.0 and works with the version 15.1.1 from Keycloak that is in the Chart.
But with Chart version 6.0.0, with Keycloak 16.1.0, this won't work again. This is because the keycloak-config-cli is still the 4.5.0, and it only works with Keycloak up to 16.0.0. So I expect the same error will happen there also.
(at this moment, 4.5.0 is also the last version of keycloak-config-cli, they have not released one compatible with 16.1.0 yet)

So we actually need to solve this issue of compatibility between packaged keycloak and keycloak-config-cli.

**Comment by marcosbc** [comment]
@marcos-scholtz My understanding is that the original issue was fixed, as now the `keycloak-config-cli` container image includes the file for 16.0.0:

- keycloak-config-cli-13.0.1.jar
- keycloak-config-cli-14.0.0.jar
- keycloak-config-cli-15.1.1.jar
- **keycloak-config-cli-16.0.0.jar**
- keycloak-config-cli.jar -> keycloak-config-cli-15.1.1.jar

**Comment by marcos-scholtz** [comment]
Hi,

yes, but the latest version of the Keycloak-Chart has "appVersion: 16.1.0"
(Keycloak 16.1.0). So it will look for a "keycloak-config-cli-16.1.0.jat",
which does not exist. So the latest version has the same problem.

But you are right, perhaps we need a new issue... the actual issue is,
there is no guarantee that the embedded version of keycloak-config-cli is
compatible with the embedded keycloak version.

Should I open a new issue?

Best regards
Marcos

**Comment by marcosbc** [comment]
That is right @marcos-scholtz. [There hasn't been a release for 16.1.0 yet](https://github.com/adorsys/keycloak-config-cli/releases) so it could be good to open a new issue to improve the logic. For instance, to try and detect 16.1.0 and if it doesn't exist, try with 16.0.0, instead of just trying once.
