### ISSUE TITLE
[bitnami/keycloak] Empty secret name for KEYCLOAK_DATABASE_PASSWORD

### ISSUE THREAD

**Issue by hinorashi** [bitnami/charts#9381]
### Name and Version

bitnami/keycloak 7.1.1 

## 1. My config
Use external database (_I think other settings won't involve_):
```yml
# values.yaml
postgresql:
  enabled: false
externalDatabase:
  host: "postgres"
  port: 5432
  user: keycloak
  database: keycloak
  password: "something-here"
  existingSecret: ""
  existingSecretPasswordKey: ""
```

## 2. How I run
```sh
helm upgrade -i keycloak bitnami/keycloak -f values.yaml
```

## 3. The error
```
Warning  FailedCreate      24s (x27 over 24m)  statefulset-controller
create Pod keycloak-0 in StatefulSet keycloak failed error: Pod "keycloak-0" is invalid:
spec.containers[0].env[4].valueFrom.secretKeyRef.name: Invalid value: "":
a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.',
and must start and end with an alphanumeric character
(e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

## 4. Debugging
This is how I debug:
```sh
helm template x bitnami/keycloak -f values.yaml
```

What I see (only useful piece of info):
```yml
---
# Source: keycloak/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: keycloak
spec:
  template:
    spec:
      containers:
        - name: keycloak
          image: docker.io/bitnami/keycloak:16.1.1-debian-10-r42
          env:
           # 2 more env
           - name: KEYCLOAK_MANAGEMENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: management-password      
           - name: KEYCLOAK_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:
                  key: password
```
As you could see, the field `valueFrom.secretKeyRef.name` for `KEYCLOAK_DATABASE_PASSWORD` is empty.

## 5. Workaround
I have to manually edit the `StatefulSet`, add the secret name to be `keycloak`.

Please help to update the related templates 🐧 

### What is the expected behavior?

release successes with no warning 🐊 

### What do you see instead?

```
Warning  FailedCreate      24s (x27 over 24m)  statefulset-controller  create Pod keycloak-0 in StatefulSet keycloak failed error: Pod "keycloak-0" is invalid: spec.containers[0].env[4].valueFrom.secretKeyRef.name: Invalid value: "": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

**Comment by smolinari** [comment]
I can confirm this issue. 

Scott

**Comment by migruiz4** [comment]
Hi @hinorashi,

Thank you for reporting this issue, I'm looking into it.

P.S.: I'm editing the original post as the `values.yaml` used to reproduce the issue is missing:
```
postgresql:
  enabled: false
```

**Comment by migruiz4** [comment]
Hi again!

PR #9383 should fix this. Thank you again for reporting!

**Comment by smolinari** [comment]
@migruiz4 - Sorry to be off-topic, but is there a slack channel or Discord server or the like for the Bitnami Helm charts to discuss such problems up front? I found this problem almost a week ago, but wasn't sure if it was me, cause I'm not an experience DevOps person. I could have asked about it in the community first to get confirmation it was a chart problem and maybe could have reported it sooner. 

Thanks for the fix btw. :grinning:  

Scott

**Comment by LiberoScarcelli** [comment]
This is not closed at all. This issue is still there

> Hi again!
> 
> PR #9383 should fix this. Thank you again for reporting and the detailed description!

Hi,

this is not closed at all... this issue is still there

**Comment by smolinari** [comment]
Agreed. Somehow this got missed. 

Scott

**Comment by migruiz4** [comment]
Hi,

Due to an issue with our release process, version `7.1.2` did not include the fix for this issue. Instead, it will be included in version `7.1.3`.
